openshift-metal3/dev-scripts

01_install_requirements.sh

Its used in 02_configure_host.sh

Install additional requirements

---

01_install_requirements.sh

If there are no ssh keys on host the new one should be created automatically

01_install_requirements: create new key automatically

---

01_install_requirements.sh
02_configure_host.sh
05_run_ocp.sh
README.md
ironic/Dockerfile
tripleo-quickstart-config/roles/common/defaults/main.yml
tripleo-quickstart-config/roles/libvirt/setup/overcloud/templates/instackenv.json.j2

Add a starting point for ironic on the bootstrap node, basically working but very much WIP.

Ironic aio

---

01_install_requirements.sh
02_configure_host.sh

This way if the developer is trying modifications, those won't get
overwritten.

Use crudini to avoid altering user tuning

---

05_deploy_bootstrap_vm.sh

Fix a last minute edit of the last patch. (Causes permission error further down the script)

Remove sudo

---

05_deploy_bootstrap_vm.sh

We no longer need them as we're not using iscsi
deploy any longer, they caused problems restarting the
ironic container so don't do it. Also we can now remove
some workarounds we had.

Stop bind mounting /var and /dev

---

02_configure_host.sh

This preserves the colors, so better open the new log file with:
less -R name_of_log_file

ansible: preserve logs

---

06_deploy_masters.sh

Always rinse before you repeat.

Clean previously deployed env

---

02_configure_host.sh
06_deploy_masters.sh
common.sh

Capturing changes needed for baremetal deployments.

Changes for bare metal deployments

---

02_configure_host.sh

We have moved to use baremetal as the bridge name
Fixes #73

Update virbr0 bridge to baremetal

---

libvirt_cleanup.sh

libvirt_cleanup: remove baremetal network

---

05_deploy_bootstrap_vm.sh
06_deploy_masters.sh
README.md
ocp_install_env.sh
tripleo-quickstart-config/roles/common/defaults/main.yml
tripleo-quickstart-config/roles/environment/setup/templates/network.xml.j2

Co-authored-by: Antoni Segura Puimedon <antoni@redhat.com>

switch cluster domain to ostest.test.metalkube.org

---

01_install_requirements.sh
05_deploy_bootstrap_vm.sh
ignition_patches/master/01_core_user_pass.json
utils.sh

This patchset introduces a facility for patching master nodes just like
there is for bootstrap.

Patch master node with passwd for virsh console

---

04_setup_ironic.sh

The RHCOS image disk size is 16G so when IPA is writing
the qcow2 to disk during deployment, it has to write 16G (at least)
to the master disk. This happens 3 times, so on a virtual env we
are writting 50G during each deploy. The partitions on the RHCOS
image are only about 3.3G so we can safely reduce the disk size and
therfore reduce the amount of data ironic writes. When the master nodes
boot growfs runs and expands the filesyatem to the size available
on the master node, so we end up using all the space available anyways.
This patch in local tests takes 3 minutes off the deploy time for
the master nodes, so should speed up development time, in the
longer term we should look into changing the image upstream.

Reduce the RHCOS disk size

---

02_configure_host.sh
04_setup_ironic.sh
host_cleanup.sh

The patch takes care of removing the overcloud
network which had to be taken care of manually.

Removing overcloud network as part of cleanup.

---

02_configure_host.sh
04_setup_ironic.sh
06_deploy_bootstrap_vm.sh
host_cleanup.sh
ironic/dnsmasq.conf
tripleo-quickstart-config/roles/common/defaults/main.yml

"overcloud" and "brovc" are both tripleo terms, using
them for ironic provisioning is confusing.

Rename networks and bridges to provisioning

---

06_deploy_bootstrap_vm.sh
utils.sh

Split this out into a separate function to improve readability.

Split out etcd if-name munging

---

07_deploy_masters.sh

Now that these have simple healthchecks this should stall
the script if a problem is detected.

Check to make sure ironic containers are running

---

02_configure_host.sh
06_deploy_bootstrap_vm.sh
common.sh
ocp_cleanup.sh
utils.sh

This wasn't working but the libvirt-daemon package
provides a similar config in
/usr/share/polkit-1/rules.d/50-libvirt.rules

Replace writing out of 80-libvirt.rules

---

common.sh
config_example.sh
run_ci.sh
utils.sh

Add a script that will be triggered on github pull request,
for now just calls make but will be expanded in the future.
Not sure if this is a good idea but would like to give it a go, I got a baremetal host that I intend to reset back to a fresh centos between jobs.

Add script to run a ci job

---

07_deploy_masters.sh

This will run introspection on a manageable node. We should be able to remove this step when using fast-track deployment but its useful for now to gather introspection data.
To get introspection data:
GET http://<IP>:5050/v1/introspection/<node>/data
or via openstackclient:
export OS_TOKEN=fake-token
export OS_URL=http://localhost:6385/
openstack baremetal introspection data save <node>

Add inspect step to perform introspection

---

07_deploy_masters.sh
run_ci.sh

nothing major, just annoyances.

Small fixups

---

03_ocp_repo_sync.sh

Drop some commented out repos from this script.  Just drop them to not
confuse what's absolutely required.
Signed-off-by: Russell Bryant <rbryant@redhat.com>

03: Remove commented out repos.

---

run_ci.sh

These arn't files so the check never passed

Test for existence of metalkube directories

---

03_ocp_repo_sync.sh
05_build_ocp_installer.sh
ocp_cleanup.sh
utils.sh

The kni-installer repo is moving from the metalkube org to the openshift-metalkube org.

kni-installer moved to openshift-metalkube

---

ocp_install_env.sh

quay.io/vrutkovs/kni-release:mar14 is the updated tag since there
were issues with the build from yesterday

Update temporary OCP image override

---

01_install_requirements.sh

Required to unzip terraform archive.

Install missing unzip dependency

---

assets/files/etc/keepalived/keepalived.conf.template

See https://github.com/openshift/installer/pull/1421

Switch keepalived checks to readyz

---

08_deploy_bmo.sh
Makefile
README.md

Deploy baremetal-operator in the openshift-machine-api namespace/project.
Add cleanup logic for localized changes introduced by the above changes.
Add deploy of baremetal-operator as the last step of make and update
documentation.

Deploy baremetal-operator in the openshift-machine-api namespace.

---

07_deploy_masters.sh

Signed-off-by: karmab <karimboumedhel@gmail.com>

Mark masters as workers for router pods to get running

---

assets/files/usr/local/bin/haproxy.sh

This commit enables ha-proxy statistics for the self-hosted OCP-API
load balancer.

OCP-API loadbalancer - enable statistics

---

08_deploy_bmo.sh
09_deploy_manifests.sh

We want to better catch errors should they occur.

Adding 'set -ex' where missing.

---

get_images.sh

Signed-off-by: karmab <karimboumedhel@gmail.com>

Use current rdo ironic python agent tar

---

assets/files/usr/local/bin/haproxy.sh

Set statistics port in haproxy.cfg file also when haproxy.cfg
file is reconfigured.

Fix haproxy statistics bug

---

04_setup_ironic.sh
07_deploy_masters.sh
host_cleanup.sh
ironic/dnsmasq.conf

Split the Ironic container into ironic, dnsmasq, and httpd containers.

Split up Ironic container into multiple containers

---

10_deploy_rook.sh

Signed-off-by: karmab <karimboumedhel@gmail.com>

Set properly GOPATH variable when deploying rook

---

masters_cleanup.sh

Add common for the benefit of logging output

Add common to masters_cleanup.sh

---

masters_cleanup.sh
ocp_cleanup.sh

Add common for the benefit of logging output

Add common logging to ocp cleanup

---

README.md
ironic_hosts.json.example

Added example json file for ironic hosts

---

07_deploy_masters.sh

oc get is for humans and is not script safe. Use a "-o" so we get something
script safe.
Drop all usage of --config since it was used inconsitenctly and the kubeconfig
was already set by common.sh
Stop doing bash loops for operations which are selectable across labels
by kubernetes.

Make master node mutation be script safe

---

README.md

Explain this repository to new users, and show how we expect to promote the workflow concepts after they bake in:
dev-scripts.git -> kni-installer.git -> openshift-installer.git

README: describe the purpose and future of this repository

---

07_deploy_masters.sh
assets/files/etc/selinux/config
assets/files/usr/local/bin/get_vip_subnet_cidr
assets/templates/99_master-api-haproxy.yaml
assets/templates/99_master-coredns.yaml
assets/templates/99_master-keepalived.yaml
assets/templates/99_master-mdns-publisher.yaml
assets/templates/99_master-remove-nic.yaml
assets/templates/99_master_permissive_selinux.yaml
assets/templates/99_worker-coredns.yaml
assets/templates/99_worker-mdns-publisher.yaml
common.sh
run_ci.sh
utils.sh

Rework #192 w/ additional fixes
Not sure if permissive selinux is required though

Automatically use latest RHCOS build

---

README.md

Mention facet wrapper API project and how it relates to this project.

README: describe future with facet

---

demo/launch_demo_bmo.sh

It's easy to misconfigure the demo-mode server, so let's automate it
to make it simpler.

add a script to run the baremetal operator in demo mode

---

01_install_requirements.sh
02_configure_host.sh
03_ocp_repo_sync.sh
04_setup_ironic.sh
05_build_ocp_installer.sh
06_create_cluster.sh
08_deploy_bmo.sh
09_deploy_manifests.sh
10_deploy_rook.sh
common.sh
logging.sh

Use a separate include for logging

---

common.sh
run_ci.sh

Cache the kni-installer data in CI
and fix a typo in the RHCOS image name

Cache installer

---

10_deploy_rook.sh

- we also dont use any csi for the moment

use latest ceph

---

02_configure_host.sh

There was a typo that was comparing two times with
MANAGE_PRO_BRIDGE

Fix problem in managing baremetal bridge

---

extras/common.sh
extras/kafka.sh

Fixing a small error locating common script on new extra folder

Fix: error locating the common script on extra folder

---

Makefile

(re)building a cluster can take a while. Ring a bell at the end so we
can tell it is done, even if we aren't watching it run.

ring a bell when the scripts finish

---

extras/kafka.sh

The route is not ready when the dash are submited, postpossed to did it after producer and consumer deployment.

Fix: Error on dashboard POST to grafana

---

06_create_cluster.sh

This manually updates the status of the Machine objects to contains:
1) nodeRef pointing back to the Node
2) addresses of the Node, copied to the Machine

Set up the node -> machine mapping

---

06_create_cluster.sh
fix_certs.sh
ocp_cleanup.sh

Because life is too short for broken certs.

Run fix_certs script automatically

---

assets/files/etc/kubernetes/manifests/mdns-publisher-worker.yaml
assets/files/etc/kubernetes/static-pod-resources/mdns/worker-config.template
assets/templates/99_worker-mdns-publisher.yaml

Without this change the masters would announce themselves as members of the etcd cluster as well

mdns-publisher: remove master things

---

tripleo-quickstart-config/roles/common/defaults/main.yml

We now create 1 worker VM instead of 3.

Only set hostname for single worker.

---

.gitignore
assets/files/etc/chrony.conf
assets/templates/99_master-chronyd-redhat.yaml.optional
assets/templates/99_worker-chronyd-redhat.yaml.optional
ocp_cleanup.sh
utils.sh

Config NTP server accessible on the red hat network.

---

03_ocp_repo_sync.sh
common.sh
ocp_install_env.sh
utils.sh

Send the node properties inside flexible maps, to allow different
number of masters in the future. Set a NUM_MASTERS var that defaults to 3,
with the possibility of changing to 1 in the future.

Change the data structure to allow configurable master count

---

run_ci.sh

I had an almost successful CI run this morning: http://10.8.144.11:8080/job/dev-tools/584/console.  The final step of CI seems to be the problem. This is the error:
```
+ for FILE in '$FILESTOCACHE'
++ basename /opt/dev-scripts/ironic/html/images/-openstack.qcow2
+ '[' '!' -f /opt/data/filecache/-openstack.qcow2 ']'
++ basename /opt/dev-scripts/ironic/html/images/-openstack.qcow2
+ sudo cp /opt/dev-scripts/ironic/html/images/-openstack.qcow2 /opt/data/filecache/-openstack.qcow2
cp: cannot stat ‘/opt/dev-scripts/ironic/html/images/-openstack.qcow2’: No such file or directory
```
The problem is we set `FILESTOCACHE` at the beginning of CI before we actually know the image name - we get that from the installer in step 3.  At the start of CI, `$RHCOS_IMAGE_FILENAME_OPENSTACK` isn't set... …

Fix rhcos image caching in CI

---

extras/sqlserver.sh

this provides a sample script to deploy
- dotnet project
- sqlserver pod

Sqlserver script

---

11_register_hosts.sh

Only create workers if the file is not empty

---

link-machine-and-node.sh

$machine_name does not exist, this change fixes it to $machine

Fix machine name in PATCH url

---

Makefile
host_cleanup.sh
ironic_cleanup.sh

Allow some flexibility in doing a cleanup for ironic without having
to rerun the 02 script.

Split ironic cleanup into a separate script

---

10_deploy_rook.sh

Signed-off-by: Sage Weil <sage@redhat.com>

10_deploy_rook.sh: enable pg_autoscaler; set rbd pool target_ratio to .5

---

10_deploy_rook.sh

Removed CEPH_VERSION as required version provided by default
Changed to new build of rook with important fixes
Changed git version to get pinned yaml files
Reduced ROOK_MON_HEALTHCHECK_INTERVAL and ROOK_MON_OUT_TIMEOUT
Removed useAllDevices:true as provided as default in yaml
failureDomain set to host
Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

Rook+Ceph Updates

---

extras/02_kafka.sh

Feat: Added the capability to set the scrape time of Prometheus and t…he Kafka Retention Period via env variable

Prometheus Scrape time and Kafka Retention Period via env Var

---

link-machine-and-node.sh

Otherwise we can race and the curl fails because the proxy port isn't
yet ready
Closes: #466

WIP Wait for proxy in link-machine-and-node.sh

---

ocp_cleanup.sh

Clean up fix_certs timer even after an error

---

README.md

Signed-off-by: David Galloway <dgallowa@redhat.com>

Fix broken links and filenames in CPU/mem/disk docs

---

10_deploy_rook.sh

Due to 5s interval UI looks out of sync. This change makes status changes in UI smoother.
Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

Decreasing interval to 2s for prometheusRules

---

09_deploy_kubevirt.sh

This should resolve https://github.com/openshift-metal3/dev-scripts/issues/524

Making sure project scope is returned to the current project

---

docs/developing-installer.md

The repo is called kni-installer, not kni-install.

Change repo name to kni-installer

---

01_install_requirements.sh
03_ocp_repo_sync.sh
09_deploy_kubevirt.sh
10_deploy_rook.sh
utils.sh

The colors in lolcat in particular are not great for logs.
figlet isn't necessary, and the scripts are so verbose that you
don't really see these messages easily anyway.
Fixes #594.

Drop figlet and lolcat.

---

manifests/100_cnv_kubevirt_op.yaml

this addresses issues with latest ocp

Update kubevirt version

---

assets/templates/99_master-chronyd-custom.yaml.optional
assets/templates/99_worker-chronyd-custom.yaml.optional
utils.sh

Avoid messing the git repo

---

06_create_cluster.sh
ocp_install_env.sh

To test
- Check out this PR
- Check out https://github.com/openshift-metal3/kni-installer/pull/106 to `~/go/src/github.com/openshift-metalkube/kni-installer`
- Install with `KNI_INSTALL_FROM_GIT=true make`
Will build a KNI release image when installer PR is merged.

Rebase on 4.2.0-0.ci-2019-06-19-140700

---

ocp_install_env.sh

Needs https://github.com/openshift-metal3/kni-installer/pull/117

Use 'baremetal' build tag instead of 'ironic'

---

run_ci.sh

As we now have an openshift PR open, it's important to not have
regressions on their checks like lint, fmt, shellcheck, et al.  This
runs those on kni-installer PR's.

Run some of openshift CI on installer PR's

---

ocp_install_env.sh

Testing with https://github.com/openshift-metal3/kni-installer/pull/128

Align install-config with kni-installer machinepools fix

---

common.sh
ocp_install_env.sh

Just openshift-metal3/dev-scripts#647 rebased, and with a release image that includes openshift-metal3/kni-installer#129

Rebase on 4.2.0-0.ci-2019-07-03-145946

---

06_create_cluster.sh

The only remaining change we have running after exiting early from the
install process is adding IPs to the master Machines.  This is to
enable auto approval of CSRs.  We also have a cron job that does this,
so it's not necessary to do this in the middle of the install.  The
change moves it to post-install.
Related issues:
https://github.com/openshift-metal3/kni-installer/issues/60
https://github.com/openshift-metal3/dev-scripts/issues/260
https://github.com/metal3-io/baremetal-operator/issues/242

Demonstrate installer early exit is not necessary.

---

common.sh
ocp_install_env.sh

RHCOS image locations have changed
Bring in openshift-metalkube/kni-installer#136

Fix RHCOS location and update to no-early-exit installer

---

common.sh
ocp_install_env.sh

Testing https://github.com/openshift-metal3/kni-installer/pull/158

4.2.0-0.nightly-2019-07-12-041904 rebase

---

README.md

Added DNS_VIP requisites for baremetal

---

bootkube_log.sh
bootstrap_ironic_log.sh
bootstrap_openshift_log.sh
show_bootstrap_log.sh

Add a script that connects to the bootstrap node to show logs for a
service passed as argument, then update the existing scripts to use
that.
Add a new script to look at the ironic logs.

add more tool scripts for showing bootstrap logs

---

02_configure_host.sh

These rules should no longer be needed since Ironic has moved to the
bootstrap VM.

Drop some ironic related firewall rules.

---

config_example.sh

Begin documenting some of the variables that can be set in config.sh env file

document some of the variables used in config_example.sh

---

run_ci.sh

This was previously disabled while we got some issues fixed up with
the baremetal-operator deployment.  This should now be working.
Part of #739

Update CI to wait for a worker to come up.

---

01_install_requirements.sh
02_configure_host.sh

https://github.com/metal3-io/metal3-dev-env/pull/37
This PR includes two commits:
1) A temporary commit to run CI with the metal3-dev-env PR applied.
2) The dev-scripts change we need to merge at the same time as metal3-dev-env PR 37

Updates for metal3-dev-env PR #37

---

01_install_requirements.sh

Temporarily work around a dependency failure on RHEL8.  The issue is
tracked here: https://bugzilla.redhat.com/show_bug.cgi?id=1750866

rhel8: work around bz 1750866.

---

common.sh

Added a -p to make sure the working dir gets fully created. (Ran into this when I deleted /opt trying to clear working cache)

Minor update to make sure the working dir gets created

---

04_setup_ironic.sh
common.sh
ironic_cleanup.sh

This aligns with https://github.com/metal3-io/metal3-dev-env/pull/48
which landed recently and is required to fix metal3 CI.

Switch to containerized vbmc/sushy-tools

---

11_register_hosts.sh
README.md
common.sh
config_example.sh
run-custom-mao.sh

These changes make it possible to test MAO changes that are
in-flight on the dev-scripts CI.

Add a way to test MAO changes in CI

---

01_install_requirements.sh

There is no RHEL8 package for this AFAICS so lets run it
in a container which should work on both centos7 and el8 hosts.

Run docker-distribution in a container

---

README.md

This updates the description for the 01/02/04 scripts

Update README with more script details

---

README.md

Add web UI guidelines to 'Interacting with the deployed cluster' section

Add web UI guidelines to README

---

common.sh
ocp_install_env.sh

Tests all the outstanding installer changes, as well as the IPv6 Ironic
image PR to make sure it's not going to break IPv4.

Add workarounds to fix installations

---

ocp_install_env.sh

Remove merged installer PR from fixups

---

run_ci.sh

Looks like we're regularly hitting this now, add another 20 seconds.

Bump up timeout on make command

---

04_setup_ironic.sh

Both MIRROR_IMAGES=true and *_LOCAL_IMAGE rely on this
image being build so we should build it in both cases.
We had only been building it if *_LOCAL_IMAGE was set.
Fixes: #880

Always build a local release image if mirroring

---

common.sh

Filesystem type check failed when locale was not English. Thanks @hardys for the suggested solution.

Fix locale issue when checking for XFS compatibility

---

run_ci.sh

Add necessary code in run_ci.sh to test the baremetal networking
repos.

Add ci support for baremetal networking repos

---

02_configure_host.sh

This change sets up the DHCPv6 configs in ifcfg-baremetal script to allow running dev-scripts on bare metal environments.

Set up DHCPv6 baremetal interface config

---

02_configure_host.sh

This change sets up the DHCPv6 configs in ifcfg-baremetal script
to allow running dev-scripts on bare metal environments.
Backport of #904
(cherry picked from commit b07ad006edc8e49523e53af65786ee1c50d74600)

4.3 backport: Set up DHCPv6 baremetal interface config

---

ocp_install_env.sh

These are now calculated in the MAO.

Remove deploy_kernel and deploy_ramdisk

---

dev-setup.md

... otherwise sudoing to `nobody` will fail
cc #926

[docs] Don't restrict sudo to root

---

common.sh

4.5 CI builds are now available.

Move dev-scripts to 4.5 CI builds

---

04_setup_ironic.sh

We don't need/want them logged to stdout.

Don't use tee for pull secrets

---

02_configure_host.sh
04_setup_ironic.sh
common.sh
config_example.sh
rhcos.sh
vm_setup_vars.yml

This makes it easy to turn on IPv6.  Just set `USE_IPV4=false`.

Add USE_IPV4 option to make it easy to turn on IPv6 support

---

02_configure_host.sh
common.sh
config_example.sh
rhcos.sh
run_ci.sh

Set USE_IPV4=true in config to switch back to IPv4.

Use IPv6 by default.

---

README.md
config_example.sh
vm_setup_vars.yml

This allows to set resources for master/worker VMs via env
variables in config_$USER.sh

Adds options to configure resources for master/worker VMs

---

run_ci.sh

Download times for this file seem to vary a lot.

Cache the download of the oc client in CI

---

04_setup_ironic.sh

* Do not stop them when we start a cluster, in case we have multiple
clusters.
* Do not try to start them if they are already running from a previous
cluster.
* Remove the vbmc PID file when starting it because it frequently
leaves the file behind.

improve vbmc and sushy-tools management

---

README.md
common.sh
config_example.sh

Seems the website has changed a bit.  Update the URL to point to the new
pull secret location.

Update pull secret location.

---

04_setup_ironic.sh
ocp_install_env.sh
utils.sh

These were getting left behind on failure.

Remove tmp files with a trap

---

common.sh

Having common.sh echo messages to stdout interferes with scripts that
use config to find individual values.

multi-cluster: move messages to stderr

---

images/Dockerfile.ci

Add base image that will be used to run the e2e-metal-ipi test

base image for OpenShift CI integration

---

images/Dockerfile.ci

Required by https://github.com/openshift/release/pull/8420

Rename base ci image

---

01_install_requirements.sh
02_configure_host.sh
common.sh

Install the openstack script provided by metal3-dev-env

Install the openstack wrapper script

---

04_setup_ironic.sh
must_gather.sh
ocp_install_env.sh

Add --tmpdir argument to ensure they go to ${TMPDIR:-/tmp}.

ensure temporary files are placed in the temporary directory

---

assisted_deployment.sh

@hardys  we started to move our repoes to openshift org

Moving assisted deployment to clone openshift/assisted-test-infra repo

---

OWNERS

add zaneb to the owners file

---

02_configure_host.sh

metal3-dev-env already does this, just bringing parity.

Install the baremetal command along with openstackclient

---

README.md

The README didn't mention this previously

Add docs re NUM_EXTRA_WORKERS

---

01_install_requirements.sh
02_configure_host.sh
03_build_installer.sh
04_setup_ironic.sh
05_create_install_config.sh
06_create_cluster.sh
cache_cleanup.sh
common.sh
host_cleanup.sh
ironic_cleanup.sh
ocp_cleanup.sh
podman_cleanup.sh
registry_cleanup.sh
validation.sh
workingdir_cleanup.sh

- Reorganize validation to make it easier to run separate tests when
building a cluster vs. cleaning up a host.
- Add an early check to ensure the CI_TOKEN is valid.

validation improvements

---

common.sh

I regularly see DNS resolution failures in the step that looks up the
latest CI image.  I can't reproduce them on demand, but they happen a
lot. This change adds a small loop around that step to try a few times
if there is an error.

retry discovering the latest ci image

---

config_example.sh

Add two notes for things that are easy to forget/misinterpret.

Clarify using local images in config_example.sh

---

02_configure_host.sh

CI is currently failing with error below. This is a new problem, but
seems to be because libvirt is trying to use iptables since it was
started before firewalld. Moving the 02 stuff around to make sure we
always restart libvirtd after firewalld.
```
Executing: /usr/lib/systemd/systemd-sysv-install enable network
+(./02_configure_host.sh:168): main(): '[' y == y ']'
+(./02_configure_host.sh:169): main(): sudo virsh net-destroy ostestbm
Network ostestbm destroyed
+(./02_configure_host.sh:170): main(): sudo virsh net-start ostestbm
error: Failed to start network ostestbm
error: internal error: Failed to apply firewall rules /usr/sbin/iptables
-w --table filter --insert LIBVIRT_INP --in-interface ostestbm
--protocol tcp --destination-port 67 --jump ACCEPT: iptables: No
chain/target/match by …
```

Bug 1905115: Restart libvirt to detect we are using firewalld

---

04_setup_ironic.sh
base-image/Dockerfile
base-image/prepare-image.sh
config_example.sh

This change refactor the way we build the base-image used to build
custom images and allow users to select a different base image for
the base-iamge itself.

Allow to change the image the base-image is built from

---

common.sh
config_example.sh

This changes the default development version to 4.8.

Bump dev-scripts to 4.8

---

README.md

link troubleshoot section directly

---

common.sh

docker.io rate limiter is too restrictive.

using registry image pulled from quay.io registry

---

01_install_requirements.sh

Reverts openshift-metal3/dev-scripts#1225
The repos should be fixed now. Let's see

Revert "Temporary workaround for the gnutls issue"

---

podman_cleanup.sh

Pretty self-explanatory. I'm not expecting to have this in an automated setup. :)

Do not wait for confirmation on podman cleanup actions

---

OWNERS

Signed-off-by: Flavio Percoco <flavio@redhat.com>

Adding flaper87 to the OWNERS file

---

02_configure_host.sh
common.sh
config_example.sh

Just a simple configuration that I'm missing in dev-scripts.

allow configuring sushy-tools to ignore boot devices

---

04_setup_ironic.sh
common.sh
config_example.sh
run_ci.sh

Remove explicit references to ironic-inspector-image as it was merged into the ironic-image container

Changes post ironic/inspector merge

---

metallb/OWNERS

Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>

Update MetalLB OWNERS file

---

metallb/deploy_operator.sh
metallb/metallb-operator-deploy/controller_manager_patch.yaml

Updating the FRR image to the d/s image built in CI.

MetalLB: Set default BGP type to FRR and Update FRR image

---

06_create_cluster.sh
metallb/deploy_operator.sh

Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>

fix frr image tag

---

01_install_requirements.sh

Get Centos packages from Vault

---

README.md

Signed-off-by: Andreas Karis <ak.karis@gmail.com>

Update documentation for parameters in README

---

common.sh

It was changed from master to main recently

Fix default ironic image quay branch

---

Makefile
agent/03_agent_deployment.sh
agent/OWNERS
agent/README.md
agent/cleanup.sh
agent/common.sh
config_example.sh
utils.sh

This patch adds an initial support for the agent based installer workflow, so that the agent team could start using it. Further improvementes and Ansible refactoring(s) will be addressed in subsequent PRs.

AGENT-20: Add agent target to deploy agent installer

---

05_create_install_config.sh
agent/03_agent_deployment.sh
network.sh

Also, refactored the existing code to share the api/ingress vip build logic

agent: using api vip, ingress vip, cluster name and base domain for generating the agent manifests

---

ocp_cleanup.sh
registry_cleanup.sh

Avoid some errors that could cause trouble when cleaning the
environment.

Improve cleaning

---

config_example.sh

This updates the formatting of config_example.sh. I tried to keep the content the same as much as possible. I have made some Ansible that will generate a config_$USER.sh for you and this is what the generated config_$USER.sh looks like.
@zaneb @pawanpinjarkar @andfasano @rwsu @bfournie

AGENT-51: Update config_example.sh to be more documented

---

agent/04_agent_configure.sh
config_example.sh

Deploy SNO cluster with agent installer.
Ref:
https://issues.redhat.com/browse/AGENT-152
https://issues.redhat.com/browse/AGENT-130

AGENT-152: Deploy SNO cluster with agent installer

---

01_install_requirements.sh
02_configure_host.sh
config_example.sh

BM hosts need to be powered down so and old
cluster doesn't clash with the new one being
installed
Also change the config example of "NODES_PLATFORM"
to match what is in the README.

Power BM hosts down

---

common.sh

Set WORKER_DISK size.
Use lowercase for IP_STACK value.

Fixes to Agent Scenario configuration

---

01_install_requirements.sh
02_configure_host.sh
network.sh

Also update metal3-dev-env git hash

Bump Ansible version to 5.9.0

---

agent/04_agent_configure.sh

Remove the unwanted fields from the ClusterDeployment.Spec.

AGENT-283: Remove unwanted ClusterDeployment.Spec fields

---

agent/04_agent_configure.sh

Add a sample extra manifest during agent based installation

AGENT-231: add extra manifests

---

agent/05_agent_create_cluster.sh

Use the new wait-for validations-ok (AGENT-172) and wait-for
bootstrap-complete (AGENT-174) to determine when the bootstrap is
complete. This should give us more debug information than we have had
hitherto.

AGENT-174: Use wait-for commands to wait for bootstrap

---

agent/05_agent_create_cluster.sh

This patch allows deploying the Assisted UI by setting the `AGENT_ENABLE_GUI` config variable. This feature is meant just for debugging/testing purpouses

AGENT-291: Enable assisted UI

---

agent/release/billi-release.sh

Script to prepare a BILLI release from a specific git commit.

billi release script

---

agent/04_agent_configure.sh

networkType is set to OpenShiftSDN if IP_STACK == v4
networkType is set to OVNKubernetes if IP_STACK == v4v6|v6

AGENT-325: Set AgentClusterInstall networkType using IP_STACK

---

agent/04_agent_configure.sh
agent/05_agent_create_cluster.sh
agent/assets/mce/agent_mce_0_01_lso_namespace.yaml
agent/assets/mce/agent_mce_0_02_lso_operatorgroup.yaml
agent/assets/mce/agent_mce_0_03_lso_subscription.yaml
agent/assets/mce/agent_mce_0_03_mce_namespace.yaml
agent/assets/mce/agent_mce_0_04_mce_operatorgroup.yaml
agent/assets/mce/agent_mce_0_05_mce_subscription.yaml
agent/assets/mce/agent_mce_1_01_localvolumes.yaml
agent/assets/mce/agent_mce_1_02_mce.yaml
agent/assets/mce/agent_mce_1_03_agentserviceconfig.yaml
agent/assets/mce/agent_mce_1_04_clusterimageset.yaml
agent/assets/mce/agent_mce_1_05_autoimport.yaml
agent/common.sh
common.sh
config_example.sh
utils.sh

This patch introduces a new specific agent config variable to deploy MCE in a connected environment

AGENT-329: add mce deployment

---

agent/README.md

Signed-off-by: Saravanakumar Arumugam <sarumuga@redhat.com>

agent: Update README about AGENT_E2E_TEST_SCENARIO variable

---

04_setup_ironic.sh

The payload image is called machine-image-customization-controller.

Adjust for image-customization-controller image rename

---

agent/04_agent_configure.sh
agent/assets/ztp/registries-conf-playbook.yaml
agent/assets/ztp/registries_conf.j2

Looking to fix some of the feedback in #1458.
/cc @andfasano @bfournie

AGENT-331: Fix variable export issue

---

common.sh

This changes the default development version to 4.12

Bump OPENSHIFT_RELEASE_STREAM to 4.12

---

agent/04_agent_configure.sh
network.sh
ocp_install_env.sh

Addressing some nits from #1467 and (hopefully) making dual-stack VIPs logic a bit easier to read.

Cleanup parts of dual-stack VIPs logic

---

agent/04_agent_configure.sh
agent/gather.sh

Signed-off-by: Pawan Pinjarkar <ppinjark@redhat.com>

AGENT-350: Run agent_gather on the hosts

---

agent/04_agent_configure.sh
agent/cleanup.sh
agent/gather.sh

Signed-off-by: Pawan Pinjarkar <ppinjark@redhat.com>

Use V4 addresses in case of dual stack. Use hostnames instead of host ip

---

common.sh
config_example.sh

TRIVIAL: Update docs and add a comment in common.sh as a reminder when default value changes.
This is a minor cont to https://github.com/openshift-metal3/dev-scripts/pull/1459
Signed-off-by: Flavio Fernandes <flaviof@redhat.com>

Doc: default release is now 4.12

---

utils.sh

TRT-676
I'm trying to use the extra assets feature in my PR[1] but it has two problems:
- it errors if the directory is empty
- it does not look for .yml files (only .yaml)
This fixes both problems.
[1] https://github.com/openshift/release/pull/35105

Fix handling of extra assets

---

01_install_requirements.sh

by enabling fastest mirror and more parallel downloads

Speed up dnf downloads

---

02_configure_host.sh
utils.sh

Avoid unbound variables

---

scripts/periodics_pass_rates.sh

Add padding to pass rates script output

---

agent/e2e/agent-tui/test-fix-wrong-dns.sh

Required by https://github.com/openshift/release/pull/41015

agent: slow down key events

---

01_install_requirements.sh

It can help in case of cache and metadata issues, as well as local
dnf db shenanighans.
Also use nobest option for dnf upgrade.

OCPBUGS-18078: Clean dnf data before system upgrade

---

config_example.sh
utils.sh

Allowing extra container assest to be added in a IPv6/dissconnected deployment

Add mirroring support to ASSETS_EXTRA_FOLDER

---

config_example.sh

Add extra network/nic to sample config

---

agent/docs/custom-release.md

Added dedicated doc on how to use a custom release for developing/testing in the agent workflow

Agent custom release payload doc

---

02_configure_host.sh

With newer CS9 and RHEL-9, libvirtd has moved to a modular, socket activated layout.
This new layout conflicts with the single, monolithic "libvirtd.service" that was restarted until now, creating issues with other projects that may wrap this metal3-dev-env.
There is a related PR against metal3-env-dev[1].
[1] https://github.com/metal3-io/metal3-dev-env/pull/1313

Properly manage libvirt services

---

01_install_requirements.sh

This reverts commit 1fb4ebfea498b423eab8e2e42bea760669c6a81c.

Revert "Upgrade to Ansible 7 (#1523)"

---

01_install_requirements.sh

Update metal3-dev-env hash and set default Ansible version to 8.0.0

Move to Ansible 8

---

01_install_requirements.sh

Remove metal3-dev-env hack as the new hash points to the fix:
https://github.com/metal3-io/metal3-dev-env/commit/868665523cb10ce723bce48ea4e9b22edcd68f68

Update metal3-dev-env hash to remove hack

---

utils.sh

A pattern of metal-only flakes has been detected which fail on mirroring:
```
oc adm release mirror --insecure=true --keep-manifest-list=true -a /opt/dev-scripts/pull_secret.json --from registry.build05.ci.openshift.org/ci-op-9k3yt5ly/release@sha256:65e7d3738f4ae2cce61d61289ba149a5effef601e7730000e050e302468a8981 --to-release-image virthost.ostest.test.metalkube.org:5000/localimages/local-release-image:65e7d3738f4ae2cce61d61289ba149a5effef601e7730000e050e302468a8981 --to virthost.ostest.test.metalkube.org:5000/localimages/local-release-image
+(utils.sh:463): setup_legacy_release_mirror(): tee /opt/dev-scripts/registry/ostest-image_mirror-65e7d3738f4ae2cce61d61289ba149a5effef601e7730000e050e302468a8981.log
Flag --print-mirror-instructions's value 'icsp' has been deprecated. Use 'idms' …
```

Tolerate temporary flakes in CI registry

---

Makefile
agent/agent_post_install_validation.sh
common.sh
config_example.sh

Added 5CONTROL and 4CONTROL as additional AGENT_E2E_TEST_SCENARIOs.
Added post install validation to count number of master and worker nodes matches NUM_MASTERS and NUM_WORKERS.

AGENT-991: Scenarios for 4 and 5 control plane replicas

---

agent/roles/manifests/templates/agent-config_yaml.j2

NO-JIRA: configure some additional NTP server for the default agent-config.yaml

---

agent/common.sh

Fixes an unbound variable when running cleanup.sh.

Fix unbound variable in agent/cleanup.sh

---

config_example.sh
ocp_install_env.sh
utils.sh

Added workload partitioning block to install config
Added two node fencing credentials block to install config

OCPEDGE-1703: Add workload partitioning and two node fencing block to install config

---

agent/05_agent_configure.sh
agent/common.sh
config_example.sh

This PR adds the support to enable a fully disconnected (baremetal) network

AGENT-378: support for isolated network

---

README.md
config_example.sh

Adding some documentation on the effects of the OPENSHIFT_CI variable, to be referenced from other projects using it.

Add documentation on OPENSHIFT_CI variable effects

---

common.sh

Updating defaults for agent based tna deployments to be more inline with what we support

feat: update defaults for tna agent installs
