openshift-metal3/dev-scripts

images/Dockerfile.ci

Placeholder for https://github.com/openshift/release/pull/8420, to be replaced once 8420 will be consolidated

Add dummy dockerfile for CI

---

01_install_requirements.sh

When someone sets METAL3_DEV_ENV it most likely means they want
to test a local checkout so lets not reset in this case.
Also move the pin to 23eab39fe9977994aeac7ab6af603beb52059b32
which is the latest at the time of testing this PR and works
locally for me since #1017 merged.

Only pin metal3-dev-env when not using a local checkout

---

04_setup_ironic.sh
common.sh
utils.sh

We want the file to have the cluster name in it so we get different
mirror instructions for each cluster. We want the file to be in a
place that we clean up when we clean the registry so we don't
use stale info.

move the mirror log file to working dir with cluster-specific name

---

05_create_install_config.sh
06_create_cluster.sh
Makefile

When we use dev-scripts to build the infrastructure for a cluster,
we might not want it to actually run the installer. This change
separates the steps for generating the install config from the
steps for building the cluster so we can be explicit about that.

multi-cluster: separate install config from cluster build

---

images/Dockerfile.ci

This image will be used by the e2e-metal-ipi workflow currently under development in https://github.com/openshift/release/pull/8420.

Dockerfile file for dev-script image used by the OpenShift CI

---

images/Dockerfile.ci

This PR fixes the image build required for https://github.com/openshift/release/pull/8420

Fix CI image build

---

02_configure_host.sh
common.sh

CentOS 7 was marked deprecated in #1000.  Everyone really needs to be
on RHEL 8 or CentOS 8 at this point.  Drop CentOS 7 support completely
now that a warning has been in place for a bit.
RHEL 8 (or CentOS 8) is required because that's the environment we
would expect customers to use to run the installer.  Any issues with
CentOS 7 are not worth our focus anymore.

Drop CentOS 7 support completely

---

common.sh

Setting the boot device using sushy (on virt), results
in a domain reboot. This causes it to boot into RHCOS
prematurely only to be power cycled by ironic later.

Switch back to ipmi

---

01_install_requirements.sh
04_setup_ironic.sh
common.sh

A few improvements here:
- We don't need ipa downloader anymore. IPA image is embedded in the
OpenShift release so this is unused. This shaves a few minutes off an
install. It leaves support for using upstream Ironic images with
OpenShift for testing, however.
- When mirroring images, this also uses the ironic image we've already
cached instead of pointing to the upstream ironic image on Quay.
- For sushy tools and vbmc, we don't want dev environments to get out of
date, but in case of a quay outage we are OK to fail the image pulling
and used cached copies. This obviously won't work in CI where the nodes
are fresh, but at least it makes a dev environment more resilient to
outages.
Also incorporating https://github.com/openshift-metal3/dev-scripts/pull/1035 here:
- Removes operator-sdk …

Miscellaneous dev-scripts clean-ups

---

01_install_requirements.sh

We use yq in utils.sh but do not install it. There is no system
package, so we have to install via pip.
Fixes #888

install yq

---

01_install_requirements.sh

The latest metal3-dev-env includes support for logging serial console
output, so we can better troubleshoot pxe failures.

Bump metal3-dev-env requirement

---

common.sh

This doesn't apply to CI, CI always overrides OPENSHIFT_RELEASE_IMAGE to
whatever's under test, but this bumps the default for local checkouts of
dev-scripts to 4.6.

Make dev-scripts default to 4.6

---

metal3-dev/run.sh

Instead of hardcoding it, we look it up from the install state file. We
also update the operator-sdk command to conform to the latest usage
pattern.

don't hardcode provisioning ip

---

Makefile

they were moved to assisted target previously and left by mistake

removing requirements and configure from assisted_deployment

---

common.sh

Added -L flag to make curl follow redirects.
Currently I get redirects and dev-scripts is broken:
dev scripts error:
```
+++(common.sh:213): source(): curl https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4.6.0-0.ci/latest
+++(common.sh:213): source(): grep -o 'registry.svc.ci.openshift.org[^"]\+'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   146  100   146    0     0     48      0  0:00:03  0:00:03 --:--:--    48
++(common.sh:213): source(): LATEST_CI_IMAGE=
```
manual curl output:
```
curl   https://openshift-release.svc.ci.openshift.org/api/v1/releasestream/4.6.0-0.ci/latest  -i
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.17.10
Date: Wed, 24 Jun 2020 07:29:41 GMT
Content-Type: …
```

Make curl follow redirects when trying to retrieve latest CI image

---

assets/ipv6-dual-stack-no-upgrade.yaml
utils.sh

Dual-stack IPv6 is not yet enabled by default in OpenShift since it
doesn't fully work yet.  We have a feature set that allows you to turn
it on for testing purposes.  When dev-scripts is configured to bring
up a dual-stack test environment, this change adds a manifest to
enable dual-stack in the cluster.
Now that a lot of prerequisite work has started merging, we're ready
to push the dual-stack CI jobs further and this change will ensure
that dual-stack is enabled in those jobs.

ipv6: Enable dual-stack feature set

---

02_configure_host.sh
05_create_install_config.sh
common.sh
config_example.sh
host_cleanup.sh
ocp_install_env.sh
vm_setup_vars.yml

Add NUM_EXTRA_WORKERS variable to manage creating more workers than
are deployed initially. A manifest file for registering these
additional hosts is created in the ocp directory for the cluster.

support workers not included in initial deployment

---

ocp_cleanup.sh

The sed calls for removing entries from the ssh known_hosts config
assume that there are v4 and v6 addresses to be removed. If one isn't
found the pattern causes all of the entries from ~/.ssh/known_hosts to
be removed. Protect those sed calls with checks for non-empty
variables.
Also fix a typo in the reference to EXT_SUB_V6 in the invocation for
IPv6.

be more careful with cleaning up ssh known_hosts

---

common.sh
config_example.sh

Automatically look up the latest CI image for a given release stream by
setting the OPENSHIFT_RELEASE_STREAM environment variable.

Make it easier to install older releases

---

01_install_requirements.sh
config_example.sh

This allows setting BMC_DRIVER to redfish-virtualmedia. This bumps the
metal3-dev-env commit, and adds docs to config_exmaple.sh for virtual
media.

Add support for virtualmedia with sushy-tools

---

01_install_requirements.sh

If you want to build the installer from source, go 1.14 is the minimum
version.

Bump to go 1.14

---

vm_setup_vars.yml

When running a dual-stack OpenShift cluster, the cluster uses IPv4 as
the primary address family.  We should use IPv4 for the VIPs if we're
only going to use a single address family.
This came up because baremetal-runtimecfg uses the address family of
the API VIP to determine what address to look for on the Node to give
to kubelet to use as the node IP.  Dan Winship suggested that IPv4
would be a better default since that's the primary address family for
the cluster.
This is fine for a short term change, but what we really need to do is
fix this env so that we have both IPv4 and IPv6 VIPs at the same time,
but that's going to take more work and can't be solved only in
dev-scripts alone.

Use IPv4 VIPs for dual-stack envs

---

02_configure_host.sh
05_create_install_config.sh
common.sh
run_ci.sh
show_bootstrap_log.sh

Followup to #1062. There are a bunch of other places that assumed that if an IPv6 subnet is defined, then we prefer IPv6. Also, two places used `${IP_STACK}` in a way that didn't take the possibility of `"v4v6"` into account.
I'm not sure if [this code](https://github.com/openshift-metal3/dev-scripts/blob/b1e7c89fb5412b4da001c25fce5a5a394bebb635/02_configure_host.sh#L159) is single-stack IPv6-specific or if it works with dual-stack?
Not tested because I don't know how to test it...
/assign @russellb

Further single-stack IPv6 vs dual-stack updates

---

common.sh
config_example.sh

We've been seeing different behavior between the ci and
nightly builds, so this makes it easier to switch between
them to compare, e.g to deploy latest nightly
export OPENSHIFT_RELEASE_TYPE=nightly

Add OPENSHIFT_RELEASE_TYPE variable

---

ocp_install_env.sh

Explicitly list the namespace for the secrets and hosts so it doesn't
matter what project context is set when oc is used to add them to the
cluster.

ensure extra hosts are created in the right namespace

---

01_install_requirements.sh
common.sh

Creates some VMs with ipmi and others with redfish, so
dev-scripts will test both paths.

Switch to "mixed" mode for VM management

---

common.sh

Redfish is currently erroring with this below due to wrong sushy tools library in the ironic images.
```
level=error msg="Error: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'Failed to inspect hardware. Reason: unable to start inspection: 'System' object has no attribute 'set_system_boot_options''"
level=error
level=error msg=" on ../../tmp/openshift-install-695067531/masters/main.tf line 1, in resource \"ironic_node_v1\" \"openshift-master-host\":"
level=error msg=" 1: resource \"ironic_node_v1\" \"openshift-master-host\" {"
level=error
level=error
```

Temporarily revert to using IPMI only

---

02_configure_host.sh
config_example.sh
host_cleanup.sh

In order to properly test unicast VRRP with keepalived, it is desirable to
block multicast on the provisioning host.
This patch does so with ebtables. Additional config will be required in
vm_setup_vars.yml to create external SRV records, since coredns-multicast
will no longer be working.

Enable the ability to block multicast traffic for testing

---

metal3-dev/pause-control-plane.sh

Sometimes when working on the baremetal-operator it is useful to have
it ignore hosts so the logs do not become cluttered with the usual
regular updates. This script applies the pause annotation to the
control plane hosts so the baremetal-operator will stop regularly
checking their power state.

add script for pausing bmo management of control plane hosts

---

common.sh

This restores redfish as the default for all users, and mixed mode as
the default for CI.

Restore redfish/ipmi mixed mode as default for BMC's

---

utils.sh

It's possible for this to be empty, e.g if we fail the resolution
of clock.redhat.com no custom DNS manifests get created
This appears to currently be the case in CI, so we fail like:
cp: cannot stat 'assets/generated/*.yaml': No such file or directory

Handle empty assets/generated dir

---

images/Dockerfile.ci

We need to pull the latest ansible collections into this image in order to start using tags for packet servers.

Add the latest ansible collections to Openshift CI image

---

04_setup_ironic.sh
base-image/Dockerfile
config_example.sh

One problem we have at the moment is testing with custom built
images using the same repositories and configuration from Openshift
upstream and downstream customization.
This patch introduces a bsae-image container that can be used to build
local images using for example custom repositories.
To be able to do that, we introduce 1 new variable that can be set
in the config file: CUSTOM_REPO_FILE
The CUSTOM_REPO_FILE is the name of a file that contains the custom
repositories that we want to use to install packages from, e.g.
export CUSTOM_REPO_FILE=ocp46.repo
The file needs to be present in the base-image dir.

Allow testing with custom base images

---

docs/custom-mao-and-capbm.md
mao-images.sh

Sometimes when working with the machine-api-operator it is not
necessary to provide a custom set of images, and the images file in
the machine-api-operator repository may not match the cluster where
development is happening. This new script extracts the image settings
from the running machine-api-operator so they can be used with a
custom build.

add a script to get the image settings for the active MAO

---

OWNERS

This adds Andrea to the approvers, who's got about a dozen commits in this repo and many more reviews.
We don't have anything on the OpenShift side of Metal3 about granting approval rights -- should we come up with some standard? Like more than 10 commits?

Add andfasano as an approver

---

04_setup_ironic.sh
config_example.sh

The paths of files and directories in the COPY instructions inside
the Dockerfile are interpreted as relative to the source of the
context of the build.
Therefore, the custom repository file must be created inside the
base-iamge directory or the build will fail.

Fix COPY instruction for custom repositories file

---

02_configure_host.sh
common.sh

There are two problems - the base port is miscalculated so we
have a discontinuous port range, and we don't consider the extra
workers in the calculation of VBMC_MAX_PORT.
This means BMH registration fails when adding the extra workers
to the cluster.

Fix firewall issues with NUM_EXTRA_WORKERS

---

01_install_requirements.sh
02_configure_host.sh
03_build_installer.sh
04_setup_ironic.sh
05_create_install_config.sh
06_create_cluster.sh
common.sh
metal3-templater.go
network.sh
ocp_install_env.sh
utils.sh
vm_setup_vars.yml

This enables support in dev-scripts for optional provisioning network.
To use, set PROVISIONING_NETWORK_PROFILE to "Disabled".

Optional provisioning network

---

02_configure_host.sh
host_cleanup.sh

Currently we invoke the ansible roles twice, which results
in missing DHCP reservations in the ostestbm network configuration,
because that network already exists when the second run takes place.
That means on scale out any workers defined via NUM_EXTRA_WORKERS will
fail to join the cluster, since they register as "localhost", but the
machine hostname is "localhost.localdomain", which the machine-approver
rejects.

Create all workers with a single ansible run

---

01_install_requirements.sh
02_configure_host.sh
network.sh

OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE needs to be set along with MIRROR_IMAGES=true,
setting it in 04_setup_ironic.sh (where its used), wouldn't work alone as its also needed
in 06_create_cluster.sh

Set OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE when setting MIRROR_IMAGES

---

README.md
openshift_xinetd_example.conf

Added the `xinetd` option to the README and created a config example file to be used as template

Improve README and add xinetd config example

---

utils.sh

Always set the rootDeviceHints as a way to test and demonstrate the
feature.

use ROOT_DISK_NAME to set rootDeviceHints

---

metal3-dev/local-bmo.sh

BMO now checks explicitly for the availability of Ironic services within the reconcile loop before applying any logic, so the `local-bmo.sh` script can be slightly simplified

Remove wait for ironic service

---

.gitignore
01_install_requirements.sh
02_configure_host.sh
03_build_installer.sh
04_setup_ironic.sh
05_create_install_config.sh
README.md
common.sh
config_example.sh
must_gather.sh
ocp_install_env.sh
utils.sh

The user-specific pull secret granted by logging in to
api.ci.openshift.org expires. Rather than forcing users to manually
get a new one, use the login command to get it ourselves and combine
it with the more static parts of the pull secret.
This change deprecates the PULL_SECRET variable in favor of
PERSONAL_PULL_SECRET and CI_TOKEN variables.

fetch a ci token as needed for the pull secret

---

04_setup_ironic.sh

Remove download of headers file when using local ipa-downloader image

---

metal3-dev/local-cbo.sh

This PR adds a new script to test a local Cluster Baremetal Operator checkout. The script copies an existing metal3 deployment into a new one and adds the required annotation to grant the ownership to cbo.

Local cbo script

---

common.sh
utils.sh

the pull secret configured in the ci job has everything it needs to
access the registry so we don't have to do anything extra

assume if we are running in ci we do not need a token

---

clouds.yaml.template
metal3-templater.go
utils.sh

This PR aims to provide a generic way to generate the `clouds.yaml`, in 4.6 we enabled the `http_basic` for ironic an ironic-inspector.
- metal3-templater now can generate specific config for the bootstrap, and for ironic and ironic-inspector according to the auth_type.
- clouds.yaml.template was updated to support the structure for `http_basic`
- utils.sh was update to generate the correct `clouds.yaml` according to the OCP version.

Add support to generate clouds.yaml with http_basic credentials

---

stop-mao.sh

When running the MAO locally, the developer typically needs a JSON
file with the images the MAO should use. It is possible to build a
custom file, but it's often easier to just use the one from the
cluster because we know those images match the rest of the components
in the cluster.

have stop-mao.sh save the image settings

---

utils.sh

I've found it useful to be able to examine the raw YAML for the generated
assets to understand why a cluster doesn't always come up (especially
when the host resources are invalid).

preserve the generated assets for debugging in case the cluster fails

---

ocp_cleanup.sh

The cleanup of known_hosts file in ocp_cleanup.sh requires
EXTERNAL_SUBNET_V{4,6} to be set. If one does not have that set in
config.sh, then the known_hosts cleanup does not happen, since
network.sh isn't included in the cleanup. This adds network.sh to
be sourced in the cleanup script.

Fix known_hosts cleanup

---

utils.sh

The pull secret file in CI contains everything we need *except* the
credentials for the local registry created inside the CI job. Merge
those in to the PULL_SECRET_FILE to support CI jobs that require the
local mirror.
/cc @stbenjam @hardys

fix local registry credential handling in CI

---

README.md

Added a preparation part, aiming to help newcomers.
Detailing the required steps after installing a new OS and before the dev-scripts installation.

Expand dev-scripts documentation

---

02_configure_host.sh
assets/metal3-cbo-deployment.yaml
utils.sh

This PR adds an empty metal3 deployment used to test CBO ownership

Empty metal3 deployment for CBO testing

---

vm_setup_vars.yml

On a default virtual env the master node running metal3
can only have 3G free, give us some extra head room so
that we can play with ironic if we need to.
The underlying qcow files are thinly provisioned so shouldn't
use up much extra space unless its needed.

Increase the default for MASTER_DISK too 30G

---

clouds.yaml.template

When the auth method is basic-auth, you have to use
`--os-cloud=metal3-inspector` instead of `--os-cloud=metal3` when talking to
ironic-inspector rather than ironic-api. For consistency, ensure this
also works when the auth method is noauth.

Always include metal3-inspector 'cloud' in clouds.yaml

---

config_example.sh

This was missed in the original PR which added the variable

Add PROVISIONING_NETWORK_PROFILE to config_example.sh

---

02_configure_host.sh
README.md
utils.sh

The openstack client isn't currently working with auth turned on
and the standalone baremetal command is now the prefered client.
Also link clouds.yaml and _clouds_yaml/clouds.yaml together so
changes in one are reflected in both(users mightn't realise the
file _clouds_yaml/clouds.yaml exists).

Switch to the Standalone ironic client

---

metal3-dev/mao-bmo.sh
metal3-dev/mao-capbm.sh

We need to source common.sh in order to have the kubeconfig path set in
the environment before running oc commands.

metal3-dev: Fix scripts returning to MAO control

---

common.sh
run_ci.sh
utils.sh

Previous changes moved to using a CI_TOKEN for access to the openshift
CI image registry and a file for the other parts of the pull
secret. The PULL_SECRET variable was retained to allow the CI job to
be updated. That has been done, so now we can remove support for
PULL_SECRET.

remove support for PULL_SECRET variable

---

README.md
config_example.sh
utils.sh

There is the need to deploy clusters with customized settings,
that will need to include additional manifests at deploy time.
Add the possibility to include an ASSETS_EXTRA_FOLDER, that will
allow to put additional manifests there and will be copied to
the manifests before install.

Add ASSETS_EXTRA_FOLDER for additional manifests

---

utils.sh

Otherwise the assets are gone by the time we try to copy
when IGNITION_EXTRA is used

Move assets cp before IGNITION_EXTRA

---

01_install_requirements.sh
common.sh
config_example.sh

This enables you to add the following config
```bash
export OPENSHIFT_RELEASE_TYPE=ga
export OPENSHIFT_VERSION=4.5.8
```
and this will create a cluster based off of: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.5.8/release.txt
fixes #1038

Add support for GA release types

---

must_gather.sh

Otherwise MIRROR_IMAGES isn't defined when testing, and we see
a failure to pull the image in the CI logs when test ipv6

Add network.sh to must_gather.sh

---

assets/templates/98_master-chronyd-custom.yaml.optional
assets/templates/98_worker-chronyd-custom.yaml.optional
common.sh
ignition/file_example.ign
utils.sh

The version from 4.6 onwards switched to ignition 3.1.0 so
we should update the version, the schema for the files
changed slightly so we have to remove the filesystem for
3.x but otherwise the existing config should work.

Use appropriate ignition version for chronyd config

---

logging.sh

Because there is a pipe (from awk to tee) in our log output pipeline,
output is now buffered, which is bad for watching in real time. awk
doesn't provide an option to line-buffer the output even though it is
not going to a terminal, so explicitly call fflush() after each line.
Fixes #1121

Line-buffer log output

---

common.sh
config_example.sh

As 4.7 is now open for development, this changes the dev-scripts
default to be 4.7. It also updates an outdated comment about why
we override the release image when building from source.

Set dev-scripts default to 4.7

---

01_install_requirements.sh

There's no 4.7 directory on the mirror so use latest instead

Update oc download location for 4.7

---

01_install_requirements.sh
validation.sh

oc command will be installed on the requirements step.
But deploy validation tries to login with the provided
ci token to validate the token. Allow the requirements to
install oc cli, then proceed with the validation in next step.

Remove deploy validation in requirements step

---

config_example.sh

Dual-stack installs work now, and I assume the comment here was only talking about dev-scripts support for dual-stack, not about whether OCP fully supports the feature.
/cc @stbenjam

Remove warning that dual-stack is not expected to work

---

utils.sh

Using OPENSHIFT_VERSION=4.5.0 results in failure of
the auth template generation because it take wrong path
as the condition only checks for 4.5 only. Trim the version
if it is of format x.y.z before checking.
Fixes: #1131

Auth template generate fails for 4.5.0 version

---

common.sh
config_example.sh

Nightlies for 4.7 now block on e2e-metal-ipi, which means these builds
*should* always install successfully (except for
flakes/misconfiguration) as any accepted nightly will be guaranteed to
have a successful install on baremetal.
One can continue using CI builds by setting `OPENSHIFT_RELEASE_TYPE=ci`.

Make dev-scripts default 'nightly' instead of 'ci'

---

04_setup_ironic.sh

That's what ironic images use in reality. Fall back to Dockerfile.

04_setup_ironic: explicitly handle Dockerfile.ocp

---

metal3-dev/local-bmo.sh

Sync'up with the latest changes on BMO, fixed the script

Fix local-bmo script

---

04_setup_ironic.sh
base-image/Dockerfile

The bash way doesn't always work and could cause issues during build time.
Make TEST_REPO ARG mandatory for base-image.

Remove ARG default for custom repo file in base-image

---

04_setup_ironic.sh

Changes made in 04_setup_ironic.sh file to fix error raised when `podman wait` executes with no unit for time.

Add unit to time in "podman wait" command.

---

metal3-dev/local-bmo.sh

Export GOPATH so that the baremetal-operator code knows where to look
for the tools modules.
Stop requiring the operator-sdk to be installed, since recent versions
of the baremetal-operator don't use it.

Fix local-bmo.sh script

---

04_setup_ironic.sh
config_example.sh

Add the possibility to specify a Pull Request number associated to
an image and build it locally with that change.

Fetch Pull Request to build local image

---

02_configure_host.sh
common.sh
metal3-dev/local-bmo.sh
utils.sh

`whoami` does not always match the group name for
the user. Use `id -gn` to set the group name properly.
Also create GROUP environment variable and replace
USER where appropriate for chown commands.
Fix openshift-metal3/dev-scripts#1154
Signed-off-by: Melvin Hillsman <mrhillsman@redhat.com>

Add GROUP variable for chown where different from USER

---

config_example.sh
ocp_install_env.sh

Adding the option to add certificate bundle that will be added to the nodes' trusted certificate store.

Additional trust bundle

---

04_setup_ironic.sh

The default for CentOS 8 is 1.6.4 which does not support units
in `podman wait -i`. Add a version check to support both.
Follow-up to commit 42af6102b4901a1818e7e71607838b1d9a8c36a9.

Account for podman version < 2.0.0

---

03_build_installer.sh
04_setup_ironic.sh
ocp_install_env.sh
utils.sh

Updates detection of the openshift version because although users can set OPENSHIFT_VERSION, and we can derive it from most user specified release versions, the release images generated in CI don't work because they look like `registry.build02.ci.openshift.org/ci-op-xyz`
Instead we can save the release info locally, and look at the release version directly, which should result in version logic that works both for local testing and in CI.

Update version detection and make dnsVIP conditional

---

ocp_cleanup.sh

For some reason the virsh --remove-all-storage isn't actually removing
the storage, this may be because we moved to a non-default pool?
This can quickly use up space as each leaked directory is about 2.2G
so lets clean it up until we can find a more robust way to handle
this in the installer.

Cleanup /var/lib/libvirt/openshift-images

---

README.md
generate_clouds_yaml.sh
show_bootstrap_log.sh
utils.sh

Currently this is only generated on a successful deployment, but the time you need it most is during/after a failed deploy for debugging.
So try to generate a clouds.yaml (including for the bootstrap VM) even on a failed deploy, and add a script that allows us to generate the file during a deployment if needed.

Improve clouds.yaml generation

---

01_install_requirements.sh
common.sh

The current URL we are using for `oc` was removed, so we need to get the
tools from another location. This also removes the dependency on
calculating the version based on the pullspec, meaning this code works
for CI builds too.
We only use these tools to bootstrap getting the ones from the release
payload, so the actual version isn't super important as we just
overwrite it anyway a little bit later on.

Fetch oc tools from different URL

---

ocp_install_env.sh

This builds on top of @hardys https://github.com/openshift-metal3/dev-scripts/pull/1146 
and depends on https://github.com/openshift/installer/pull/4390

Set bootstrap provisioning ip only when the openshift version is < 4.7

---

ocp_install_env.sh

In anticipation of https://github.com/openshift/cluster-baremetal-operator/pull/86 landing.

Don't set clusterProvisioningIP when network is disabled

---

04_setup_ironic.sh

Since https://github.com/openshift/oc/pull/646
the format of this image name changed, so use the release image tag instead

Retrieve ironic image from release payload

---

02_configure_host.sh
assisted_deployment.sh
host_cleanup.sh
utils.sh

A deployment would lay down the `/etc/NetworkManager/conf.d/dnsmasq.conf` file to enable the NetworkManager dnsmasq service, but a `make clean` would not clean up this configuration and revert the system back to a state without NetworkManager dnsmasq. This simply adds the additional cleanup to the `host_cleanup.sh` script.
Also corrected a function name typo.

add host cleanup commands to revert NetworkManager dnsmasq config

---

must_gather.sh
ocp_install_env.sh
utils.sh

Architecture information was recently added to image pullspecs. We
fixed this for ironic in #1171, but missed it for must-gather.

Fix disconnected must-gather

---

images/Dockerfile.ci

Adding nss_wrapper provides for a local, unprivileged passwd file to be specified,
allowing the container to map the required user information to a random UID without 
having to modify the containers /etc/passwd file directly.
Full explanation on https://access.redhat.com/articles/4859371

Add nss_wrapper to Dockerfile.ci

---

04_setup_ironic.sh
build-base-image.sh

Let's start simplifying a little the 04_setup_ironic.sh moving build
base-image code to its own independent script.

Extract code to build base-image for custom images

---

05_create_install_config.sh

The impact of CVE-2020-25684, CVE-2020-25685, and CVE-2020-25686 can be
reduced by disabling the dnsmasq cache. This change adds cache-size=0 to
our dnsmasq network config.
More information is available at:
https://access.redhat.com/security/vulnerabilities/RHSB-2021-001

Add risk reduction for DNSpooq by setting cache-size=0

---

02_configure_host.sh
config_example.sh

The introduction of ENABLE_LOCAL_REGISTRY will allow then to setup the local registry both explicitly - by setting such variable - or in all the other previous situations where it was required).
This approach will be used to expand the OpenShift CI tests coverage, since it's required to run the e2e suites in disconnected mode (see [1]). To do that, the test workflow will mirror the required images to the local dev-scripts private registry.
[1] https://github.com/openshift/origin/pull/24887

Add ENABLE_LOCAL_REGISTRY config var to setup the local registry

---

metal3-dev/local-bmo.sh

Env variables weren't exported correctly in the `local-bmo.sh` script, thus provoking an inspection failure due a parsing error.

Fix exporting provisioning ip for ipv4/ipv6 cases in local-bmo.sh

---

06_create_cluster.sh

By default, on baremetal platforms, the image registry operator is
configured without persistent storage.  Here, we configure it with
"emptyDir".  This is needed for e2e test.
[Ref](https://docs.openshift.com/container-platform/4.3/registry/configuring_registry_storage/configuring-registry-storage-baremetal.html#installation-registry-storage-non-production_configuring-registry-storage-baremetal)

Configure storage for image registry

---

metal3-dev/local-bmo.sh

Adds the option to override the default path via the
BAREMETAL_OPERATOR_PATH variable.
This is useful when you want to modify the checkout consumed
via BAREMETAL_OPERATOR_LOCAL_IMAGE, which ends up in $HOME
not the regular GOPATH location.

local-bmo.sh make BMO path configurable

---

02_configure_host.sh

In recent (2.2.1 tested) podman versions, this file ends up
unreadable as $USER e.g in utils.sh (previously it ended up as 644, now it's 600)
```
$ sudo podman login --authfile /tmp/test.json ...
Login Succeeded!
-rw-------. 1 root root 107 Feb 17 12:00 /tmp/test.json
```
In future we should probably test removing all the `sudo podman`
calls to use rootless mode, but since that has historically been
buggy, this is a lower risk interim fix.

chown private mirror creds file

---

02_configure_host.sh
ocp_install_env.sh
utils.sh

For IPv4 environments, when `ENABLE_LOCAL_REGISTRY` is enabled, we are getting `x509: certificate signed by unknown authority` in CI workflows. This is due to the fact that `additionalTrustBundle` should be added as well as `imageContentSources` into the install-config, even when `MIRROR_IMAGES` is disabled.
This PR adds enabling this even when MIRROR_IMAGES is disabled environments.

Add ENABLE_LOCAL_REGISTRY check in image mirror config

---

05_create_install_config.sh
README.md
create_remote_nodes.sh
ocp_install_env.sh

This PR adds support to create a 'remote cluster' VM nodes and their own L2 network. The network is a libvirt NAT network.
To create a new remote cluster VM(s) and their corresponding network, just invoke the: `create_remote_nodes.sh` with a namespace as an argument.
e.g 
```
./create_remote_nodes.sh mynamespace
```

Add support to lauch remote site VMs in their own L2 network

---

rhcos.sh

Currently with the set -x we're dumping the entire rhcos.json
to the logs 5 times(!), due to the echo | jq ...
Instead we can just save the file in the case where we're running
from source, and reference the file directly in the call to jq.

Quieten rhcos.sh logging

---

02_configure_host.sh

Happened to me on a scalelab machine.
Figured out we can handle it in this way.
/hold

using slash delimiters in sysctl for handling vlan NICs

---

external_loadbalancer.sh

This allows us to test external Api/Ingress traffic running through an haproxy-based external LB.
To switch external traffic from self-hosted LB to the external LB it needs to update api and .apps records to point at 192.168.111.1 (or the
equivalent ipv6 address) instead of the VIPs.
This can be done by editing the ostestbm.addnhosts file in /var/libvirt/dnsmasq and then sighupping
the associated dnsmasq process.
Co-authored-by: Ben Nemec

Add external LB script

---

04_setup_ironic.sh
config_example.sh

Long due change to provide a way to automatically install extra
packages in the local custom built images.
This can be useful to test different versions of packages or just
test new dependencies or tools.
This depends on https://github.com/metal3-io/ironic-inspector-image/pull/72 and https://github.com/metal3-io/ironic-image/pull/227

Add a way to install extra packages in the images

---

04_setup_ironic.sh

The extra pkg change broke image builds that don't use it because
it was unconditionally calling realpath on the variable. If it wasn't
set then this resulted in an invalid command. To fix this we just
need to move the realpath call inside the -n check so we only do it
if the variable is populated.

Fix error building images without extra pkgs

---

metal3-dev/local-bmo.sh
utils.sh

Fixes two issues when testing without a provisioning network - the clouds.yaml generation is broken, and also the local-bmo.sh development script has a similar issue, we need to adjust the IP in each case.

Fix issues with PROVISIONING_NETWORK_PROFILE=Disabled

---

README.md

We haven't required specific hostnames for several releases. I doubt
this prereq is relevant to anyone starting to use dev-scripts at this
point.

Drop hostname requirements from README

---

06_create_cluster.sh
utils.sh

CI runs dev-script with `ENABLE_LOCAL_REGISTRY`(local image registry) to support disconnected environments and this causes unknown certificate error for 60 tests which tries to access tools image stream.
This PR defines local certificate as trusted CA for cluster's image configuration in connected environments (with also configuring cluster samples operator).
Reference: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html-single/images/index#installation-restricted-network-samples_samples-operator-alt-registry

Configure cluster samples operator and tools image registry

---

metal3-dev/local-bmo.sh

This PR adds a missing exported env var required to run locally BMO (this reflects also the current CBO [approach](https://github.com/openshift/cluster-baremetal-operator/blob/3e51af8955d3b353202e11d2404ffcf82dcf55e9/provisioning/baremetal_pod.go#L377-L378))

Fix TLS support for local-bmo.sh

---

clouds.yaml.template
utils.sh

In theory it should be possible to load the public key from secrets, but
I don't have an environment to figure it out yet.

Disable TLS verification in clouds.yaml

---

06_create_cluster.sh
config_example.sh

Some CI tests try to test machine scale in and out like;
`Managed cluster should grow and decrease when scaling different machineSets simultaneously`.
If the CI suite set NUM_EXTRA_WORKERS field to test this, we automatically apply it.

Apply NUM_EXTRA_WORKERS if explicitly set in CI

---

utils.sh

The credentials we generate for Ironic and related services end up in
the log. There's not much use of these, since they're ephemeral, and
you'd have to otherwise have access to the host's network to make use of
them, but we should hide them anyway.

Don't show generated ironic credentials in the logs

---

metal3-dev/local-capbm.sh

Allows to override the default path similar to #1178, and resolves a port conflct when running both scripts together

local-capbm.sh fixes

---

provisioning-network.sh

This PR enables the day 2 management of the provisioning network. The script manipulates the provisioning-configuration CR and sets the values in the spec based on whether the provisioning network is managed, unmanaged or disabled.
Usage:
./provisioning-network.sh [Managed|Unmanaged|Disabled]

Add support for Day 2 management of the provisioning network

---

ocp_cleanup.sh
podman_cleanup.sh

When testing the virtualmedia flow, I noticed that we're
leaking boot images, and also that on realclean we don't
clean any dangling podman volumes.

Add some extra image/volume cleanup

---

metal3-dev/local-cbo.sh

These files are now required when running the local CBO.

Make CBO TLS files available on the host

---

README.md

I noticed config_example comments and README had a different hostname to get the CI_TOKEN, and validations were checking against the one in config_example.
Signed-off-by: Rohan CJ <rohantmp@gmail.com>

[tiny] update README.md with correct CI registry hostname

---

01_install_requirements.sh
common.sh

So we pick up https://github.com/metal3-io/metal3-dev-env/pull/619
This is needed for testing live-iso install ref #1193 since that needs
the sushy_ignore_boot_device option

Bump metal3-dev-env version

---

02_configure_host.sh
host_cleanup.sh
remote_nodes.sh
vm_setup_vars.yml

Since https://github.com/metal3-io/metal3-dev-env/pull/129
the extradisks variable actually doesn't work, so instead we
need to set the value in vm_setup_vars.yml directly

Fix VM_EXTRADISKS

---

03_build_installer.sh
rhcos.sh

This allows to use openshift-install coreos print-stream-json if available to gather openstack and qemu images from installer binary

Gather rhcos assets using print-stream-json if available

---

assisted_deployment.sh

This got dropped in a recent change to the assisted scripts and it
causes make clean to always fail on non-assisted deployments.

Reinstate check for NODES_PLATFORM in assisted cleanup

---

assisted_deployment.sh

With there being multiple releases of the assisted-service-operator,
starting at v0.0.1 is only going to cause headaches. This removes it
entirely and leaves it up to OLM which version to install first...which
if we set up our manifests correctly should always be the latest.

assisted-installer: do not set starting CSV

---

03_build_installer.sh

There's a missing `>`, so currently `2&1` is treated as an argument to
openshift-install resulting in this error in the CI logs:
```
INFO[2021-04-28T12:40:02Z] time="2021-04-28T11:03:00Z" level=fatal msg="Error executing openshift-install: accepts 0 arg(s), received 1"
```
See: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/516/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-dualstack/1387357685652918272

rhcos: don't output fatal error when printing json

---

common.sh

When using the same directories as WORKING_DIR and SCRIPTDIR some input
and output files may be the same what causes unexpected behaviour and
crashes during creation of the environment.
This PR adds a simple check to make sure WORKING_DIR and SCRIPTDIR are
different.

Ensure working and script directories are different

---

06_create_cluster.sh

This PR removes configuring cluster samples operator's sampleRegistry to local image registry.
This configuration does not work currently and will be handled in release.

Remove samples operator configuration

---

README.md
assets/templates/cluster-network-00-gateway-mode.yaml.optional
utils.sh

Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

Allow local gateway mode to be configured with OVN

---

network.sh

Dualstack doesn't need to be installed disconnected. This expands the tests that will run on dualstack since we'll run the connected ones too, and it also makes the test a little bit shorter.

Install dualstack connected

---

common.sh

RHEL 8.2 already having podman >= 1.4.4, so this workaround shouldn't be needed anymore.
/cc @stbenjam 
/hold

remove workaround of unset XDG_RUNTIME_DIR

---

04_setup_ironic.sh

This is needed because if the checksum is provided to the BMH like:
```
image:
checksum: http://192.168.111.1/images/rhcos-48.84.202104271417-0-openstack.x86_64.qcow2.gz.sha256sum
checksumType: sha256
format: qcow2
url: http://192.168.111.1/images/rhcos-48.84.202104271417-0-openstack.x86_64.qcow2.gz
```
We see an error like:
```
Error downloading image: Download of image bdab49e61715b72c5e937c54a232677cbf821ebcd71aeb3ba58028683cccad07
failed: Checksum file does not contain name rhcos-48.84.202104271417-0-openstack.x86_64.qcow2.gz
```
It seems that Ironic is checking for the filename/basename and fails to find the checksum if a fully qualified path is used.
This isn't an issue in regular IPI deployments because we use the cluster cached copy of RHCOS which calculates the checksum …

when creating the image sha256sum remove the path to the image file

---

assisted_deployment.sh

This PR makes the `assisted_deployment.sh` script save all the manifests
into `saved-assets/` so that operators have an ability to inspect them
after (un)successful installation.
The previous behavior was to generate the manifest on fly and pass it
directly to `oc apply`. From now on the manifest will be saved on a
local filesystem and only afterwards applied from the file that has been
created.
This PR creates as well a patched copy of `extra_host_manifests.yaml`
given that the namespace of the created resource must match the
namespace of all the other resources we are creating.

NO-ISSUE Store artifacts in saved-assets/assisted-installer-manifests

---

metal3-dev/local-bmo.sh

On my environment it takes nearly two minutes to start the whole pod.

local-bmo: increase pod wait timeout

---

utils.sh

On 4.8 and later we don't need to override the default feature gates, and so we shouldn't.
(Currently MCO is assuming that we will, and so it hacks the bootstrap-time kubelet config to include the feature gate, which will then cause problems if you _didn't_ manually set the feature gate, so effectively 4.8 still requires people to manually override the feature gate.)
MCO fix: https://github.com/openshift/machine-config-operator/pull/2580
Whichever one merges first will break dual-stack CI. There is no good way to avoid this.

Bug 1966602: Only do the feature-gate override for dual-stack on 4.6 and 4.7

---

assisted_deployment.sh

This PR makes `assisted_deployment.sh` script generate more useful BMH
definition, i.e. by adding additional labels and annotations which
otherwise would need to be added manually by the operator.
Please note that while the namespace will be configured according to the
namespace where assisted-service is installed (defined in
`config_*.sh`), the `infraenvs.agent-install.openshift.io` labels gets a
sample value of `myinfraenv`. This is because we do not provide an
automatically generated InfraEnv definition, but at the same time we
want the BMH to contain all the fields an operator may need to add
manualy at the later stage.
Please, select one or more if needed:
assisted_deployment.sh generates now the following file
```
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
name: …
```

Make assisted_deployment.sh generate useful BMH definition

---

common.sh
config_example.sh
utils.sh

I was trying to find a better place for this as I think, for dev-script, it may be beneficial to always set this. I put it in the assisted_deployment script for now as that's the workflow I'm after right now. 
I'd be happy to move this to a more generic place if people think it is worth it.
```
[dev@edge-10 dev-scripts]$ cat config_dev.sh | grep BMO
export BMO_WATCH_ALL_NAMESPACES=true
[dev@edge-10 dev-scripts]$ cat ocp/ostest/saved-assets/openshift/99_baremetal-provisioning-config.yaml | grep watchAll
watchAllNamespaces: true
[dev@edge-10 dev-scripts]$ oc get provisioning provisioning-configuration -o yaml | grep watchAll
watchAllNamespaces: true
[dev@edge-10 dev-scripts]$
```
Signed-off-by: Flavio Percoco <flavio@redhat.com>

Set watchAllNamespaces when deploying assisted service

---

common.sh

It's been moved to amd64.ocp.releases.ci.openshift.org, and the redirect
from openshift-releases seems to be gone.

Move release dashboard to new URL

---

common.sh

If we have no release image and retrieving the latest ci image fails,
we can't proceed. If we try to anyway then confusing errors happen.
It's better if we bail out as soon as we know something is wrong so
we can log a message that explains what happened.

Stop if we fail to retrieve the ci image

---

assisted_deployment.sh

Currently, the assisted deployment only creates the Hive operator.
The operand also needs to be created so that it can reconcile
CRs like cluster deployments.
Signed-off-by: Richard Su <rwsu@redhat.com>

Create Hive operand in assisted deployment

---

README.md

The pull secret URL is referenced in the Pre-requisites
section, but not in Configuration, making it easy to
miss when you read this section directly.

README Doc update, adds a pull secret hyperlink to Configuration

---

utils.sh

This PR changes version extraction method for IPv6DualStack feature apply. In CI, `OPENSHIFT_VERSION` is always unset and for 4.6 and 4.7 versions, this condition is always false. Thereby, dualstack jobs are failing in these versions.

Change IPv6DualStack feature version check

---

must_gather.sh

To prevent output from stomping on files from a previous
mustgather give each run its own directory.

Append timestamp to must-gather directory

---

Makefile

`make configure` is not an idempotent action and in the current form
makes it impossible to use `make assisted` without breaking a
deployment, i.e.
```
make
make assisted
```
leaves the environment in a broken state. This PR changes the `assisted`
target so it only executes the installation script for the assisted
service.
Please note it implicitly assumes that the user previously executed
`make all`, however this is not a change in the behaviour as currently
this is also required.

Fix make target for Assisted Installer

---

01_install_requirements.sh
utils.sh

We're having those kind of errors in all kinds of jobs:
https://search.ci.openshift.org/?search=OpenSSL+SSL_connect%3A+SSL_ERROR_SYSCALL+in+connection+to+mirror.openshift.com%3A443&maxAge=48h&context=1&type=all&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
I think it will help us deal with those kind of flakes on other places as well, but let's start with the oc installation.

retry downloading of oc client from mirror.openshift.com

---

Makefile
assisted_deployment.sh

This PR adds additional ways to use `assisted_deployment.sh` so that it
can not only perform a complete installation of the Assisted Service but
can also be used to install only its prerequisites, i.e. LSO and Hive.
This is a useful workflow for development where operator-sdk is used to
install the operator itself, but we don't want to handle the base
requirements manually.

Improve script to install assisted-service

---

ocp_install_env.sh
utils.sh

When there is no `MIRROR_IMAGES` or `ENABLE_LOCAL_REGISTRY` environment variables, image_mirror_config function gets an `-z: command not found` error and https://github.com/openshift-metal3/dev-scripts/blob/d3249ae3e97d7a9cb473b17b3e0fab43f27ab6ff/utils.sh#L340 is never executed.
This PR fixes by adding extra brackets to test condition.

Fix image_mirror_config test condition bug

---

02_configure_host.sh
ocp_cleanup.sh
utils.sh

Currently, IPv6 clusters do not synchronize their time with NTP because
there's no external internet access. This is causing a newly enabled
test to fail (`[sig-apps] [Feature:TTLAfterFinished] job should be deleted once it finishes after TTL seconds`).

Configure an NTP server for dev-scripts cluster

---

04_setup_ironic.sh
config_example.sh

Introduce a variable to explicitly trigger the build of a custom base
image for the ironic images.
Do not make that depends from the CUSTOM_REPO_FILE variable anymore.
The CUSTOM_REPO_FILE is not mandatory anymore to build a custom base
image.
Also a custom base image is not required anymore to build local images as
the openshift base images are pullable from the openshift registry.

Update base-image logic

---

utils.sh

This was added in #1274 but doing this drops all the libvirt chains,
which causes subsequent ansible libvirt setup tasks to fail.
(I'm not entirely sure why this didn't fail CI)

Don't reload firewalld during chronyd config

---

README.md
common.sh
config_example.sh
utils.sh
validation.sh

When testing cluster-bot builds, the server (and CI_TOKEN) is
different, so it's necessary to modify the server login URL from
that used for regular CI builds.

Enable alternative CI_SERVER login

---

02_configure_host.sh

Trying to bring up a cluster on a fresh CentOS 8 host, it errors out trying to run `sudo firewall-cmd --permanent --zone=libvirt --add-service=ntp` because firewalld isn't running. The script ensures firewalld is running (#970) but that happens _after_ the new chronyd config stuff that tries to modify the firewall (#1274).
I don't know why this isn't breaking anyone else? Reusing existing hosts rather than creating fresh ones? Additional setup scripts that enable firewalld?

Ensure firewalld is running early enough

---

metal3-templater.go

We have switched to TLS long ago, the generated clouds.yaml still has HTTP.

Use https in the generated clouds.yaml for the cluster

---

01_install_requirements.sh
common.sh
config_example.sh
utils.sh
vm_setup_vars.yml

This was added to metal3-dev-env in [0]. Expose the setting for
dev-scripts too.
With the current version of libvirt available, we are not able to run
virsh net-dhcp-leases when infinite leases are enabled. I've added
logic to skip that step when LEASE_EXPIRY=0. It just means we
can't retrieve clouds.yaml from the bootstrap.
0: https://github.com/metal3-io/metal3-dev-env/pull/599

Support lease expiry option

---

README.md

This PR fixes a path to the `.openshift-install-state.json` in the README.md and adds some more information, where to find the config parameters fir xinetd.

Fix path in README.md to .openshift-install-state.json

---

04_setup_ironic.sh
common.sh
ocp_install_env.sh
rhcos.sh

This PR introduces a new variable USE_RHCOS_LIVE_IMAGES which enables caching of 4 RHCOS live images: kernel, rootfs, initramfs and iso.

RHCOS Live Image caching support

---

utils.sh

CI and nightly releases are not part of the official Red Hat
Cincinnati graphs.  This commit removes the channel property [1],
which will result in the NoChannel condition [2], but will keep the
CVO from attempting to find its current version in the official
Cincinnati [3].  That in turn should keep the CVO from throwing a new,
critical alert [4], which will keep it from running afoul of recent
update e2e logic that forbids critical alerts [5].
See this related PR [6] which does this for other platforms IPI
install step.
[1]: https://github.com/openshift/installer/blob/4eca2efd615f8abd65f576721e2410b19f0d40d0/data/data/manifests/bootkube/cvo-overrides.yaml.template#L8
[2]: https://github.com/openshift/cluster-version-operator/blob/fa452c2d270f1f989f3868ef97ae8cf825713583/docs/user/status.m …

Remove ClusterVersion channel

---

utils.sh

This PR adds condition to prevent spec.channel clear when
`OPENSHIFT_RELEASE_TYPE ` is `ga`. spec.channel is cleared for
only release types `ci` and `nightly`.

Clear spec.channel other than OPENSHIFT_RELEASE_TYPE ga

---

01_install_requirements.sh
go.mod
go.sum

baremetal-operator depends on 1.16, and there is no reason to not use
the latest

Bump go_version to 1.17.1

---

common.sh

This currently ends up as 4.1 for 4.10 release image strings...

Fix OPENSHIFT_VERSION regex

---

06_create_cluster.sh

OperatorHub tries to reach internet to pull images for redhat-operators,
certified-operators, community-operators. However, in disconnected environment
these pods are in degraded state. CI jobs fire warnings due to these pull image
errors.
This PR disables OperatorSource in disconnected.

Disable OperatorSource objects for disconnected

---

06_create_cluster.sh
ocp_install_env.sh

This patch stores the yaml generated for the extra workers in a secret, so that [e2e baremetal tests](https://github.com/openshift/origin/tree/master/test/extended/baremetal) could use it to dynamically add/delete extra workers when required

Store extraworkers info in a secret

---

metallb/run_e2e.sh

1. We need to source the metallb common.sh file to get the
network settings of the cluster to set the provisioning
host IP variable passed to the E2E tests.
2. Setting the dual stack name to 'v4v6' as this is the
setup in the dev-scripts, and not 'dual'.
3. Set the provisioning host IP according to the cluster IP family.
4. Skip dual stack tests according to the cluster IP family.
5. Set dummy IP for the unsued host IP, the host IPV4 or IPV6
according to the cluster IP family.

Fix metallb script that's running E2E tests

---

metal3-dev/local-bmo.sh

CBO creates BMO resources as well as ValidatingWebhookConfiguration
and service. However, on local runs, BMO ValidatingWebhook is disabled
by default. To allow requests go to BMO API, this PR deletes
ValidatingWebhookConfiguration.

Delete BMO ValidatingWebhookConfiguration on local runs

---

01_install_requirements.sh

A metal3-dev-env change ([Enable authentication in sushy-tools](https://github.com/metal3-io/metal3-dev-env/pull/798)) added a requirement for python3-passlib and python3-bcrypt.
Apparently these aren't available in RHEL and some folks on slack have been workinga around this by using EPEL. They are also available in OSP 16 repos.

Enable EPEL repo on RHEL8

---

01_install_requirements.sh
vm_setup_vars.yml

This allows additional networks to be defined e.g
```
export EXTRA_NETWORK_NAMES="nmstate1 nmstate2"
export NMSTATE1_NETWORK_SUBNET_V4='192.168.221.0/24'
export NMSTATE1_NETWORK_SUBNET_V6='fd2e:6f44:5dd8:ca56::/120'
export NMSTATE2_NETWORK_SUBNET_V4='192.168.222.0/24'
export NMSTATE2_NETWORK_SUBNET_V6='fd2e:6f44:5dd8:cc56::/120'
```
Requires ansible role changes added via
https://github.com/metal3-io/metal3-dev-env/pull/852

Add support for additional networks

---

metallb/run_e2e.sh

Need to skip L2 metrics test because the pod that's running the tests is not in the same subnet of the cluster nodes, so the arp request that's done in the test won't work.

MetalLB E2E tests: skip L2 metrics test

---

ocp_install_env.sh

This is only needed in rhcos.sh for old versions which lack the
openshift-install coreos-print-stream-json option, and the
file moved in https://github.com/openshift/installer/pull/5252
so we should only copy if the "old" location is detected

Conditionally copy rhcos.json

---

metallb/run_e2e.sh

This is done to fix the following error:
```
skip="L2' 'metrics"\|IPV6\|DUALSTACK'
No idea what 'metrics"\\|IPV6\\|DUALSTACK' is!
make: Leaving directory '/root/dev-scripts/metallb'
make: *** [Makefile:19: run_e2e] Error 1
```
As there are spaces in the skip string variable we need to put double quotes on it.

MetalLB E2E tests: Fix skip flag

---

metallb/run_e2e.sh

Setting the logs path to `/logs/artifacts/` as this is the openshift-ci artifacts location so the logs will be stored on every CI run.

MetalLB E2E tests: Add logs path

---

metallb/run_e2e.sh

Adding the flag to support the last change in the operator, as we are deploying MetalLB here through the operator.
In the new operator configuration the operator takes control of the ConfigMap, meaning if an external thing (like the e2e tests) changes the ConfigMap the Operator will reconcile it to what it thinks it should be - making the e2e tests useless.

MetalLB E2E tests: Add use-operator flag

---

metallb/run_e2e.sh

Apparently -e flag is getting logs only when running the E2E tests on kind clusters.
We get all the logs we need in must-gather.

MetalLB E2E: Remove export logs flag

---

metallb/run_e2e.sh

Doing this so we can run MetalLB E2E tests from a specific branch to match the deployment version.

MetalLB E2E: Allow setting MetalLB repo branch

---

metallb/run_e2e.sh

In order to make bfd work, we need to open the ports in the same way we did for bgp.

MetalLB: open BFD ports

---

metallb/deploy_operator.sh

Instead of building the operator image we can use the latest image in the CI registry.
Doing this so when running the CI in metallb-operator repo the deployment will be done with the committed changes instead of latest main.

MetalLB: Use metallb-operator image from CI registry

---

04_setup_ironic.sh
common.sh
ocp_install_env.sh
rhcos.sh

In 4.10 we don't need to pass a clusterOSImage in the install config, so don't.

Stop passing clusterOSImage

---

common.sh
ocp_install_env.sh

The $OPENSHIFT_VERSION variable isn't defined in CI.

Use openshift_version function with is_lower_version

---

04_setup_ironic.sh
config_example.sh

In disconnected deployments (like ipv6) we need to mirror any OLM
operators that we want to install because the OLM images aren't
otherwise available. This patch adds a MIRROR_OLM configuration
variable that will create a pruned index containing only the
relevant operators in the local registry.
The mirroring process generates a couple of manifests needed to use
the mirrored index, and these files are added to the deployment
manifests directory so it will be usable immediately.

Add support for mirroring OLM operators

---

01_install_requirements.sh

Reverts openshift-metal3/dev-scripts#1343
Since moving to Rocky Linux, this code changes package repositories back to using vault mirror even in Rocky Linux.
Regular repositories are good enough for us, so this change no longer needed.
/cc @derekhiggins 
/hold
(waiting to manually investigate CI logs)

Revert "Get Centos packages from Vault"

---

01_install_requirements.sh

The commit [1] broke compatibility with filters in netcommon, we need to
cap ansible.netcommon to version lower than 2.6.0 to avoid issue when
importing filters for templates until the filter redirection is fixed.
[1] https://github.com/ansible-collections/ansible.netcommon/commit/db4920ebf6bae6476ff8829e2cf475f19f83a990

Temporarily capping version of ansible.netcommon

---

network.sh

Especially when testing a disconnected environment (ie ipv6) where the local registry is deployed, it is required to add it to the no_proxy list if a proxy based installation is performed

Add registry to the no_proxy when is configured

---

utils.sh

This PR fixes function responsible for synchronizing repositories so
that both "main" and "master" branches are supported. Current behaviour
assumes that there always exists a "master" branch what is no longer the
case given repositories follow a patern of using "main" instead.

Add support for "main" and "master" branches

---

06_create_cluster.sh
config_example.sh

This new ENABLE_VIRTUAL_MEDIA_VIA_EXTERNAL_NETWORK will be used to pass
virtualMediaViaExternalNetwork as true in provisioning configs.
virtualMediaViaExternalNetwork, when it is set to true, allows for worker
to boot via Virtual Media and contact metal3 over the External Network.
With this PR, we will be able to test this functionality in our CI
jobs to assure that it is working as expected or not. Moreover,
users also can use that environment variable if they want to boot workers
via Virtual Media and contact metal3 over the External Network.

Add ENABLE_VIRTUAL_MEDIA_VIA_EXTERNAL_NETWORK environment variable

---

docs/assisted-deployment.md

It no longer has to be a manual step.
/cc @hardys @flaper87

Document extra disks for assisted

---

utils.sh

Because noone could be stopped from naming a default branch "goofy"

Determine default git branch when syncing repo

---

agent/03_agent_deployment.sh

AgentClusterInstall.Spec.provisionRequirements.workerAgents should
reflect the value set in NUM_WORKERS.
This allows high availability clusters to be installed through
the agent based installer flow.

Include NUM_WORKERS in agent based installs

---

06_create_cluster.sh

The correct flag is --kubeconfig
Also add single line instruction to message to set the KUBECONFIG
environment variable.

Fix typo in the oc command after cluster is ready

---

03_build_installer.sh
ocp_install_env.sh
utils.sh

This patch modifies the openshift installer functions so that it will be possible to reuse the `03_build_installer.sh` also for non-baremetal flows (it will be used by the agent flow in a subsequent patch).
In addition, it allows the `sync_repo_and_patch` to use a different branch (also this feature will be required by the agent flow, as currently is being developed in its own installer branch)

AGENT-164: Customize openshift installer checkout, build and extraction

---

Makefile
agent/03_agent_build_installer.sh
agent/04_agent_configure.sh
agent/05_agent_create_cluster.sh
agent/README.md
agent/cleanup.sh
agent/common.sh
config_example.sh

This patch requires https://github.com/openshift-metal3/dev-scripts/pull/1392
It changes the agent flow in order to use the openshift installer, by reusing the existing build installer step (properly customized where required).
A new `agent_build_installer` has been added to rebuild the installer from source or extract it from the release payload (more docs on this point will follow), and it could be used also in standalone way if required.
The previous `agent_deployment` step was split in two:
* `agent_configure` will now configure the environment and networking, and also create the manifests (this step could be further split in future)
* `agent_create_cluster` generates the image and starts the cluster installation.
The current working dir is set under $OCP_DIR, by default the …

AGENT-164: Use openshift installer for the agent flow

---

agent/05_agent_create_cluster.sh

We can't cd into the working directory *and* pass a --dir, because
assets end up getting written to ocp/ostest/ocp/ostest.
Eventually we will prefer passing --dir, but for now there is legacy
fleeting code that looks for files relevant to the current working
directory.

Use correct output directory for all assets

---

agent/05_agent_create_cluster.sh

This patch adds a rudimentary waiting condition to detect when the cluster is available and ready to be used.
This will be used to implement the first CI job.

AGENT-179: wait for cluster ready

---

images/Dockerfile.ci

The provisioning of equinix machines is broken because it fails with:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (packet_device) module: tags Supported parameters include: always_pxe, auth_token, count,
count_offset, device_ids, facility, features, hostnames, ipxe_script_url, locked, operating_system, plan, project_id, state, user_data, wait_for_public_IPv, wait_timeout"}
```
This issue seems to be related to the latest version (`5.0.0`) of the `community.general` ansible collection which drops the support for ansible 2.9 that we install (https://github.com/ansible-collections/community.general/blob/stable-5/CHANGELOG.rst#major-changes)
This change pins the `community.general` ansible collection to the previous version `4.8.1` which seems to …

NO-ISSUE: Pin community.general collection to version 4.8.1

---

agent/04_agent_configure.sh

Now that the agent installer supports installing the release payload
from the ClusterImageSet, pass the value calculated from the dev-scripts
config.

AGENT-165: stop hard-coding release image

---

agent/04_agent_configure.sh
agent/05_agent_create_cluster.sh

Rename `manifests` to `cluster-manifests`
Expect agent.iso in work directory, not in `outputs` subdirectory.
Use symlinks to prevent CI breakage until this is changed in the installer.

Agent: change input/output directories

---

agent/docs/config-presets-and-options.md

Adding documentation defining the values for different types of preset configurations.
AGENT-51

AGENT-51: Add documentation for preset configurations

---

agent/04_agent_configure.sh

Since openshift/installer#5975:
ZTP manifests are now read from cluster-manifests.
The agent.iso output is now in the work directory directly.

Agent: remove workarounds for old file locations

---

04_setup_ironic.sh
build-base-image.sh
utils.sh

In case the host where dev-scripts is running has only localhost as
resolver, the dns resolution during build fails as it's removed from
/etc/resolv.conf since it's not reachable from the container.
If we need to reach external urls during image building, the entire
build fails, as the urls can't be resolved.
As a workaround use the --network host option only during build.
For more info see https://github.com/containers/podman/issues/13599

Use host network when building images

---

assisted_deployment.sh

The ocpmetal image is no longer being maintained or updated.
All assisted images should now be pulled from edge-infrastructure.
cc @dtantsur

Update assisted operator index image

---

agent/04_agent_configure.sh

Configure the `ClusterImageSet` manifest using the version fetched from the downloaded release payload

Agent: use OpenShift version extracted from the release payload

---

agent/03_agent_build_installer.sh

Agent installer extracts the version information directly from the binary, and it's used to configure the assisted-service via the RELEASE_IMAGES env var. When building from src anyhow this info is missing, so this patches the binary similary to what the `oc adm release extract` command does.
Since assisted-service will check the content of the RELEASE_IMAGES with the `.metadata.version` field of the extracted release info, we're going to patch it otherwise the installation process won't start.

agent: patch openshift install version if missing

---

utils.sh

Make eats all exit codes:
http://www.gnu.org/software/make/manual/html_node/Running.html. So when
make fails, regardless of the error code the installer or dev-scripts
returns, make exits 2. Make's behavior seems to be non-configurable.
By recording it in the log, we can look for it later.

Save installer exit status in logs

---

utils.sh

Force the command to get the bootstrap ip to succeed.
If running a DHCP server outside of dev-scripts
(with MANAGE_BR_BRIDGE=n) then the net-dhcp-leases command
will return nothing, because we have "set -o pipefail" this
causes the whole script to stall.

Ensure bootstrap_ip doesn't fail

---

network.sh

Previously, if you ran two builds in a row without cleaning in between,
this would append a second copy of the dnsmasq config to the end of the
file. The presence of duplicate line in the config caused an error that
prevented NetworkManager from doing DNS lookups. This meant that even
cleaning was broken, so there was no obvious way to recover.
Overwrite the file instead of appending to it so that this doesn't
happen.

Don't append to existing dnsmasq config

---

04_setup_ironic.sh
agent/03_agent_build_installer.sh
agent/04_agent_configure.sh
agent/common.sh
utils.sh

First step in using disconnected installs for agent. The new files required for disconnected installs are created (registries.conf and ca-bundle.crt) and the release image is mirrored to the local image server.
A follow on will add images for the assisted-* components to the local image server.
To test set:
export MIRROR_IMAGES=true
export INSTALLER_REPO_PR=5992
export KNI_INSTALL_FROM_GIT=true

AGENT-216: Add agent support for disconnected installs

---

rhcos.sh

For OKD IPI we use FCOS as a base OS. However its artifacts are .xz packed.
This ensures both RHCOS .gz and FCOS .xz are supported

rhcos.sh: support FCOS artifacts

---

agent/05_agent_create_cluster.sh

This simulates a disconnect from the masters when using the agent with mirroring. It sets a bogus /etc/hosts entry so that the local mirror must be used.  This is currently needed since we must have a valid connection to create the mirror and create the iso so we can't break the connection until after that's done.

AGENT-287: For agent mirror testing force disconnect from masters

---

common.sh
config_example.sh
ocp_install_env.sh

This configures a static IP for the bootstrap external NIC
Requires https://github.com/openshift/installer/pull/5787

Add ENABLE_BOOTSTRAP_STATIC_IP option

---

01_install_requirements.sh

This is to avoid the system not finding the yq binary when using
recent pip versions.

Install the yq util system-wise

---

01_install_requirements.sh
02_configure_host.sh
README.md
common.sh
host_cleanup.sh
validation.sh

These two distributions are essentially what CentOS was pre-Stream,
so they should generally be compatible as well. They are documented
as "best effort" support though since I don't think we'll be running
them in CI.

Add Alma and Rocky Linux as supported host OSes

---

config_example.sh
network.sh
utils.sh
vm_setup_vars.yml

This provides a way to specify a custom networkConfig for each node
in a deployment. The user sets NETWORK_CONFIG_FOLDER to a path that
contains YAML files named for each node. The contents of these files
are included in the install-config definition for the appropriate
node.

Add interface for custom networkConfig

---

02_configure_host.sh
host_cleanup.sh

In order to ensure that the IPv6 bridge interface comes up add a dummy interface. This is needed for versions of NetworkManager after 1.32.

Bug 2087096: Add a dummy interface to IPv6 bridge

---

agent/05_agent_create_cluster.sh

Since we don't yet have a way of saving the kubeadmin password created
by the assisted-service, generate a new password and update the hash in
the cluster.

Agent: Create kubeadmin password

---

agent/04_agent_configure.sh
agent/05_agent_create_cluster.sh

For agent IPv6 testing set up the nmstate config to use IPv6 addressing.
I've tested this with both IPv6 and IPv4 using 4.12 and https://github.com/openshift/installer/pull/6249

AGENT-239: Use IPv6 addresses in nmstate config

---

02_configure_host.sh

Not sure how this got missed, but I guess that's the danger of not
CI'ing with all of the supported platforms.

Fix another missing Alma/Rocky reference

---

network-configs/bond/ostest-master-0.yaml
network-configs/bond/ostest-master-1.yaml
network-configs/bond/ostest-master-2.yaml
network-configs/bond/ostest-worker-0.yaml
network-configs/bond/ostest-worker-1.yaml
network-configs/static/hosts.yaml
network-configs/static/ostest-master-0.yaml
network-configs/static/ostest-master-1.yaml
network-configs/static/ostest-master-2.yaml
network-configs/static/ostest-worker-0.yaml
network-configs/static/ostest-worker-1.yaml

These are some example configs that can be used with the NETWORK_CONFIG_FOLDER option added in #1418. In addition to making it easy for new users to test the networkConfig feature, this will also make it easier to run such configurations in CI.
To use, just set the variable to the appropriate path. For example:
export NETWORK_CONFIG_FOLDER=network-configs/static

OPNET-156: Add static and bond network configs

---

agent/01_agent_requirements.sh
agent/04_agent_configure.sh
common.sh
config_example.sh

This PR supports DHCP agent deployment with just agent-config.yaml and install-config.yaml. Set only `rendezvousIP` in the agent-config.yaml ( no hosts at all or no hosts with any network config). Devscripts provides no nmstateconfig.yaml
To create a DHCP agent deployment, `export AGENT_E2E_TEST_SCENARIO=HA_IPV4_DHCP` in config_\<user\>.sh.
Also, this is a change for 4.12 so `export OPENSHIFT_RELEASE_STREAM=4.12`
To test, run `make agent`

AGENT-245: DHCP only agent deployment

---

agent/04_agent_configure.sh
agent/common.sh
common.sh

Add dual-stack testing. The nmstate config now takes both v4 and v6 interfaces in dual-stack. In addition the agent-cluster-install.yaml takes the v4 and v6 subnets in ClusterNetwork, ServiceNetwork, and the now MachineNetwork.
Tested with COMPACT_IPV4, COMPACT_IPv6, and COMPACT_IPV4V6.

AGENT-158: Add support for testing agent with dual-stack

---

02_configure_host.sh
Makefile
agent/01_agent_requirements.sh
agent/04_agent_configure.sh
agent/common.sh
common.sh
config_example.sh
network.sh
oc_mirror.sh
oc_mirror_cleanup.sh
registry_cleanup.sh
utils.sh

Add a new variable - OC_MIRROR to mirror images using the `oc mirror` command.  If OC_MIRROR is not set then the mirroring will be done using 'oc adm release mirror'.  In addition a new variable REGISTRY_BACKEND is used to determine hw the registry is set, either the legacy way by creating a podman registry, or via the mirror-registry command.
Note that OC_MIRROR is currently only supported for the Agent implementation.

AGENT-316: Add support for oc mirror

---

agent/04_agent_configure.sh
agent/assets/agent-create-registries-conf-playbook.yaml
agent/assets/registries_conf.j2

These changes mirror MCE using `oc mirror` and updates registries.conf accordingly.
This PR is based off #1435 and is verified to work with the IPv4 disconnected scenario.
AGENT-331

AGENT-331: Add support for MCE disconnected scenario

---

agent/05_agent_create_cluster.sh

Fall back to the existing agent.iso filename only if (e.g.) agent.x86_64.iso is not present.

AGENT-390: Expect CPU arch to appear in ISO output filename

---

agent/04_agent_configure.sh
network.sh
ocp_install_env.sh
vm_setup_vars.yml

This PR adds a fix to #1389 to include only one VIP in the install-config in dual-stack environments <=4.11 (f1e0f51a2f982bd1180f4ec22e0a732158f0b89a).
Addition 1: It adds a fix in `add_dnsmasq_multi_entry()` to append the api vips, so both api vips are added to the dns_masq config file (9b796976f70c1ab182af14b404c909a8ab9f991d)
Addition 2: It renames the `API_VIP` and `INGRESS_VIP` fields to `API_VIPs` and `INGRESS_VIPs` to be clear these fields can contain multiple VIPs (012377813200b2b62419bf19eb182e2603077ecc).
Putting this on-hold until I finished all the tests in the different environments (4.11: v4,v6,v4v6, 4.12: v4,v6,v4v6)
/hold

network: add support to dualstack (including fix for environments before 4.12)

---

agent/04_agent_configure.sh
agent/assets/installconfig/agent-config_yaml.j2
agent/assets/installconfig/install-agent-config-playbook.yaml
agent/assets/installconfig/install-config_yaml.j2
agent/common.sh
common.sh
config_example.sh

Add support for install-config.yaml and agent-config.yaml for agent deployments and use it by default. ZTP manifests can still be used by setting the new 'AGENT_USE_ZTP_MANIFESTS' to true.  This uses ansible and jinja to create the yaml files files based on https://github.com/openshift-metal3/dev-scripts/pull/1458.

AGENT-392: Add support for install-config.yaml/agent-config.yaml

---

sanitychecks.sh

One thing I've noticed is that a lot of new dev-scripts users don't realize they need to run make clean between deployments. This adds a check for the ocp/<cluster name> directory before deployment and stops if it already exists. That directory is created pretty early in the process and removed by make clean so it should be a good indicator of whether a deployment has already been run. It's also specific to a given cluster so it shouldn't affect environments that are running multiple clusters of different names.

Check for existing cluster before deployment

---

agent/04_agent_configure.sh
network.sh

SNO clusters require at least the api dns entry to be set, otherwise the oc/openshift-install commands will not work properly

agent: set api dns entry for SNO clusters

---

agent/04_agent_configure.sh
agent/assets/installconfig/install-agent-config-playbook.yaml
agent/assets/installconfig/install-config_yaml.j2
agent/assets/ztp/registries-conf-playbook.yaml
agent/assets/ztp/registries_conf.j2

The mirror registries configuration for the agent is currently hardcoded. This is incorrect when a particular release image digest is defined, for example here is the ICSP for recent 4.12 image when using:
OPENSHIFT_RELEASE_IMAGE=registry.ci.openshift.org/ocp/release@sha256:508e696f24fc844cbbf9599ee6516c2f76d032f363a041df0441e3629ce64807
imageContentSources:
- mirrors:
- virthost.ostest.test.metalkube.org:5000/localimages/local-release-image 
source: registry.ci.openshift.org/ocp/4.12-2022-11-11-131611
- mirrors:
- virthost.ostest.test.metalkube.org:5000/localimages/local-release-image 
source: registry.ci.openshift.org/ocp/release
The mirror registries should be extracted from the log files when the 'oc adm release mirror' or 'oc mirror' commands are run. This will be correct for all …

AGENT-429: Dynamically generate mirror configuration for agent

---

agent/04_agent_configure.sh

Fix for unbound variable error when using ipv6 to deploy a SNO cluster

Fix dns entry for SNO cluster with ipv6

---

common.sh

Keep OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE as OPENSHIFT_RELEASE_IMAGE when the release tag is a digest (usually this happens in the CI), since it's used in different parts of the workflow (ie when generating the ztp manifests)

fix agent builds when local mirror is used

---

scripts/periodics_pass_rates.sh

Using the search string "nightly-<version>" on job names ensures we don't get incorrect hits for upgrade jobs (upgrading from <version> )

Better default for jobs names

---

Makefile
agent/04_agent_configure.sh
agent/gather.sh

A new target `make agent_gather` allows the user to gather useful troubleshooting data when things go wrong even before the API services are available.
Signed-off-by: Pawan Pinjarkar [ppinjark@redhat.com](mailto:ppinjark@redhat.com)

AGENT-350: Gather agent data with 'make agent_gather'

---

02_configure_host.sh

openshift-metal3/dev-scripts#1483 bumped the version of metal3-dev-env to a commit including the changes in metal3-io/metal3-dev-env#1022. However, SATA is unavailable as a disk/cdrom bus for arm64 hypervisors, and #1483 broke the CI for arm64.
```
"msg": "libvirtError: unsupported configuration: SATA is not supported with this QEMU binary"
```
Failures in CI:
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-multiarch-master-nightly-4.11-ocp-e2e-metal-ipi-ovn-arm64/1602625608012009472
- https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetalds-ipi-ovn-ipv4-p1-f4/1603156946309877760
The fix is also being tested in the legacy QE CI at: …

Use SCSI as cdrombus when the provisioner node architecture is aarch64

---

01_install_requirements.sh

This change avoids installing the python version of yq if there is
already another version installed. This allows a user to install the
golang version from https://github.com/mikefarah/yq, for example, when
that version is required by other apps or scripts running on the same
host as dev-scripts.

do not stomp on existing yq

---

01_install_requirements.sh

Reverts openshift-metal3/dev-scripts#1483
The change brought in https://github.com/metal3-io/metal3-dev-env/pull/1059/commits/b8a223c452d5133984796cb314213fccc5397eae that adds redfish-virtualmedia to the bmc drivers tested in CI, breaking the dualstack jobs

OCPBUGS-4977: Revert "Use ansible 6"

---

Makefile

Removing the registry in regular clean does bad things to the developer workflow because while iterating on changes the entire release has to be re-mirrored each time. Those who want to wipe their entire environment between runs have the realclean option available.

Move registry cleanup back to realclean

---

agent/roles/manifests/templates/install-config_yaml.j2

We shouldn't require users to set the host details in the install-config, given that they are not used for anything. A previous bug where we did require them was fixed as [OCPBUGS-3278](https://issues.redhat.com/browse/OCPBUGS-3278). Remove this section from the install-config template so that we cannot regress it.

OCPBUGS-4874: Remove hosts section from platform.baremetal

---

agent/06_agent_create_cluster.sh
config_example.sh

When developing the WebUI for the agent based installation, it is useful to disable the services that automatically grab the manifests in the ISO and create and start the installation by talking to the REST API. This PR adds a new setting named AGENT_DISABLED_AUTOMATED that when set to true will prevent those services from running.
Signed-off-by: Antoni Segura Puimedon <antoni@redhat.com>

agent: optionally disable automation services

---

02_configure_host.sh
oc_mirror.sh
utils.sh

This is a follow-up to https://github.com/openshift-metal3/dev-scripts/pull/1472 to get the auth set up properly when using the quay registry backend.

AGENT-499: Fixes for auth when using quay registry

---

01_install_requirements.sh
go.mod

updated golang version to match build containers
```sh
podman run registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.19-openshift-4.13 go version
go version go1.19.4 linux/amd64
```
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>

Bump go_version to 1.19.4

---

common.sh
config_example.sh
oc_mirror.sh

Add the ability to use oc-mirror to create a mirror registry by generating a tarfile first and then publishing the tarfile to the registry. The can be used to test a common use case for disconnected installs.

AGENT-500: Add configurable step to oc-mirror to generate tarfile

---

oc_mirror.sh

If the quay registry backend is configured but the podman registry is still set up, the "mirror-registry" command will fail and it will be difficult to debug. Exit the command with instructions of how to remove the podman registry.

AGENT-509: Warn if podman registry in use when configured for quay

---

agent/common.sh

We need to source network.sh before referencing IP_STACK or it may be unset in the default case.

Fix unbound variable in agent/common.sh

---

images/Dockerfile.ci

We temporarily need to support both RHEL 7 and 8
as we can't change the ci-operator image build to switch
to rhel a new image in lockstep. Once the switch over is done
we can remove the RHEL7 support.
This should allow use to eventually remove the NSS_WRAPPER_PASSWD
hack in baremetalds-packet-setup-commands.sh

Update dev-script CI image

---

config_example.sh
network.sh
ocp_install_env.sh

Adds a new value "v6v4" for IP_STACK to allow deployment of clusters with ipv6 as the primary address family.

OPNET-200: Add support for ipv6-primary dual stack

---

agent/05_agent_configure.sh

In 4.14 the `oc adm release mirror` command has been updated to output ImageDigestSources instead of ImageContentSources. Update the agent script to handle both.
See https://github.com/openshift/oc/pull/1341#issuecomment-1498475901 for the slightly different output.
Also there is a minor fix for inadvertent hardcoding of working dir.

Agent-613: Support imageDigestSources for oc adm release mirror

---

common.sh

The H/W validation minimum was changed to be consistent with docs in https://github.com/openshift/installer/pull/7025. Set the disk size for agent disk to be minimum.

Use 100 GB for agent default disk size

---

agent/06_agent_create_cluster.sh
agent/README.md
common.sh
config_example.sh

Generates pxe assets by running `./openshift-install agent create pxe-files` command. 
Set `AGENT_E2E_TEST_BOOT_MODE` to `PXE` along with `AGENT_E2E_TEST_SCENARIO` to `SNO_IPV4`, for example, to create an SNO cluster to be booted with PXE. The `AGENT_E2E_TEST_BOOT_MODE` can be set as `PXE` or `ISO`. `ISO` is the default boot mode.
To test, set `export INSTALLER_REPO_PR=7102` in config_<user\>.sh

AGENT-603: Support 'create pxe-files' command for ABI

---

02_configure_host.sh
agent/06_agent_create_cluster.sh
agent/cleanup.sh
common.sh

This patch adds the possibility to test ABI via iPXE booting, to verify that the PXE artifacts generated with the `agent create pxe-files` command can be successfully used. IPv4/IPv6 supported.
Requires https://github.com/openshift-metal3/dev-scripts/pull/1526, https://github.com/openshift/installer/pull/7185

AGENT-604: support agent iPXE booting

---

config_example.sh

https://github.com/openshift-metal3/dev-scripts/pull/1528 now supports IPV6 as well for PXE booting.
Hence, the updated docs.

Agent can PXE boot on IPV6 as well

---

agent/06_agent_create_cluster.sh

Previous implementation didn't allow the script to exit properly.
Required by https://github.com/openshift/release/pull/39907

AGENT-439: avoid pxe server command blocking the step script

---

agent/06_agent_create_cluster.sh
agent/common.sh
config_example.sh

This provides a test for both https://issues.redhat.com/browse/AGENT-558 and https://issues.redhat.com/browse/AGENT-559. It runs the installer commands to create an unconfigured ignition and to create a config-image. It creates an ISO from the unconfigured ignition suitable for booting the VM. It also attaches the config-image to the VM which will be loaded when detected during system boot.
Also adds a new config setting `AGENT_APPLIANCE_HOTPLUG` that when set will configure the hosts using the unconfigured ignition and then pend for user input before creating the config-image and mounting it to the host. This emulates a situation where a user boots the host first before adding the config-image and continuing the installation.

AGENT-616: Create unconfigured ignition and config-image and mount to VM

---

01_install_requirements.sh
04_setup_ironic.sh
README.md
agent/roles/manifests/tasks/main.yml
agent/roles/manifests/templates/infraenv_yaml.j2
agent/roles/manifests/templates/install-config_yaml.j2
common.sh
config_example.sh

Enable the ability to test arm64 with agent installer: https://github.com/openshift/installer/pull/6401

AGENT-242: Enable agent installer installs for arm64

---

start-mao.sh
stop-cbo.sh
stop-mao.sh

Prior to OCP 4.10, the 'group' field in the override was ignored.
Although "apps/v1" was the documented thing to pass, after
https://github.com/openshift/cluster-version-operator/pull/689 stopped ignoring the field, only
"apps" works.
My proposed fix for [OCPBUGS-15390](https://issues.redhat.com/browse/OCPBUGS-15390) is to
make both work, so we might as well switch to the one that works with
older releases.

Fix CVO overrides

---

agent/roles/manifests/templates/agent-config_yaml.j2

NETWORKING_MODE env var supports 'DHCP' value in upper-case. Hence, in order to support this network mode in agent-config template, changed to upper-case 'DHCP'.

Fix DHCP network mode on agent-config.yaml

---

agent/roles/manifests/templates/agent-cluster-install_yaml.j2

This data ended up one level too high, which broke SNO CI.

Agent: Move userManagedNetworking under networking

---

agent/06_agent_create_cluster.sh

New users do not have this directory.
This is causing the CI job to fail because the CI user does not have this directory.

Create $HOME/.cache/agent/image_cache before extracting to it

---

agent/roles/manifests/templates/agent-config_yaml.j2

This fixes a validation problem when using IPv6_DHCP.

OCPBUGS-16781: Fix validation failure when using IPv6_DHCP

---

common.sh

This patch reverts the workaround introduced in https://github.com/openshift-metal3/dev-scripts/pull/1519

Revert the workaround for the rhcos storage issue

---

agent/06_agent_create_cluster.sh

Fix script failure if the file doesn't exist.

Fix failure if nmstateconfig.yaml doesn't exist

---

agent/06_agent_create_cluster.sh
agent/cleanup.sh
agent/common.sh
agent/roles/manifests/tasks/appliance.yml
agent/roles/manifests/tasks/main.yml
agent/roles/manifests/templates/agent-config_yaml.j2
agent/roles/manifests/templates/appliance-config_yaml.j2
agent/roles/manifests/templates/install-config_yaml.j2
common.sh
config_example.sh

Added support for running the agent flow using the openshift-appliance[1] disk image.
To invoke the flow, use the following env var in config:
`export AGENT_E2E_TEST_BOOT_MODE=DISKIMAGE`
The appliance flow is as follows:
* Generate appliance-config.yaml[2]
* Includes config required for building the appliance
* Build the appliance disk image using the container image defined in APPLIANCE_IMAGE env var
* Create the config-image ISO
* Clone the appliance disk image for every node
* As each node needs a seperate disk for exclusive i/o
* Attach a cloned disk image to each node
* Attach the config-image ISO to all nodes
* Boot all machines from the disk image
Note: based on config-image support [PR](https://github.com/openshift-metal3/dev-scripts/pull/1533)
[1] …

agent: introduce openshift-appliance flow

---

agent/roles/manifests/templates/appliance-config_yaml.j2

Added a default 'userCorePass' to appliance-config.yaml file. This is useful for debug purposes (to login through console).

appliance: added userCorePass to appliance-config

---

agent/06_agent_create_cluster.sh

The config-image should be created only once (as the ISO is shared by all machines).
Hence, moved the config-image creation logic outside of the 'attach_appliance_diskimage' func.
I.e. Since this func is called twice (both for masters and workers).

appliance: ensure config-image is created once

---

agent/common.sh
agent/roles/manifests/templates/agent-config_yaml.j2
agent/roles/manifests/templates/net_macros.yaml
agent/roles/manifests/templates/nmstateconfig_yaml.j2
agent/roles/manifests/vars/main.yml
config_example.sh

The Agent IPV6_DCHCP test fails due to the address assigned via DHCPv6 not matching the rendezvousIP. The reason is that by default NetworkManager sends DHCPv6 Solicitations with a Client ID of DUID-UID (prefix=00:04, see https://datatracker.ietf.org/doc/html/rfc6355) containing a machine specific value. When using nmstateconfig for DHCP, the NetworkManager keyfiles are setup for each interface with dhcp-duid=ll (prefix=00:03, see https://datatracker.ietf.org/doc/html/rfc3315#section-9.4) which means that the DHCPv6 Solicitation is based on the mac address. This allows the DHCPv6 server to assign a deterministic address which can be set to match the rendezvousIP, e.g
https://github.com/metal3-io/metal3-dev-env/blob/main/vm-setup/roles/libvirt/templates/network.xml.j2#L93
Using the …

OCPBUGS-16912: Agent use nmstateconfig for DHCP tests

---

agent/common.sh

Sourcing the non-step script `network.sh` within the non-step script `agent/common.sh` introduces a not explicit dependency that may produce unwanted side-effects.
In particular, since the `agent/common.sh` is source into the `agent/01_agent_requirements.sh` _before_ the generic `/01_install_requirements.sh`, all the functions in `network.sh` needing a specific software requirement - like ansible for [nth_ip](https://github.com/openshift-metal3/dev-scripts/blob/f4c1080455a3d1928b6ee675ec379de31ad703e5/network.sh#L7) - are going to fail.
The blocking issue was initially discovered by @danielerez while trying to activate the `INSTALLER_PROXY` config var, which requires the [PROVISIONING_HOST_EXTERNAL_IP](https://github.com/openshift-metal3/dev-scripts/blob/f4c1080455a3d1928b6ee675ec379de31ad …

Removing sourcing of the non-step network.sh script

---

agent/06_agent_create_cluster.sh

Now that the kubeadmin-password is generated this workaround can be removed.

Remove agent workaround for kubeadmin-password

---

02_configure_host.sh

If the BM interface is up the virsh command can't activate it, it fails with the error:
error: error creating bridge interface ostestbm: File exists
Bring the BM bridge down before virsh brings it back up

Bring down bm interface before virsh bring it back up

---

agent/06_agent_create_cluster.sh

After copying appliance.raw disk image for each node, the source file is no longer needed.
Hence, deleting the file to avoid storage overconsumption on CI machines.

appliance: remove unused appliance.raw disk image

---

02_configure_host.sh
agent/05_agent_configure.sh
agent/common.sh
agent/roles/manifests/tasks/install-config.yml
agent/roles/manifests/tasks/ztp.yml
agent/roles/manifests/templates/agent-config_bond_yaml.j2
agent/roles/manifests/templates/agent-config_yaml.j2
agent/roles/manifests/templates/net_macros.yaml
agent/roles/manifests/templates/nmstateconfig_bond_yaml.j2
agent/roles/manifests/vars/main.yml
config_example.sh
network.sh
utils.sh

Add a new variable - BOND_CONFIG, that defines the bonding mode to be used with nmstate configuration when creating 2 nics in a bond. Use the existing variable - BOND_PRIMARY_INTERFACE to indicate that a bond should be created, a random mac will be generated for the 2nd interface so that the two bond interfaces have unique macs.
Co-Authored-By: Richard Su <rwsu@redhat.com>

AGENT-428: Add support for bonding with unique macs

---

agent/roles/manifests/templates/agent-config_bond_yaml.j2
agent/roles/manifests/templates/agent-config_yaml.j2

https://github.com/openshift/installer/pull/7450 renamed `ipxeBaseURL` to more generic `bootArtifactsBaseURL`. 
This PR fixes it in dev-scripts.

Rename ipxeBaseURL to bootArtifactsBaseURL

---

agent/06_agent_create_cluster.sh
agent/cleanup.sh
agent/common.sh

https://github.com/openshift/installer/pull/7450 renamed `pxe` to more generic `boot-artifacts`.
This PR fixes it in dev-scripts.

Update directory name

---

agent/05_agent_configure.sh
agent/roles/manifests/templates/agent-cluster-install_yaml.j2
agent/roles/manifests/templates/install-config_yaml.j2

Initial support for the external OCI platform. This sets the libvirt domain manufacturer and product to allow the assisted-service validations for this platform to pass.
Requires https://github.com/openshift/assisted-service/pull/5438 and https://github.com/openshift/installer/pull/7442
In addition, this requires changes to either:
a) use a minimalISO instead of a fullISO in the agent-based-installer 
b) not require a mimimalISO in assisted-service

AGENT-698: Agent support for OCI platform

---

ocp_cleanup.sh

I'm finding after the change https://github.com/openshift-metal3/dev-scripts/pull/1573 to workaround the upgrade issue that running 'make clean; make agent' fails with the error:
```
+(utils.sh:294): sync_repo_and_patch(): git checkout main Already on 'main'
M	vm-setup/roles/packages_installation/tasks/centos_required_packages.yml Your branch is behind 'origin/main' by 454 commits, and can be fast-forwarded.
(use "git pull" to update your local branch)
+(utils.sh:295): sync_repo_and_patch(): git fetch origin
+(utils.sh:296): sync_repo_and_patch(): git rebase origin/main
error: cannot rebase: You have unstaged changes.
error: Please commit or stash them.
+(utils.sh:1): sync_repo_and_patch(): removetmp
+(utils.sh:777): removetmp(): '[' -n ' /tmp/test-token--Zw8ebP1VUP' ']'
+(utils.sh:777): …
```

Restore metal3-dev-env file

---

02_configure_host.sh
03_build_installer.sh
config_example.sh
utils.sh
validation.sh

This change adds the ability to deploy OKD versions without requiring the CI_TOKEN. This improves the ability to automate deployments and makes dev-scripts accessible to a wider range of users from the community.

Remove CI_TOKEN requirement for OKD deployments

---

01_install_requirements.sh

ipi jobs fail installing lxml as it needs python39 libxml2 and libxslt
devel packages
Resolves: https://github.com/openshift-metal3/dev-scripts/issues/1558

arm64 needs devel packages for lxml install

---

02_configure_host.sh

In specific scenarios we deploy dual-stack NICs even if the host is configured as IPv4 stack (e.g. when testing multi NIC with nmstate). In this situation we forgot to set accept_ra what causes deployment to fail.
With this change we will set accept_ra no matter the topology of the cluster so that we can have all types of VMs created.

Set net.ipv6.conf.all.accept_ra=2 for all topologies

---

ocp_install_env.sh

Add new install-config param 'bootstrapExternalStaticDNS' with value 192.168.111.1 for cluster with static IP address
https://github.com/openshift/installer/pull/6585

Add new param bootstrapExternalStaticDNS

---

config_example.sh
ocp_install_env.sh

Used on the external NIC on the bootstrap VM.

Add externalMACAddress to be configured

---

04_setup_ironic.sh

We were matching containers with a common ending.

Make sure we test for containers with a full name match

---

agent/04_agent_prepare_release.sh
common.sh

In some cases it may be useful to provide a custom image name - rather than using the folder name as a default - when preparing a local release.
This is particularly useful for the agent-based installer, since the same repo may be used to produce (more than one) different images shipped in the release payload (having their own name).
Also, enabling automatically local registry when using custom images also for the agent workflow

Allow pushing custom image names when preparing a release

---

common.sh

Since CI hosts do not run with FIPS mode enabled, disable checking for it in openshift-install by default. This setting can be overridden in the config by setting FIPS_VALIDATE=true.

Skip host FIPS validation in installer by default

---

04_setup_ironic.sh
utils.sh

We have observed that in specific environments (e.g. CI with IPv6-only)
there are missing default credentials for the local registry hosted at
`virthost.ostest.test.metalkube.org:5000` what causes errors like
```
Trying to pull [...]
Error: initializing source docker://virthost.ostest.test [...]
[...] /localimages/local-release-image: authentication required
```
In order to fix that, we are trying to explicitly pull the image with
`--authfile` so that the subsequent `podman run` has the image already
available.
---
We have also noticed that when release image constains manifest list but
the list contains only a single image, then `oc adm release mirror`
unpacks the list causing digests of the images to change. In order to
prevent that, we are explicitly requesting that manifest lists are …

Mirror manifest lists and use authfile explicitly

---

02_configure_host.sh
host_cleanup.sh

In order to ensure that the IPv6 bridge interface comes up add a dummy interface.
We did the BM interface long ago but never did the provisioning interface.

OCPBUGS-20404: Add a dummy interface to IPv6 bridge (#1442)

---

agent/05_agent_configure.sh
agent/06_agent_create_cluster.sh
agent/common.sh

When building the configImage, the extra manifests were not being added to the directory where it was built.

OCPBUGS-22417: Include extra manifests when building configImage

---

agent/05_agent_configure.sh
agent/roles/manifests/templates/install-config_yaml.j2

When the platform type is "vsphere", set the host's manufacturer to VMWare in order to pass the assisted-service validations and allow the installation to proceed.

OCPBUGS-19676: Allow agent VSphere installs by simulating VMWare host

---

02_configure_host.sh

gpasswd does the same as the usermod call we have just before. It was
mostly a mix with the newgrp command, but it doesn't help either.
Since there's no way to reload the groups system wide without a logout
and login, we can't really do anything...

Remove gpasswd command call

---

01_install_requirements.sh
02_configure_host.sh
06_create_cluster.sh
common.sh
config_example.sh
host_cleanup.sh

Disruptive CI jobs require a PV with
ReadWriteMany access mode.

METAL-759: Add nfs volume

---

vm_setup_vars.yml

This reverts commit d96ef53d6ba06300f2e7c5c42db2e6907153ec96.
The revert is done to prevent duplicate DNS records in ostestbm network.
E.g.
```
[2023-11-23 13:42:15]   <dns>
[2023-11-23 13:42:15]     <forwarder domain='apps.ostest.test.metalkube.org' addr='127.0.0.1'/>
[2023-11-23 13:42:15]     <host ip='fd2e:6f44:5dd8:c956::5'>
[2023-11-23 13:42:15]       <hostname>api</hostname>
[2023-11-23 13:42:15]     </host>
[2023-11-23 13:42:15]     <host ip='fd2e:6f44:5dd8:c956::2'>
[2023-11-23 13:42:15]       <hostname>ns1</hostname>
[2023-11-23 13:42:15]     </host>
[2023-11-23 13:42:15]     <host ip='fd2e:6f44:5dd8:c956::1'>
[2023-11-23 13:42:15]       <hostname>virthost</hostname>
[2023-11-23 13:42:15]     </host>
[2023-11-23 13:42:15]     <host ip='fd2e:6f44:5dd8:c956::5'>
[2023-11-23 …
```

Revert "OCPBUGS-15056: Use v4 network for v4-primary dual stack (#1534)"

---

01_install_requirements.sh
02_configure_host.sh
06_create_cluster.sh
common.sh
config_example.sh
host_cleanup.sh

This reverts commit b4b21a39713af2b1166ffdaf6e9da26a1c98a841.
It may have broken some dualstack setups (depending on which network was priary)

Revert "METAL-759: Add nfs a backed persistent volume (#1608)"

---

agent/roles/manifests/templates/agent-cluster-install_yaml.j2

In agent_cluster_install.yaml, include VIPS in addition to VIP to be compatible with the assisted-service change.
https://github.com/openshift/assisted-service/pull/5501

AGENT-337: When using ZTP manifests, support both VIP and VIPs

---

images/Dockerfile.ci

Since the move to rhel 9, the packet-setup step is broken because
packet-python is installed in 3.9 environment and ansible in 3.11.
This PR fixes this issue.

NO-ISSUE: Install packet-python in 3.11 environment

---

agent/04_agent_prepare_release.sh
agent/docs/custom-release.md

This patch adds the possibility to specify an additional build arg when building a local repo. In addition, it ensures that the installer will be extracted from the mirror, so that the subsequent steps will use the updated one -  in case it was just rebuilt (this feature will avoid specifying `export KNI_INSTALL_FROM_GIT=true` when using a custom release)

Add build arg to custom release

---

images/Dockerfile.ci

Install posix collection in order to use synchronize module. It was a
built-in module before.
Remove the constraint on general collection as it was pinned because
rhel 8 used a old version of ansible, which is not the case anymore with
rhel 9 (https://github.com/openshift-metal3/dev-scripts/pull/1399).

MGMT-16396: Install ansible.posix collection

---

04_setup_ironic.sh
06_create_cluster.sh
agent/03_agent_build_installer.sh
agent/05_agent_configure.sh
agent/06_agent_create_cluster.sh
generate_clouds_yaml.sh
network.sh
ocp_cleanup.sh
ocp_install_env.sh
release_info.sh
utils.sh

OpenShiftSDN is being deprecated in 4.15, so switch the default to OVNKubernetes in the IPv4-only case (OVNk is already required for IPv6/dual-stack) to avoid installer failures.
This follows up on 8537fdd1e01fa07caa7f09ed03c6beafdacb9378, which sets OpenShiftSDN in the manifests (but not the install-config) iff it is *explicitly* requested.

CORS-2969: Don't default to OpenShiftSDN after deprecation

---

06_create_cluster.sh

The create_cluster function in utils.sh relies on the function override_openshift_sdn_deprecation defined in ocp_install_env.sh. Therefore latter must be sourced anywhere that create_cluster is used, and it should not have been removed from 06_create_cluster.sh by 41443197abc8a748e192ef87e1c4c3b74c693059.

OCPBUGS-27189: Fix dependency issue

---

04_setup_ironic.sh

This patch fixes a git error when running step 4 multiple times and building the ironic-image with a specific PR number.

Avoid git fetch error when using PR number

---

01_install_requirements.sh

https://issues.redhat.com/browse/MGMT-16990
Hive has increased the minimum go version required to 1.21 which breaks the assisted-service CI jobs since the go version is pinned to 1.20.
This introduces a configurable `GOVERSION` variable to allow other versions to be specified and installed.
/cc @adriengentil

MGMT-16990: Make the go version installed configurable

---

01_install_requirements.sh
config_example.sh

In this PR, we change the variable `GOVERSION` to `GO_VERSION` to prevent encountering failures due to mismatched value format.
If `go` is exists and we execute `make`, then `GOVERSION=go<version>` is format of the value being set. However, `install-package-playbook.yml` expects the value to be only the `version` instead of the prefix `go`.
Fixes #1639

Change the go version variable name.

---

host_cleanup.sh

Restart network service after removing the old network definitions to completely remove them and allow upgrade in CentOS 8 old dev-scripts deployments.

Upgrade from CentOS 8 compatibility

---

agent/06_agent_create_cluster.sh
agent/roles/manifests/tasks/install-config.yml
agent/roles/manifests/templates/install-config_vsphere_yaml.j2
common.sh
config_example.sh

Fake credentials are added to install-config.yaml for vSphere platform.
In combination with
https://github.com/openshift-metal3/dev-scripts/pull/1588, this patch allows testng of installer and assisted-service validations for the vSphere platform.
A complete install for vSphere using dev-scripts is currently not possible because the vSphere environment is partially simulated using libvirt VMs. Any cloud controller manager interactions with vSphere will fail in libvirt because there isn't an actual vSphere environment that is being exercised.
In this setup, only "agent wait-for bootstrap-complete" will succeed. For vSphere, "agent wait-for install-complete" will fail and is skipped.
Add these to config_<username>.sh script to test:
```
export AGENT_PLATFORM_TYPE=vsphere
export …
```

AGENT-724: Deploy vSphere clusters with credentials

---

host_cleanup.sh

systemctl requires sudo to run
also removing the || true to avoid covering hidden errors, the network service should always be present before the migration and if any ifcfg file is there

Fix upgrade from CS8 compatibility

---

ocp_install_env.sh

In the course of bumping oc's base image to RHEL9, it is needed that the environments bases on RHEL 8 (at least for now) to use oc RHEL8 binary. This PR enables that when the dev-scripts is also bumped to RHEL9, it will be an easy change to use oc.rhel9 explicitly.
This PR changes the extraction of oc to oc.rhel8 which exists in 4.15 and 4.16 release payloads and fall backs to default oc for older releases.

OCPBUGS-20097: Extract oc RHEL8 binary from release explicitly

---

images/Dockerfile.ci

'facility' was deprecated from Dec 1, 2023. This PR update is to use [equinix.cloud ansible
collection](https://deploy.equinix.com/labs/ansible-collection-equinix/) to enable use of 'metro'.

OCPQE-19493: Update image with equinix.cloud collection

---

01_install_requirements.sh
02_configure_host.sh

CI job that ran on rocky9 with this branch
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50285/rehearse-50285-periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-ipv6/1778423230030155776

Add rocky9 support

---

03_build_installer.sh
common.sh
utils.sh

With https://github.com/openshift/installer/pull/8161, the baremetal installer is now part of the regular installer which is now statically linked.
Using the static binary has the advantage of working on both CS8 and CS9 VMs and is a necessary step for moving the Installer images to a RHEL9 base.

CORS-3462: extract static openshift-installer from 4.16

---

04_setup_ironic.sh

fallback to statically linked latest upstream
release of the opm binary if it cannot be downloaded from mirror.openshift.com (
https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.16.0/opm-linux.tar.gz is still not there) or if the downloaded binary cannot be executed (on OCP 4.15 and greater is linked only for RHEL9, see: https://issues.redhat.com/browse/OPRUN-3221 ).

opm: fallback to upstream opm on failures

---

02_configure_host.sh

We have observed the below error in some of our deployments.
```
2023-11-23 15:20:02 level=error msg=Error: failed to dial libvirt: dial unix /var/run/libvirt/libvirt-sock: connect: no such file or directory
```
Using this patch, we are able to proceed when the above error is observed. Newer deployments with this patch have been successful.

Enable libvirt proxy local socket

---

agent/06_agent_create_cluster.sh
agent/e2e/agent-tui/test-fix-wrong-dns.sh

This patch fixes the failing `AGENT_TEST_CASES` `bad_dns` script. Since Openshift 4.16, the nmtui main panel shows an additional "Radio" entry, thus requiring an additional step for a proper selection.

OCPBUGS-34581: Fix bad dns agent test for ocp 4.16

---

01_install_requirements.sh

* Upgrade metal3-dev-env to latest
* ~Install python 3.11 on centos8~
* Use ansible 7.1.0 to match metal3-dev-env
There is a breaking change in metal3-dev-env.  This openshift/release PR resolves it:
https://github.com/openshift/release/pull/38008

Upgrade to Ansible 7

---

01_install_requirements.sh

Package update doesn't restart NetworkManager resulting in a mismatch between Client and Server versions

Restart NetworkManager after updating packages

---

01_install_requirements.sh
02_configure_host.sh

The previous one got reverted because it did not account for certain variable changes.

Another attempt to update Ansible and metal3-dev-env

---

01_install_requirements.sh

Also install it early and pin its version

Avoid installing yq twice

---

01_install_requirements.sh

Starting from RHEL9 some packages (e.g. libvirt-devel) have been moved to the CRB repo, which is not enabled by default. Add the proper command to enable it on RHEL9, noting that a valid subscription is needed for that.

METAL-1089: Enable CRB repo in RHEL9

---

01_install_requirements.sh

In el9 python is already version 3.9 and the devel package is simply named python3-devel, the python39-devel package does not exist.

Install python-devel package based on OS version

---

01_install_requirements.sh

https://github.com/openshift-metal3/dev-scripts/pull/1674 enables CRB repos on RHEL using subscription-manager.
RHEL system might not be subscribed to subscription-manager. The system might be using custom repos to install libvirt-devel package. Then dev-scripts installation will fail.
In order to fix it. We can use subscription-manager identity command to check the system status. If a system is subscribed to subscription manager, then exit status will be 0 else 1.
Below is the example for the same:
A system is subscribed with subscription-manager:
```
[zuul@ospci-baremetal-01 ~]$ sudo subscription-manager identity
system identity: xxx
name: xxx
org name: xxx
org ID: xxx
[zuul@ospci-baremetal-01 ~]$ echo $?
0
```
A system with no subscrition:
```
[root@ospci-baremetal-02 ~]# …
```

Run subscription-manager command when system is subscribed

---

01_install_requirements.sh

The existing code works a bit accidentally, because the command output is ignored anyway. If there would be no output redirection to /dev/null, then the command would always fail with something like ~"Command not found: This system is not yet registered".
Details: https://www.shellcheck.net/wiki/SC2091

Remove unwanted $

---

04_setup_ironic.sh
common.sh

The ironic-ipa-downloader container has been removed since OCP 4.10

Remove ipa-downloader leftovers

---

01_install_requirements.sh

metal3-dev-env is hard reset to an old commit hash to avoid disruption in testing. Adding a temporary workaround ( till fix in PR https://github.com/metal3-io/metal3-dev-env/pull/1442 is effective)

OCPQE-24202: Temporary hack to update baremetalvm.xml.j2

---

01_install_requirements.sh
02_configure_host.sh

Old hash from July 26, 2023
https://github.com/metal3-io/metal3-dev-env/commit/4e5497b
New hash from July 27, 2023
https://github.com/metal3-io/metal3-dev-env/commit/32f90c7
"fix incorrect EFI firmware reference in VM template"

Update metal3-dev-env hash

---

01_install_requirements.sh

New hash is from commit
https://github.com/metal3-io/metal3-dev-env/commit/62be8305720509325000e89d2ca4d80b795421fb
that fixes an issue with bm vm xml libvirt template

Update metal3-dev-env hash and remove  yet another hack

---

agent/05_agent_configure.sh

It appears that https://github.com/openshift-metal3/dev-scripts/pull/1654 broke the bonding configuration in 05_agent_configure.sh. AGENT_NODES_MACS was only adding a singular mac at line 106, not an array. Fixed to add in the bond mac correctly.

Fix agent bonding configuration

---

common.sh
config_example.sh

This is valid for local runs only.

Move default release to 4.18

---

utils.sh

The code to conditionaly add --keep-manifest-list=true to the mirror command was added for a now unsupported version of OC. Remove it as it doesn't always work e.g. if the .releaseClientVersion doesn't follow the 4.XX... format.
4.15.0-0.nightly-2024-..-.....
vs
0.0.1-0.test-2024-....-latest

Always mirror with --keep-manifest-list=true

---

agent/06_agent_create_cluster.sh

When running the appliance flow, virt-xml fails when trying to add a new disk with the following [error](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8487/pull-ci-openshift-installer-master-e2e-agent-compact-ipv4-appliance-diskimage/1802735980159963136#1:build-log.txt%3A17189):
```
+(./agent/06_agent_create_cluster.sh:141): attach_appliance_diskimage(): sudo virt-xml ostest_master_0 --add-device --disk ocp/ostest/appliance.raw_master_0,device=disk,target.dev=sda
ERROR    XML error: target 'sda' duplicated for disk sources '<null>' and '/root/dev-scripts/ocp/ostest/appliance.raw_master_0'
```
The error is raised since the first device in domain xml is an empty cdrom disk:
```
<disk type='file' device='cdrom'>
<driver name='qemu' type='raw'/> …
```

appliance: fix disk attach using virt-xml

---

agent/07_agent_add_node.sh

A bug fix to oc changed the filename of the generated node ISO to include the architecture. Previously the name was node.iso. Because the default architecture used in devscripts is x86_64/amd64, the name is now node.x86_64.iso.
Depends on https://github.com/openshift/oc/pull/1887

OCPBUGS-42528: Day 2 iso name changed to node.x86_64.iso

---

06_create_cluster.sh

Disable client caching of file attributes and force the writes to become synchronous making local changes to a file become visible on the server immediately.

Mount nfs with noac

---

01_install_requirements.sh
agent/07_agent_add_node.sh
common.sh
config_example.sh

This patch is required to test https://github.com/openshift/installer/pull/9066 
As a rule of thumb, node-joiner patches may require to update as well the related wrapping oc commands (which could be present in CI registries but not yet released to the usual mirror)

AGENT-966: use oc from current release image

---

01_install_requirements.sh
agent/07_agent_add_node.sh
common.sh
config_example.sh

Reverting the previous patch as the `OPENSHIFT_CLIENT_FROM_RELEASE` was broken and not required (since step 03 already extracts the oc tool from the release image).
Also, adding missed statements for properly logging the new agent step 07 (for adding nodes)

NO-JIRA: revert #1706

---

02_configure_host.sh
06_create_cluster.sh
network.sh

Ensure all but BMC traffic goes via the proxy

OCPBUGS-36506: Fix config for disconnected cluster

---

agent/07_agent_add_node.sh

This patch increases the `oc adm node-image ...` commands loglevel to help troubleshooting CI jobs failures

NO-JIRA: increase log level for day2 add nodes commands

---

Makefile
agent/07_agent_add_extraworker_nodes.sh
agent/agent_remove_all_extraworker_nodes.sh

Adds a new target to remove all extraworker nodes:
make agent_remove_node
The nodes are deleted from the cluster. The VM is then shutdown and its disk reinitialized to be empty. Any agent ISO attached as /dev/sdc is also removed.
The extraworker nodes can be added back to the cluster by running:
make agent_add_node
They can be repeated added and removed using these two make targets.

AGENT-963: make target to remove extraworker nodes from cluster

---

agent/07_agent_add_extraworker_nodes.sh

Remove debug logging since too verbose

NO-JIRA: use default logging for oc adm node-image commands

---

06_create_cluster.sh

When "INSTALLER_PROXY" is set all services on the virt hosts are blocked unless explicitly enabled.

Allow bootstrap to talk to ntp

---

agent/07_agent_add_extraworker_nodes.sh

Required by https://github.com/openshift/release/pull/59335

NO-JIRA: skipping add-nodes step for ocp versions lower than 4.17

---

agent/05_agent_configure.sh
agent/07_agent_add_extraworker_nodes.sh

This patch skips the 07 step in case no extra workers are present.

NO-JIRA: skip the add nodes step if no additional workers are defined

---

01_install_requirements.sh
02_configure_host.sh

This seems to have been dropped in the move from 8 to 9. Just adding it back in so we have equivalent functionality for 8 and 9-based distros (and because I'm still using it).

Add support for Alma 9

---

01_install_requirements.sh
utils.sh

changed the node role to be applied on index count and not on name, in ci the host name can be anything so we need to trigger based off of the order.

OCPEDGE-1645: fix: change node role arbiter logic

---

common.sh

Increase the memory for these tests and they are failing in 4.19 with "no space left on device".

Increase memory for agent installer 4 and 5 node tests

---

agent/06_agent_create_cluster.sh
common.sh
config_example.sh

Add a new export - AGENT_OPERATORS - that can take a comma-separated list of operators. The operator list will be stored in a file and pushed to the rendezvous node when it is up so that it can be configured in assisted-service by the agent installer client.

AGENT-1127: Add ability to test operator configuration with ABI

---

agent/roles/manifests/templates/appliance-config_yaml.j2

The appliance now supports using a release image URL: https://github.com/openshift/appliance/pull/352
Hence, we can now use a nightly/ci release url in the ApplianceConfig template.
Also no need for 'imageRegistry' as the appliance now builds the registry internally: https://github.com/openshift/appliance/pull/349

agent: use release 'url' in ApplianceConfig

---

agent/05_agent_configure.sh
agent/07_agent_add_extraworker_nodes.sh

This patch fixes the typo inserted in the previous commit [9f27423](https://github.com/openshift-metal3/dev-scripts/commit/9f274238c53f0882844487cc5eb94f2b66e0bf9e) preventing the execution of the step 07 as expected

NO-ISSUE: fix extra worker step

---

agent/06_agent_create_cluster.sh
agent/gather.sh

The screenshots can aid in diagnosing issues in agent-tui. Currently they are saved in $OCP_DIR but aren't being archived by agent-gather.
Adds a screenshot after the bad_dns fix is applied to verify the dns configuration was changed correctly.

AGENT-1108: Gather console screenshots as part of agent-gather

---

agent/06_agent_create_cluster.sh
agent/e2e/agent-tui/test-fix-wrong-dns.sh
agent/e2e/agent-tui/utils.sh

- Moved utility functions ( to be reused for iso-builder) into agent/e2e/agent-tui/utils.sh
- No need to pass CLUSTER_NAME to test-fix-wrong-dns.sh as its a global var

NO-ISSUE: Code restructure

---

assisted_deployment.sh

With https://github.com/openshift/assisted-service/pull/3067 we have
introduced an `imageStorage` configuration option that needs to be set
in the AgentServiceConfig for Infrastructure Operator.
This PR adds the configuration, so that `make assisted` target can
deploy the operator seamlessly.
/cc @mresvanis

assisted-service: Add imageStorage to the service configuration

---

02_configure_host.sh

On subsequent runs this will fail because the link has already been created, but it still fails the -f test because it's a link not a file. Since we only care about existence and not the specific type of this file, let's just check for existence with -e instead.

Fix issue with OVMF_CODE.fd symlink

---

01_install_requirements.sh

ansible.utils just released a new version that is incompatible with ansible-2.15 (ansible-collections/ansible.utils@7059201) and this results in:
```
TASK [common : Show networks data for debugging (common role)] *****************
task path: /home/dev-scripts/metal3-dev-env/vm-setup/roles/common/tasks/main.yml:42
[WARNING]: Collection ansible.netcommon does not support Ansible version
2.15.12
[WARNING]: Collection ansible.utils does not support Ansible version 2.15.12
redirecting (type: filter) ansible.builtin.nthhost to ansible.netcommon.nthhost
redirecting (type: filter) ansible.builtin.nthhost to ansible.netcommon.nthhost
```
this is a proposal to pin these collections until we can upgrade to 2.16.

Pin collections to latest ansible 2.15 compatible versions

---

01_install_requirements.sh

Let's use ansible.utils<6.0.0 and ansible.netcommon<8.0.0 as ceiling so we can benefit from minor releases / bug fixes.

Relax pinned versions to use breaking ones as upper limits

---

agent/01_agent_requirements.sh
agent/03_agent_build_installer.sh
agent/04_agent_prepare_release.sh
agent/05_agent_configure.sh
agent/06_agent_create_cluster.sh
agent/agent_post_install_validation.sh
agent/common.sh
agent/e2e/agent-tui/automate-no-registry-agent-tui.sh
agent/e2e/agent-tui/test-fix-wrong-dns.sh
agent/e2e/agent-tui/utils.sh
common.sh
config_example.sh
ocp_cleanup.sh

Dev-scripts support to build OVE ISO 
- Reuse **`make agent`** target (instead of introducing a new one)
- Build agent OVE ISO
- Boot up the required VMs
- Set custom rendezvous node (Use **`AGENT_RENDEZVOUS_NODE_HOSTNAME`**) and auto-configure rendezvousIP via TUI
- Take TUI screenshots during install flow
- Verify that the assisted install web UI is running and accessible
- Increase VCPU allocation for certain operators requiring more resources
- Install required dependencies
- Set isolated network to true for truly disconnected OVE env
- Temporarily skip common steps not relevant for OVE ISO installs
- Temporarily skip generating unused manifests and config files
- Reclaim disk space by cleaning up cache and unnecessary files 
(Use `**AGENT_CLEANUP_ISO_BUILDER_CACHE_LOCAL_DEV**` for …

AGENT-1134: Dev-scripts support to build OVE ISO

---

agent/01_agent_requirements.sh

Early calling `write_pull_secret` causes an error`root/private-mirror-ostest.json: No such file or directory`
As like all other agent jobs, it should be correctly called through the configure step (02_configure_host)

NO-ISSUE: ISOBuilder

---

agent/01_agent_requirements.sh
agent/06_agent_create_cluster.sh

The `01_agent_requirements.sh` tries to extract `oc` binary much before its installed via `01_install_requirements.sh` causing the CI job to fail with `oc: command not found` error. This worked locally because we have `oc` installed.
Also, moved git clone agent-installer-utils into a more logical place `agent/06_agent_create_cluster.sh`

AGENT-1194: Fix premature oc extraction

---

agent/roles/manifests/templates/appliance-config_yaml.j2

Since 'version' is not wrapped with quotes, it's parsed as float. E.g. instead of '4.20', '4.2'.
Hence, recent 4.20 jobs fails with:
```
failed to load asset "Appliance Config": invalid Appliance Config configuration: ocpRelease.version: Invalid value: "4.2": OCP release version must be at least 4.14
```
See: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_appliance/379/pull-ci-openshift-appliance-master-e2e-sno-dualstack-dhcp/1918945229772165120

agent: Use string for ApplianceConfig.ocpRelease.version

---

agent/06_agent_create_cluster.sh

Creates dummy kubeconfig and kubeadmin password file in case of ISO_NO_REGISTRY to make CI happy.

AGENT-1196: OVE create dummy files

---

utils.sh

Two Node OpenShift with Fencing (TNF) is a deployment topology with two control-plane nodes that was introduce as a Dev Preview in OpenShift 4.19. This commit updates the logic around TNF to only render fencing credentials in releases 4.19 and up, and also the sslInsecure parameter so that it uses certificateVerification in 4.20 and up, as introduced in https://github.com/openshift/installer/pull/9640.

OCPEDGE-1825: [TNF] Reworked TNF logic to render fencing block conditionally.

---

agent/06_agent_create_cluster.sh

Delete the unused cache/temp directories to avoid storage overconsumption on the CI machine.

appliance: remove cache/temp dirs

---

01_install_requirements.sh

Restarting NM breaks VPN connections, which are required to build images for some OpenShift projects, notably machine-config-operator. Forcing a NetworkManager restart every time we update the node, even when no changes to the NetworkManager package were made, causes problems when working on patches to MCO.
This change checks the NM version before and after the dnf update and only restarts NM if the version changed.

Don't restart NetworkManager unnecessarily

---

agent/roles/manifests/templates/install-config_baremetal_yaml.j2

Changes made for a test got inadvertently introduced and broke the agent dual-stack tests.

Fix agent regression for dual-stack

---

README.md

I have noticed that the documentation regarding editing the hosts file for sshuttle is not working anymore. It turns out that the api endpoint is exposed on IP 192.168.111.5 not on 192.168.111.4.

NO-ISSUE: Move api hosts entry to its designated ip

---

config_example.sh
ocp_install_env.sh

added ability to specify a capability set and additional capabilities in the install config.

OCPEDGE-1734: feat: add ability to define capability set

---

agent/roles/manifests/templates/install-config_baremetal_yaml.j2

PR https://github.com/openshift-metal3/dev-scripts/pull/1757 introduced a formatting problem when using the agent-based installer with BMC configuration.

Fix regression in agent installer with BMC verify_ca

---

common.sh

Currently the OVE ISO size is slightly larger than the previous 40Gb, so bumping it to a greater value

NO-ISSUE: Bump AGENT_OVE_ISO_SIZE to 50Gb
