README.md
configure_host puts a bunch of stuff in /home/stack
regardless of who ran the script for now lets just
use that user.
=> Add note about requiring "stack" user

01_install_requirements.sh
`02_configure_host.sh` has a playbook which expects `stack` user to be present, so it should be created in `01_install_requirements`.
Not sure if this is an effective way to check that the user exists though
=> 01_install_requirements: add stack user

README.md
without a hint IPA defaults to the smallest disk it finds
that is above a certain threshold, in our case this is /dev/vdb,
it then boots from vda and fails. Force it to install on vda.
=> Add a root device hint to install the image on the first disk

tripleo-quickstart-config/roles/common/defaults/main.yml
If using virtio UDP checksums arn't calculated and some
versions of dhclient drop them as a result. This includes
the version in the cirros image we are using so change to
e1000 to avoid problems.
Patch untested but I think this is where to set it....
=> Switch the BM nics to e1000

05_run_ocp.sh, README.md, ironic/Dockerfile
Swap out our use of the cirros image for the RHCOS
image. Also needs more disk space on the bootstrap VM
the the image can be converted by ironic.
=> Deploy the RHCOS image

05_run_ocp.sh, common.sh, get_rhcos_image.sh, ironic/Dockerfile
Use an upstream location for the image download, and parameterize the docker build, which should make it easier to bump versions, and allows a fast local mirror for the 650MB qcow download :)
=> Image download updates

tripleo-quickstart-config/metalkube-nodes.yml
Currently we don't need these extra disks and they use up
space in the pool created in /home/stack - we can re-enable them
later (probably with smaller disk sizes) when we start testing with
storage.
=> Set extradisks:false

README.md
We're using iscsi deploy, which doesn't check a
checksum (direct deploy does), lets not mislead people.
=> Remove reference to image checksum

tripleo-quickstart-config/roles/common/defaults/main.yml
Now that we are no longer using cirros we don't need this,
and as the deploy time is a lot faster with virtio (local tests
show dd of image accross iscsi goes from 150sec to 80) we
should switch back.
This reverts commit e63b3553797aab0d85a3f77beb46c1e979a84569.
=> Revert "Switch the BM nics to e1000"

01_install_requirements.sh
My usual workflow is reserving a machine in Beaker which gives root login there. When the script is running as root (instead of stack) it needs access to stack's home directory, otherwise the VM won't start.
This PR ensures stack homedir has necessary permissions if its has not created previously
=> If there is no stack user make the ser directory readable

README.md, ironic/Dockerfile
For a single node this preforms a little better(about 2min45 vs
3min15 in a local env), but it should scale a lot better as it
offloads most of the work from the controller to the nodes being
deployed.
=> Switch to the "direct" deploy interface

03_ocp_repo_sync.sh
dev-scripts originates from github.com/imain/ocp-doit which targets
openshift 4.x installation on the openstack platform. This patch removes
some leftover repo sync that only slows down development.
=> stop syncing openstack specific integration

05_run_ocp.sh, README.md, ironic/Dockerfile, ironic/dnsmasq.conf, ironic/runironic.sh
This ensures that:
* bootstrap's dnsmasq allocates defined IPs for masters
* "external" DNS resolves these IPs to `<cluster-name>-etcd-<index>` name
* sets etcd discovery DNS entry
=> Set necessary DNS in dnsmasq config

ocp_cleanup.sh
* `cluster destroy` would fail as `images` pool is not used
* remove `ocp` directory so that a reinstall would work
=> cleanup: remove all ocp bits

05_deploy_bootstrap_vm.sh
Installer generates time-restricted certificates, so images should be downloaded earlier, so that installer assets won't expire
=> Pull RHCOS images earlier so that kubelet certs won't expire

01_install_requirements.sh, 02_configure_host.sh, 05_deploy_bootstrap_vm.sh, README.md, common.sh, config/environments/dev_privileged_libvirt.yml, libvirt_cleanup.sh, tripleo-quickstart-config/roles/common/defaults/main.yml
Using local user instead of user stack
This patch removes the need to create the user stack and just
uses a local user.
Instead of using the homedir, it creates a working-dir
/opt/dev-scripts to store temporary files.
Fixes #28
=> Using local user instead of user stack

ironic/Dockerfile, ironic/dnsmasq.conf, tripleo-quickstart-config/metalkube-nodes.yml, tripleo-quickstart-config/roles/libvirt/setup/overcloud/templates/ironic_nodes.json.j2
Allows us to boot the RHCOS image in a baremetal env (at least the one we've tested). The image boots but then fails to resolve ostest-api.test.metalkube.org. Which is better then we were.
Unfortunately the RDO IPA image has a bigger footprint, so needs a bump in RAM to fit the image download during deploy.
If merged this will require users to rerun the setup scripts from 02_...sh onwards
=> Bare metal support

01_install_requirements.sh, 05_deploy_bootstrap_vm.sh, README.md, ignition_patches/bootstrap/01_core_user_pass.json, utils.sh
This patch introduces a systematic way of patching ignition files and
provides a utility method for its usage.
All your patches to ignition files should follow jsonpatch rfc 6902.
You should place your patch json files in:
json_patches/kind_of_machine
Then, in the code that starts the machine, you should run:
apply_json_patches bootstrap "$IGN_FILE"
where bootstrap is the kind of machine from the possible:
- bootstrap
- masters
- workers
and IGN file is the ignition file that will be served to the machine via
PXE.
To run this, you should source utils.sh
=> Ignition patching system

05_deploy_bootstrap_vm.sh, pyxpath, utils.sh
This patch gets us ready for when we add more nets to the deployment by
only retrieving the IP of one specific libvirt network. We had to drop
domifaddr because it misbehaved when there's multiple nets.
=> bootstrap vm deployment: support multiple nets

utils.sh
There is a delay between the entry for a domain being created
in vibvirt and when the MAC entry appears in net-dhcp-leases (when
the host boots and does a dhcp request). We need to check the
entry has appeared before extracting it.
=> Check for MAC entrying in net-dhcp-leases before using it

02_configure_host.sh, 05_deploy_bootstrap_vm.sh
Restarting NetworkManager may cause network issues.
Better to reload instead.
=> Reload NetworkManager instead of restarting

01_install_requirements.sh, 05_deploy_bootstrap_vm.sh, ironic/dnsmasq.conf, ironic/dualboot.ipxe, ironic/inspector.ipxe
This gets the the ironic-inspector container and starts it. It also
changes the boot.ipxe file used for deployment to include
inspector.ipxe for introspection. If a deployment is not
being done, i.e. Ironic has not created a file in
/var/www/html/pxelinux.cfg/<MAC>, then the inspector.ipxe
file will be chainloaded to cause the IPA to run introspection
and return data to Ironic Inspector.
To access the Ironic Inspector API use:
export OS_TOKEN=fake-token
export OS_URL=http://ostest-api.test.metalkube.org:5050/
=> Download ironic-inspector container and allow introspection to run

06_deploy_masters.sh
We may fail in certain node states, and also we should wait for the
undeploy or the delete will fail.
=> 06_deploy_masters.sh wait for undeploy and tolerate failure

06_deploy_masters.sh, common.sh
Adding a valirable that if set is used as the root_device.
Making it possible to use a prepared instack.json. Previously
it was always trying to create one for libvirt based setup and
the MAC addresses in it didn't match the real ones on BM nodes.
=> Allowing root_disk and instack.json to be set in advance.

06_deploy_masters.sh
This ensures all masters are started in a rapid succession, which helps 
etcd cluster to assemble
=> Move master deploy to a different loop

ocp_cleanup.sh
We don't use "create cluster", so it doesn't really make sense to use the inverse openshift-install operation - it kinda works by luck because we name the bootstrap VM with the expected prefix, but we should probably just manually clean the things created via 05_deploy_bootstrap_vm.sh instead.
=> ocp_cleanup.sh - don't use openshift install to clean up

02_configure_host.sh, 05_deploy_bootstrap_vm.sh, README.md, common.sh, tripleo-quickstart-config/metalkube-setup-playbook.yml
When testing with real baremetal master/worker nodes we only
need the bootstrap VM, so we can disable some of the quickstart
roles by setting "NODES_PLATFORM" to something other than "libvirt"
which is the default.
NODES_FILE can also be overridden to point to your manually created
alternative to $WORKING_DIR/ironic_nodes.json (or you can just
copy it to that location).
This was created following conversation in https://github.com/metalkube/dev-scripts/pull/67
=> Allow disabling master/worker VMs for baremetal testing

01_install_requirements.sh, 05_deploy_bootstrap_vm.sh, utils.sh
etcd discovery container defaults to `eth0` interface to detect etcd IP and compare it with etcd SRV record.
This PR would pull MCS config, extract `etcd-member` k8s manifest, add `--if-name` argument to the container, pack it back and restart MCS to serve new ignition files to masters.
In the future this will be reverted and interface name would be a part of platform config, set in the installer. MCS would read this and automatically set `args` when assets are being generated
=> Edit interface name in master's etcd discovery

02_configure_host.sh
These are clogging up the top level directory and we
log all the scripts already (see common.sh), so we
don't need to do it a second time.
=> Stop directing ansible logs to file

02_configure_host.sh
We cannot assume the user running these scripts will be root.
=> Missing sudo

05_deploy_bootstrap_vm.sh, 06_deploy_masters.sh, common.sh
This should avoid confusion since instack is a legacy TripleO thing,
also make MASTER_NODES_FILE overridable so folks can do that
for baremetal testing as an alternative to NODES_FILE if they wish.
=> Rename instack to MASTER_NODES_FILE

05_deploy_bootstrap_vm.sh
Since 0.10.0, clusterID is no longer part of install-config.yaml
See openshift/installer#1057
=> Don't generate clusterID

host_cleanup.sh, ocp_cleanup.sh
This means we still clean things up if e.g the bootstrap VM is still
defined but not running.
=> Tolerate failure in *_cleanup.sh

06_deploy_bootstrap_vm.sh
Update to v1beta3 version. Remove everything except where we want to supply required information or override the defaults.
=> Update install-config 

04_setup_ironic.sh
This was failing for me, with a misleading "no route to host" error
from the IPA urllib code (the route was fine, but the firewall
blocked the port)
So, ensure we always open up this port for traffic over the brovc
bridge from the master/worker VMs to Ironic running on the host.
=> Add firewall rule to allow IPA access to Ironic API

utils.sh
even if the curl in wait_for_json fails the command returns success
as the "jq ." doesn't fail. This function presumably should be
running with pipefail set to work properly. Also add a sleep to
slow it down a bit.
=> Fix wait_for_json

06_deploy_bootstrap_vm.sh
We added this in when ironic was on the bootstrap node
so that images would fit. Ironic isn't running on the
bootstrap node any longer so we don't need this.
=> Remove the resize of the bootstrap image

ignition_patches/master/02_noneed_prov_nic.json
Having it there results in dracut attempting to dchp on boot.
This doesn't work and stalls the boot process once ironic is gone away.
=> Remove provisioning nic from the kernel command line

04_setup_ironic.sh, 07_deploy_masters.sh, common.sh
Create a link(redhat-coreos-maipo-latest.qcow2) pointing to the
the RHCOS image that we should be using. Also precalcualte the
md5sum of this image and expose it over http. This will allow
a client to reference the image to deploy and get its md5sum,
without having to download the data to calculate it.
=> Create link to the latest RHCOS image

ocp_cleanup.sh
This is helpful to avoid warnings when ssh is used manually
from the host to access the deployed nodes.
=> Cleanup ssh known hosts in host_cleanup.sh

01_install_requirements.sh
libguestfs-tools is required by the virt commands in 04_setup_ironic.sh
python-lxml is required by the pyxpath script
=> Install libguestfs-tools and python-lxml in 01_install_requirements.sh

README.md
The OS_URL value in the readme points to the OpenShift API not Ironic.
Signed-off-by: Doug Hellmann <dhellmann@redhat.com>
=> fix OS_URL in README

ocp_cleanup.sh
Some scripts access the cluster via the vip so we also need to clean
this to avoid ssh warnings when re-running the scripts
We may also want to clean this after the VIP fails over from the
bootstrap node, but I've not considered that in this patch
=> Also cleanup api ssh known_hosts entry

07_deploy_masters.sh
This allows us to print some helpful output with the node IPs
and also will work better when we eventually want to test
subsequent things on the deployed cluster
=> Wait for masters to become active/booted

06_deploy_bootstrap_vm.sh, 07_deploy_masters.sh, common.sh, utils.sh
I've seen the ssh to check if the master API is ready
(in 07_deploy_masters.sh) hang and have to be killed for the
script to move one, presumably this was something to do
with the VIP moving from the bootstrap node to the master.
Add a timeout to all ssh commands to prevent this from happening,
also create a common SSH env variable for all ssh commands.
=> Use ssh with ConnectTimeout=5

02_configure_host.sh
Open 3000/tcp and 8080/tcp on the host to allow access to Facet
backend and Yarn development server from remote locations, to aid
in remote development.
=> Open ports for Facet backend and Yarn development server

manifests/10_cnv_kubevirt_op.yaml, manifests/11_cnv_kubevirt_cr.yaml, manifests/12_cnv_kubevirt_config.yaml, manifests/README.cnv, manifests/README.md
This change adds the kubevirt manifests.
This is not all of the CNV manifests. But a start.
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>
=> manifests: Add CNV (kubevirt) manifests

07_deploy_masters.sh
Sometimes the status can be "deploy failed" and this
patch adds the check to catch it too. Otherwise the
checking loop doesn't end.
=> Adding check for failed string in status.

ocp_cleanup.sh
Some home dirs may be outside of `/home` (for instance root), so lets use `$HOME` instead
=> Fix ocp_cleanup to work for root user

02_configure_host.sh
We need to have port 69 open for reaching tftp
server during pxebooting. It's not always open.
=> Allowing access to tftp server.

ironic/inspector.ipxe
Including the extra-hardware flag when running introspection
collects additional data for disks, bios, nics, cpus, kernel etc.
=> Enable extra-hardware when running Ironic introspection

06_deploy_bootstrap_vm.sh
This would avoid printing a lot of lines when the script is waiting for bootstrap node to come up
=> Use ConnectionAttempts instead of while loop in bootstrap

ocp_cleanup.sh
This PR comes to apply a check prior to editing a file that may not exist,
which would cause the following error:
sed: can't read /home/stack/.ssh/known_hosts: No such file or directory
=> Ensuring the file to edit exists.

manifests/10_cnv_kubevirt_op.yaml, manifests/11_cnv_kubevirt_cr.yaml, manifests/12_cnv_kubevirt_config.yaml
There is an issue when posting manifests using `kubevirt` namespace. This is a
workaround for the issue that is meant to later be reverted when we understand
why `kubevirt` namespace is failing.
Related to issue #141
=> Switch to kube-system namespace for kubevirt manifests

04_setup_ironic.sh, host_cleanup.sh
My metalkube got into a weird state, and it couldn't clean up the Ironic containers.  Adding `-f` to podman commands fixed it.
This is the error I was getting:
```
732baa71d7665a696fee45f84b38d035fd3cd77b4fe01c26b882516f34c7ddc3
cannot remove container 732baa71d7665a696fee45f84b38d035fd3cd77b4fe01c26b882516f34c7ddc3 as it has active exec sessions: container state improper
```
=> Force remove Ironic containers

get_images.sh
Something broke in the image built from the tip of the rocky
branch (see https://bugs.launchpad.net/tripleo/+bug/1818554 for
details). This patch uses a fixed build that seems to work to avoid
having to chase issues with the build off of the tip of the branch.
Signed-off-by: Doug Hellmann <dhellmann@redhat.com>
=> switch to a fixed known-good IPA image

manifests/10_cnv_kubevirt_op.yaml, manifests/11_cnv_kubevirt_cr.yaml, manifests/12_cnv_kubevirt_config.yaml
Subsequent discussion indicates this isn't the right approach, and that
we instead need to fix the manifest ordering, and/or use a temporary
script that runs after the cluster is fully deployed.
This reverts commit a52d2b31ae239becee39f2c882601d55801efd19.
=> Revert "Switch to kube-system namespace for kubevirt manifests"

manifests/120_cni_plugins.yaml, manifests/121_sriovdp.yaml, manifests/122_sriov_crd.yaml, manifests/123_sriov_cni.yaml, manifests/124_ovs_cni.yaml, manifests/README_cnv.md
These are network plugins installed by kubevirt-ansible.
OVS CNI pod needed adjustment in line with
https://github.com/kubevirt/ovs-cni/pull/70 to be able to create ovs-vsctl
executable on CoreOS.
=> Install additional CNI / device network plugins

01_install_requirements.sh
Install 4.0.22 and make it easier to update the version to newer
releases later.
Signed-off-by: Doug Hellmann <dhellmann@redhat.com>
=> use a more recent version of openshift client

07_deploy_masters.sh
Since we don't deploy workers yet, to do anything meaningful with the cluster
right now requires untainting master nodes for scheduling pods. This change
makes it part of automated deployment to save a manual step.
=> Remove NoSchedule taints from masters

02_configure_host.sh
The checks for existing iptables rules produces output at the end of this
script that makes it look like some failures occurred.  Since these are
expected and handled gracefully, send the error output to /dev/null.
Signed-off-by: Russell Bryant <rbryant@redhat.com>
=> 02: Clean up some expected error output.

ocp_install_env.sh
To unblock testing use this temporary build, we'll switch back to
the latest images when https://github.com/openshift/machine-api-operator/pull/246
lands
=> Use temporary images to workaround machine-api/cvo failure

06_deploy_bootstrap_vm.sh, utils.sh
The if-name for etc discovery is no longer required because of:
https://github.com/openshift/machine-config-operator/pull/547
=>  Remove if-name for etc discovery

01_install_requirements.sh, 03_ocp_repo_sync.sh, 05_build_ocp_installer.sh, 07_deploy_masters.sh, Makefile, masters_cleanup.sh, utils.sh
Install terraform and terraform-provider-ironic. Add a script that you can use to experiment with using terraform to deploy the masters after 07_deploy_masters.sh exits early.
This uses the unmerged code in metalkube/terraform-provider-ironic#2
---
TODO list before merging:
=> Use terraform to install the masters

masters_cleanup.sh
This failed if the directory didn't exist
=> Only cleanup ocp/tf-master if its there

machineconfig/master/spec/config/storage/files/haproxy.cfg.template L2V0Yy9oYXByb3h5L2hhcHJveHkuY2ZnLnRlbXBsYXRlCg==, machineconfig/master/spec/config/storage/files/haproxy.sh L3Zhci91c3Jsb2NhbC9iaW4vaGFwcm94eS5zaAo=, machineconfig/master/spec/config/storage/files/members_healthcheck.sh L2V0Yy9oYXByb3h5L21lbWJlcnNfaGVhbHRoY2hlY2suc2gK, machineconfig/master/spec/config/systemd/units/masters_haproxy.service.envsubst
This commit creates LB for OCP API, and load balances the
API traffic across all masters.
Comment#1: Because this LB runs on the master machine and OCP
API listen on API port (6443) on all interfaces, it's
required to allocate a new port that will be used as the
LB frontend (7443).
Comment#2: current implementation doesn't take into consideration the
VRRP status and LBs created on all the masters.
=> Add self-hosted OCP API Loadbalancer

machineconfig/master/spec/config/storage/files/check_ocp_api.sh L2V0Yy9rZWVwYWxpdmVkL2NoZWNrX29jcF9hcGkuc2gK, machineconfig/master/spec/config/storage/files/keepalived.conf.template L2V0Yy9rZWVwYWxpdmVkL2tlZXBhbGl2ZWQuY29uZi50ZW1wbGF0ZQo=, machineconfig/master/spec/config/storage/files/keepalived.sh L3Vzci9sb2NhbC9iaW4va2VlcGFsaXZlZC5zaAo=, machineconfig/master/spec/config/systemd/units/keepalived.service.envsubst
Some services do not yet handle well the VIPs being in the same
interface as the DHCP acquired address. While that happens, let hold the
VIPs in macvlan devices.
We should probably move back once the services deal with it better.
=> keepalived: prepare for multiple VIPs

Makefile
"all" is a typical name for the default make target, so add it as an
alias for "default".  Then I can happily run "make clean all".
=> Makefile: Add all target.

utils.sh
This patch makes it possible to ignore ipmi_port,
that's not needed for BM nodes.
=> ipmi_port is redundant on BM setup

07_deploy_masters.sh
We provide the root disk via common.sh, use this instead of defining
a new var.
=> Use ROOT_DISK

09_deploy_manifests.sh
We expect this to be handled via kni-installer but there were
issues with that ref #127 so lets just apply them via a script
for now, which is probably easier for test/dev workflows anyway.
=> Add script to deploy extra manifests

07_deploy_masters.sh, utils.sh
There is no need to repeat oc commands - it has `oc wait` subcommands which pauses until a particular `.status.condition` is set to True.
There is no `oc wait` for events, so this would run `oc get events` in a loop and look for `bootstrap-complete` event instead. Loop is limited to 60 attempts with 10 sec pause so bootstrapping is expected to complete in 10+ minutes.
If the cluster didn't start the script would output:
1. bootstrap.service logs
2. clusterversion operator status
3. operator status
4. List of failing pods
=> Use `oc wait` to wait for condition instead of running oc commands

fix_certs.sh
We shouldn't need this for very long, but to save everyone the effort
of keeping track of the command that needs to be run here's a script.
=> add a script to approve the certs after they expire

assets/templates/99_master-core-password.yaml
Fixes MCO complaining about wrong syntax in MachineConfiguration:
`
E0320 15:18:48.047943       1 reflector.go:134] github.com/openshift/machine-config-operator/pkg/generated/informers/externalversions/factory.go:101: Failed to list *v1.MachineConfig: v1.MachineConfigList.Items: []v1.MachineConfig: v1.MachineConfig.Spec: v1.MachineConfigSpec.Config: types.Config.Passwd: types.Passwd.Users: []types.PasswdUser: types.PasswdUser.PasswordHash: ReadString: expects " or n, but found [, error found in #10 byte of ...|ordHash":["$6$2Cy8We|..., bigger context ...|"passwd":{"users":[{"name":"core","passwordHash":["$6$2Cy8WeZ7uGbJ4qEv$vS8zP0HvbhtOTfu72JMoYIxm3Zb5T|...
`
=> Fix passwordHash syntax

ocp_install_env.sh
machine-api now supports baremetal, use latest built release payload.
Depends on https://github.com/openshift-metalkube/kni-installer/pull/22
=> Use latest release image

utils.sh
This can fail due to timeout, e.g when the VIP fails over or of
the API is overloaded, in this case we should retry but we
won't if the parent script has set -e
=> Tolerate get events failure

assets/files/usr/local/bin/haproxy.sh
Now that we use internal haproxy httpchk, we do not need the custom
image we made.
=> api-haproxy: change to docker library haproxy img

08_deploy_bmo.sh
The role binding is needed to give the operator permission, so we
should wait to launch the operator after the role binding is there.
=> set up the role binding before launching metalkube baremetal operator

08_deploy_bmo.sh
Change the sed pattern so we do not rely on what the current namespace
is, only on the fact that we are changing the namespace line. This
allows us to change the name we use when deploying on stock
kubernetes.
=> be more resilient when changing the namespace for the bmo

common.sh
When running the scripts as a user, the creation of the WORKING_DIR fail as it try to create it under /opt as a simple user.
Simply added sudo to make the mkdir and chown commands work correctly.
=> Add sudo for working_dir creation

04_setup_ironic.sh, assets/files/usr/local/bin/rm-provision-nic.sh
sed needs to be told to follow a simlink to prevent it
from converting a softlink to a regular file. Converting
it to a regular file meant when pivot created a new grub.cfg
we were no longer pointing at it and as a result we attempting
to switch roots into the old ostree.
Also make sure the baremetal network is the one mentioned in
/etc/default/grub so its correct if grub.cfg is regenerated.
=> Fix the boot device hacks to follow symlinks

common.sh
tripleo scripts recommend using a non-root user, but dev-scripts work perfectly as a root. Also using root simplifies testing w/ Beaker machines
This reverts a part of #186
=> Allow to use root user

assets/files/etc/NetworkManager/dispatcher.d/pre-up.d/dns-vip-prepender, assets/templates/99_master-dhclient-dns.yaml, assets/templates/99_worker-dhclient-dns.yaml
Cri-O and other service start after network-online.target.
dns-vip-prepender was being triggered by the NetworkManger dispatcher in
the "up" state, which happens right at network-online.target.
This means that if some service that ran after network-online target
needs CoreDNS mDNS resolution it may not get it depends on what happened
earlier. In order to address that, we move the dispatcher script to
"pre-up" which is strictly before NM desclares network-online.target as
achieved.
=> dns-vip-prepender: Prevent race with crio

06_deploy_bootstrap_vm.sh, common.sh
There may be situation where the SSH service on the bootstrap VM
takes longer to start. This change makes it configurable.
=> Make the time to wait for bootstrap VM SSH configurable

ocp_install_env.sh
There was an old reference to openshift/installer that if not replaced
would make builds fail on environments in which openshift/installer was
not in GOPATH
=> ocp_install_env: Refer to kni-installer

07_deploy_masters.sh, utils.sh
I think some of these were missed in a rebase between #177 and #130
There are a few other places --config is used, but currently those
don't source common.sh, so I've left them alone for now.
=> Remove some remaining --config references

02_configure_host.sh
When adding the user to the libvirt group for the first time we need
to restart the libvirtd service so it loads the new group membership
and allow the subsequent virsh pool commands to run without error.
=> Restart libvirtd service after adding user to libvirt group

assets/templates/99_master-coredns.yaml, assets/templates/99_master-keepalived.yaml, assets/templates/99_master-mdns-publisher.yaml, assets/templates/99_worker-coredns.yaml, assets/templates/99_worker-mdns-publisher.yaml
When testing that with a slow connection, the services keep
restarting because they don't have enough time to download the
content. Increasing the timeout to, at least 10 minutes, ensures
that will work on more environments.
=> Increase timeout for services that download content

run_ci.sh
To ease debugging CI problems add a hook in which
CI logs can be retrieved. The jenkins job has been
updated to grab files in $LOGDIR.
=> Add a hook for grabbing CI aritfacts

07_deploy_masters.sh, utils.sh
ep/host-etcd of the kube-system namespace is watched by the
cluster-kube-apiserver-operator to update storageConfig.urls.
Without this, errors such as the following are normal:
```W0328 12:54:56.070253       1 clientconn.go:944] grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp: lookup etcd-0.dev1.kni.lab.eng.bos.redhat.com on 10.19.130.14:53: no such host"; Reconnecting to {etcd-0.dev1.kni.lab.eng.bos.redhat.com:2379 0  <nil>}```
=> baremetal: patch kube-system host-etcd real info

06_deploy_bootstrap_vm.sh, ocp_cleanup.sh
Users may have custom variables set in config_<user>.sh
If they have a custom CLUSTER_NAME or BASE_DOMAIN, we need
to set these first, before the defaults are used to set
CLUSTER_DOMAIN in ocp_install_env.sh.
=> Always source common.sh first

host_cleanup.sh
There was a bug in this file previously, and it apparently doesn't
get updated properly. Remove the file during host cleanup so it will
be re-created correctly.
=> Remove ifcfg-provisioning during host_cleanup

tripleo-quickstart-config/metalkube-nodes.yml, tripleo-quickstart-config/roles/libvirt/defaults/main.yml, utils.sh
This is required for enabling extra disks, e.g for rook/ceph
This also enables an extra disk so we can prove this works
and support testing with ceph/rook.
Note this requires https://github.com/openshift-metalkube/terraform-provider-ironic/pull/10
=> Enable extradisks and add root_device to ironic nodes

02_configure_host.sh, 06_deploy_bootstrap_vm.sh
To avoid losing network connectivity when bridging the physical interface
to the baremetal bridge we can use systemctl restart network. This is
useful for persisting the SSH connection when automating the deployment.
Also when the baremetal bridge is not managed by libvirt the provsioning host
uses the external DNS server for name resolution. This change sets the
condition so NetworkManager dnsmasq gets used only when the baremetal bridge
is managed by libvirt.
=> Restart network service instead of ifdown to avoid losing connectivity

utils.sh
Using the variable for root_disk that was
set by the user in config_${USER}.sh file.
=> root_disk shouldn't be hardcoded

06_deploy_bootstrap_vm.sh, 07_deploy_masters.sh, assets/files/etc/keepalived/keepalived.conf.template, assets/files/usr/local/bin/keepalived.sh, tripleo-quickstart-config/roles/common/defaults/main.yml, tripleo-quickstart-config/roles/environment/setup/templates/network.xml.j2
For the Openshift router support, the router pods will run on
masters-nodes (host networking).
This patch adds support for the Ingress VIP(192.168.111.4), one
of the master nodes will hold this IP (VRRP), creates wildcard
external DNS entry pointing to Ingress VIP and adds e2e verifictation test.
Co-authored-by: Antoni Segura Puimedon <antoni@redhat.com>
=> Add support for Ingress VIP

run_ci.sh
The jenkins job times out after 90 minutes, we need to
also timeout the "make" command so it times out before
jenkins and there is time to grab the logs.
=> Set timeout on CI run

common.sh
RHEL's VERSION_ID is set to 7.X versus just 7 for CentOS,  cut after the '.' if it exist.
=>  Address issue #277

assets/templates/99_registry.yaml
This makes image-registry operator pass. In the prod version Rook should be deployed first to avoid using emptyDir for registry.
Once Rook code is finalized this config should be updated
=> Set volumeSource to emptyDir in image-registry operator

02_configure_host.sh, common.sh, host_cleanup.sh
Create 2 new vars MANAGE_PRO_BRIDGE and MANAGE_INT_BRIDGE. If those
are set to n, the scripts won't try to recreate the bridges, but
leave the ones that are already created on the host.
This is useful for specific configurations where settings
cannot be overwritten.
=> Add the possibility of not managing bridges

06_create_cluster.sh
Master is master and worker is worker, and never the twain shall meet.
This seems to confuse MCD and when `worker` label is found it attempts to reconfigure masters as workers in-flight. See https://github.com/openshift/machine-config-operator/pull/575
=> Don't labels as workers - this confuses MCD

06_create_cluster.sh, utils.sh
This would use kni-installer's subcommand which waits for all operators to rollout.
Requires #262 to make image-registry rollout properly
=> Use `upi finish` subcommand

make-bm-worker/README.md, make-bm-worker/main.go
Add a version of the tool for making a baremetal worker that knows
how to set the image properties to trigger provisioning immediately.
=> add custom version of make-bm-worker

04_setup_ironic.sh, host_cleanup.sh
This change also address the need to generate a random password
for the database user and pass it to both mariadb and
ironic container.
Relates to:
https://github.com/metalkube/metalkube-ironic/pull/23
=> Separating mariadb container

02_configure_host.sh, 06_create_cluster.sh, host_cleanup.sh
After destroying and re-creating the libvirt network
need to bring UP the NIC that's attached to the bridge.
=> Bringing UP the INT_IF NIC

01_install_requirements.sh, 03_ocp_repo_sync.sh, run_ci.sh, utils.sh
Because the provider is now vendored in the installer, we don't need
to sync it or deal with the terraform-provider-ironic repo in any direct
way. CI testing only needs to happen when the provider gets updated in
kni-installer.
This also enable debug logging for terraform.
=> Clean-ups after move to kni-installer for masters

assets/files/etc/kubernetes/manifests/coredns.yaml, assets/files/etc/kubernetes/manifests/keepalived.yaml, assets/files/etc/kubernetes/manifests/mdns-publisher.yaml, assets/files/etc/kubernetes/static-pod-resources/coredns/Corefile.template, assets/files/etc/kubernetes/static-pod-resources/keepalived/keepalived.conf.template
When moved to static pods, we also moved the dns health check to happen
in the keepalived conf instead of a separate script. The issue was that
even though it needs CLUSTER_DOMAIN, we were not exporting it before
using python to expand the keepalived.conf template.
Fixes #320
=> fix missing cluster_domain in keepalived rendering

08_deploy_bmo.sh
The operator won't work until the CRD is installed, so switch the
order of the two calls.
=> launch bmo after installing its crd

utils.sh
With the latest rebase (https://github.com/openshift-metalkube/kni-installer/pull/42), upi has been renamed to wait-for
=> 'upi finish' has been renamed to ''wait-for cluster-ready'

assets/files/etc/kubernetes/manifests/keepalived.yaml, assets/files/etc/kubernetes/static-pod-resources/keepalived/keepalived.conf.template, assets/files/usr/local/bin/fletcher8, assets/templates/99_master-utils.yaml
In order to enable multiple clusters in the same broadcast domain we
must make sure that the VRRP IP management of the different clusters
don't end up mixing up.
=> keepalived: include cluster name in instance, pass

11_register_hosts.sh, make-bm-worker/main.go
Add an optional step 11 to register hosts for the masters and workers.
Masters are registered with a machine reference, to prevent them from
showing up as available to be provisioned.
Workers are registered without a machine reference, so they are
available to be provisioned.
Add the missing machine and boot-mac arguments to make-bm-workers.
=> add a script to register hosts

assets/files/etc/NetworkManager/dispatcher.d/pre-up.d/dns-vip-prepender
Initially when the system is started, resolv.conf has some dummy resolv.conf
coming from the tree. When dns-vip-prepender is called the first time, it tries
to use that buggy nameserver and captures the error code of the dig command,
causing to set an incorrect nameserver. This patch changes dig for host, to
better capture error codes, and don't perform any action on resolv.conf if
nameserver cannot be resolved properly.
=> Add sanity check when getting VIP for nameserver

02_configure_host.sh, tripleo-quickstart-config/metalkube-nodes.yml
Add a VM_NODES_FILE variable, so that you can copy and modify
the metalkube-nodes.yml ansible vars file if desired (e.g to add
extra memory, or test with more/less nodes)
e.g
cp tripleo-quickstart-config/metalkube-nodes.yml ~
vim ~/metalkube-nodes.yml
echo "export VM_NODES_FILE=\"/home/$USER/metalkube-nodes.yml\"" >> config_$USER.sh
Proceed with caution if modifying this file, as the most well tested path
is using the defaults.
=> Make VM node specs configurable and bump defaults

common.sh
Rather than using the latest build of RHCOS, use the version that the installer pins to.
Fixes #287 and #347
=> Use the installer pinned rhcos version

11_register_hosts.sh
For IPMI systems where the port is the default, don't force the user
to specify one.
Fixes #345
=> handle missing ipmi port

extras/kafka-dashboards/dashboard-template.sh, extras/kafka-dashboards/strimzi-kafka.json, extras/kafka-dashboards/strimzi-zookeeper.json, extras/kafka.sh
This PR adds a new Kafka Grafana dashboard with some new rates metrics views.
@jparrill tbh I wasn't able to test it locally. Can you do that?
=> Added updated Grafana dashboards

run_ci.sh
This fixes an issue introduced via https://github.com/openshift-metalkube/dev-scripts/pull/359
Because `run_ci.sh` sources common.sh before running `01_install_requirements.sh` we have to install golang or we fail to source the GOPATH that's needed to get the latest version.
That does also raise the issue of whether we should calculate this after running `03_ocp_repo_sync.sh` but this seems to unblock CI for now
=> Fix issue creating FILESTOCACHE in run_ci.sh

ocp_install_env.sh
We now only create 1 worker VM, so specify the number of workers as 1
instead of the default of 3.
=> Specify master and worker counts in install-config.

01_install_requirements.sh, 06_create_cluster.sh, ocp_install_env.sh, utils.sh
See: https://github.com/openshift/installer/pull/1622
This can be dropped once kni-installer includes the above change.
The previous v4.0 tag we were using stopped getting updates, so this change is the equivalent of what we were using before.  Note that v4.0 and v4.1 don't have major functional differences other than the week or so of time since v4.0 got updated.  They're both still chasing master at the moment.
=> Switch to pinned release of OpenShift

assets/files/etc/kubernetes/static-pod-resources/coredns/Corefile.template
We added this to prevent individual etcd nodes from clustering with
only themselves, but etcd can cluster correctly with only 2 nodes.
=> Lower SRV record limit to 2

assets/files/etc/kubernetes/manifests/coredns.yaml
CLUSTER_DOMAIN was removed in 8474c871f3904c11d76ca1ac65997a5c4a3c29a5
but this reference wasn't updated. As a result, we've been querying
for "ns1." when starting coredns. This seems to work fine in my
virt environment, but I just debugged a system where that was
resulting in an empty DNS_VIP. This caused coredns to crash if it
tried to forward a query because there was nothing in resolv.conf.
The grep -v "" removed all lines, not just the one we wanted.
=> Reference correct domain env var

08_deploy_bmo.sh
This is a workaround for
https://github.com/metalkube/cluster-api-provider-baremetal/issues/57
The machine-controller currently requires that the BareMetalHost CRD
is defined before it starts up.  We'll fix this, but short term,
bounce the machine-controller after launching the baremetal-operator
and defining the BareMetalHost CRD in the cluster.
=> Restart machine-controller after deploying baremetal-operator.

03_ocp_repo_sync.sh, 10_deploy_rook.sh
For the Storage Console and Prometheus based Monitoring to work on top of OCP, there are few restrictions that needs to be addressed. This PR addresses those and adds Storage Monitoring feature to the stack.
Changes: 
1. Rook + Ceph cluster is installed in the openshift-storage namespace.
2. Service Monitor is added to openshift-storage namespace.
3. Prometheus Rule file is applied from the ceph-mixins project to enable alerting.
Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>
=> Modifying Rook Installation & Adding Storage Monitoring Components

assets/files/etc/kubernetes/manifests/keepalived.yaml, assets/files/etc/kubernetes/static-pod-resources/keepalived/keepalived.conf.template
This is a temporary solution to workaround the extra host route, 
It changes VIPs netmask to the master subnet netmask.
I set it as [WIP] since I didn't test it yet.
=> Workaround to avoid the affect of the undeleted routes for API, DNS and INGRESS VIPs

08_deploy_bmo.sh
Currently scale commands fail:
```shell
00:51:31         "2019-04-18 00:51:30 | + oc scale deployment -n openshift-machine-api machine-api-controllers --replicas=0", 
00:51:31         "2019-04-18 00:51:30 | error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:", 
00:51:31         "2019-04-18 00:51:30 | ", 
00:51:31         "2019-04-18 00:51:30 |   1. Via the command-line flag --config", 
00:51:31         "2019-04-18 00:51:30 |   2. Via the KUBECONFIG environment variable", 
00:51:31         "2019-04-18 00:51:30 |   3. In your home directory as ~/.kube/config", 
00:51:31         "2019-04-18 00:51:30 | ", 
00:51:31         "2019-04-18 00:51:30 | To view or setup config directly use the 'config' command."
```
=> Add missing config option to oc scale commands

manifests/8_cnv_cdi_operator.yaml
1.8 is intended to be the stable release for the demo.  Also, 1.6 has a pretty bad bug causing the controller to crash.
=> update KubeVirt CDI version

common.sh, tripleo-quickstart-config/roles/libvirt/defaults/main.yml, tripleo-quickstart-config/roles/libvirt/setup/overcloud/templates/baremetalvm.xml.j2
Avoid disk naming differences between VM and baremetal by using virtio-scsi devices.
=> Switch to using virtio-scsi for VM disks

Makefile
Automatic provisioning of a worker node should now be working, so add
it to the default Makefile target.
=> Makefile: Provision worker by default.

11_register_hosts.sh
The default worker wait timeout of 30s isn't sufficient while waiting for the node
to shut down, power cycle, and come back up before joining the cluster, particularly
in virtual environments where there are CPU, disk, or memory contensions.  Increase
the timeout to something more accommodating.
=> Increase the worker wait timeout

add-machine-ips.sh, link-machine-and-node.sh
Retain add-machine-ips.sh but add another script that just takes the
machine and node names so in baremetal environments where the naming
conventions do not hold we can link them explicitly.
=> add a separate script for linking machine and node

11_register_hosts.sh
Use the CLUSTER_NAME variable to pick the names of the machines
instead of hard-coding "ostest" as the prefix.
=> do not hard-code cluster name in machine names

common.sh, utils.sh
Using "name" isn't reliable on baremetal as device
name can swap from one deploy to anopther, causing
boot failures as the image gets written to the wronge
drive.
To use another root device hint in place of "name"
a deploy can set
export ROOT_DISK_NAME=
export ROOT_DISK_HCTL=0:0:0:0
=> Support additional root device hints

docs/custom-mao-and-capbm.md
It  might be a new behavior that CVO is doing this. Two of us today saw CVO
fighting us over the replicas number.
=> prevents CVO from scaling MAO back up when you are trying to run a local MAO

03_ocp_repo_sync.sh, 08_deploy_bmo.sh
Use the metalkube name instead of the metal3-io name for now. Another
patch will update the scripts to work with master form metal3-io again.
=> have dev-scripts pin the baremetal-operator

03_ocp_repo_sync.sh, 08_deploy_bmo.sh
Use a branch name for the image tag instead of a git tag so that if we
add changes on the branch we get new images automatically.
=> use metalkube branch instead of before-rename tag for baremetal operator

03_ocp_repo_sync.sh
Make sure to fetch all branches.  This will ensure an existing setup
gets the new `metalkube` branch.
Also explicitly checkout the remote `metalkube` branch, as this script
already creates a local metalkube branch in every repo for applying
any patches that are needed.
=> Fix switching to baremetal-operator metalkube branch.

11_register_hosts.sh
In order to avoid issue #421 run add-machine-ips.sh only when a single worker node is registered.
=> Run add-machine-ips.sh only with single worker deployments

11_register_hosts.sh
We automate waiting for a worker to come up and adding IPs to it for the
default virt configuration.  This is a helpful step for the common dev setup,
and it also runs in CI. For any other env, we just skip this, because we
can't automatically figure out the mapping between Machines and Nodes in
other cases, and must rely on running the link-machine-and-node.sh manually.
Related issues: #421 and #417
=> Only wait for worker-0 in the default virt config.

manifests/100_cnv_kubevirt_op.yaml
Update to kubevirt 0.16.1. This brings two fixes:
* Ensure that VMI Pods are protected during the whole migration on drains
* Allow disabling save-migration checks in libvirt. This allows to work around situations where libvirt does not properly recognise disks as migrateable, during development and testing.
=> Update to kubevirt 0.16.1

assets/files/etc/kubernetes/manifests/coredns.yaml, assets/files/etc/kubernetes/manifests/haproxy.yaml, assets/files/etc/kubernetes/manifests/keepalived.yaml, assets/files/etc/kubernetes/manifests/mdns-publisher-worker.yaml, assets/files/etc/kubernetes/manifests/mdns-publisher.yaml
Only pods in kube-system or openshift-* namespaces can be marked as
system-node-critical. This patch adapts us to that reality.
Fixes #371
=> Add openshift prefix to kni infra namespace

03_ocp_repo_sync.sh
dep requires $GOBIN to exist before it will install.  Previously it was
implicitly created by some go things we installed.  Disabling facet
changed that, so let's create it explicitly.
=> mkdir ~/go/bin before installing dep

extras/02_kafka.sh
The 0.11.2 version of Strimzi has 1G as default PVC size instead of 100 like master branch has. Changing it here.
=> Fix: chaging PVC for strimzi 0.11.2 version

host_cleanup.sh
We already delete ifcfg-provisioning because of a previous bug, but
leaving the ifcfg-baremetal file is causing problems such as #375.
Deleting this file too when we do host cleanup avoids the problem.
=> Delete ifcfg-baremetal too

Makefile
Makefiles require the use of tabs. The spaces in this target cause
the following error:
Makefile:36: *** missing separator.  Stop.
=> Use tabs for indentation in ironic_cleanup

extras/02_kafka.sh
In order to avoid error in kafka deployment because of ceph storage, I've added a function to stop the deployment of kafka if ceph has no the pool that must create the operator based on the cephblockpool.ceph.rook.io CR.
=> Feat: Added function to kafka script to check if ceph pool exists

manifests/100_cnv_kubevirt_op.yaml
The kubevirt operator is now more resilient in case that the discovery client can't fully resolve the host resources. Before this release, it was enough that one aggregated apiserver from extension is offline to block the kubevirt operator.
=> Update to kubevirt 0.16.2

assets/templates/99_openshift-kni-infra-namespace.yaml
Namespace 'openshift-kni-infra' doesn't exists.
```
$ oc get project openshift-kni-infra
Error from server (NotFound): namespaces "openshift-kni-infra" not found
$ oc get namespace openshift-kni-infra
Error from server (NotFound): namespaces "openshift-kni-infra" not found
```
=> Add 'openshift-kni-infra' namespace during install

assets/files/etc/kubernetes/manifests/mdns-publisher-worker.yaml, assets/templates/99_worker-mdns-publisher.yaml
This PR addresses two issues with the mdns-publisher-worker-0 pod:
1. add the missing `/usr/local/bin/get_vip_subnet_cidr` on the host
2. use the correct template in the render-config initContainer
With these commits and #453 the mdns-publisher-worker-0 pod in the openshift-kni-infra namespace gets into Running state.
Updates: #458
=> Fix worker mdns-publisher-worker-0 pod failures

make-bm-worker/README.md
When creating a baremetalhost it's necessary to specify this namespace
despite it being in the yaml metadata, otherwise the node won't be
seen by the actuator/operator.
=> Add -n openshift-machine-api to oc apply for baremetalhost

10_deploy_rook.sh
This is a workaround until https://github.com/ceph/ceph/pull/27876
merges and makes it into the ceph build. It makes the mgr make aggressive
pgp_num changes so that the ceph health settles quickly after adjusting
the pg_num for new pools.
We can remove this later once the above ceph fixes are in place.
Signed-off-by: Sage Weil <sage@redhat.com>
=> 10_deploy_rook.sh: set mgr_debug_aggressive_pg_num_changes during setup

assets/files/etc/kubernetes/manifests/haproxy.yaml
The haproxy-monitor container tries to configure routes by executing
`iptables` commands from the host through a `chroot /host` environment.
Without the /host volume mapped to / on the host, these commands fail
and the haproxy-monitor container fails to start.
Note that this depends on #453 before the pods can be deployed.
Closes: #456
=> haproxy: add /host volume to run commands on the host through chroot

01_install_requirements.sh
If you run this script on a system that already has selinux disabled
via config, setenforce will return non-zero and cause this script to
fail.  Check to see if selinux is enabled first to avoid this problem.
=> Only change selinux if needed.

01_install_requirements.sh, 02_configure_host.sh
Everything else in the install_requirements script is installing
software.  Creating ssh keys seems to fit better in the configure_host
step.
=> Move ssh key generation to configure_host.

manifests/100_cnv_kubevirt_op.yaml
Adds support to detect aggregated apiserver CA rotations.
=> Update to kubevirt 0.16.3

assets/files/etc/kubernetes/static-pod-resources/coredns/Corefile.template
Keepalived health for the coredns-mdns VIP is determined from being able
to give out Etcd records. The problem with that is that if some master
goes down, we are, by definition, not able to give out the total amount
of masters, which is the minimum that used to be set before we moved it
to 2. The reason why it used to be TOTAL_AMOUNT_OF_MASTERS was because
that is the right setting at the bootstrap stage and we were moving the
DNS VIP to the masters as soon as possible.
With this change and a companion one in kni-installer, we keep the
TOTAL_AMOUNT_OF_MASTERS, but only in the bootstrap keepalived
configuration. Once the cluster is formed and the bootstrap node is
taken down, the masters will run coredns-mdns without the
TOTAL_AMOUNT_OF_MASTERS restriction when responding to etcd SRV …
=> coredns-mdns: masters to always return SRV entries

10_deploy_rook.sh
'oc create' commands may take more than 360s to complete.  Subsequent 'oc wait' commands
waiting for the condition of a pod being ready based on the 'oc create' command may
time out before completing, failing deployments.  The 'oc wait' command is a polling
operation, not a blocking operation.  Increasing this value should have no significant
impact on deployment time because as soon as the condition is met, the command returns.
=> Increase oc wait timeout, again

02_configure_host.sh
The iptables configuration is now done in the individual containers where the services are started, it can be removed from the script.
=> Remove unneeded iptables configuration

.mailmap
I needed a list of all the Red Hat employees that have contributed to
the various metal3 related repos so far.  This file helps get a
sanitized list.
=> Create .mailmap file.

assets/files/etc/kubernetes/static-pod-resources/haproxy/utils.sh
The haproxy static pod should verify the existence of an iptable
rule redirects traffic from OCP API to API LB frontend.
Sometimes Haproxy pod creates wrongly multiple instances of this rule
because it fails to read the current iptables rule list
(Another app is currently holding the xtables lock).
This patch increases the wait time for iptable lock to 10 seconds in
haproxy pod.
=> Haproxy API LB - increase iptables lock wait timeout

assets/files/usr/local/bin/clusterinfo, assets/templates/99_worker-utils.yaml
clusterinfo is used to set the DNS VIP in collaboration with
NetworkManager's dhclient. The problem is that it was missing in workers
and, on top of that, it was retrieving the cluster name from
kubeconfig's cluster-name, which on the worker nodes is just "local".
This patch fixes both things.
Signed-off-by: Antoni Segura Puimedon <antoni@redhat.com>
=> FIx clusterinfo to work in worker nodes

vm_setup_vars.yml
These have been removed from metal3-dev-env so we need to set
them here
=> Add VIP DNS entries to vm_setup_vars.yml

host_cleanup.sh
An error or interruption in `link-machine-and-node.sh` can leave a lingering `oc proxy` command. After a `make clean`, this proxy will still be running, and the `kill $proxy_pid` will error, aborting the deployment on the 06 script.
This simply adds a `pkill` to the `host_cleanup.sh` script to get that sucker out of there.
=> add kill proxy to host_cleanup.sh

assets/templates/99_registry.yaml, ocp_install_env.sh, utils.sh
Changes required for update to RC.3
=> Changes required for 4.1.0-rc3

06_create_cluster.sh
After our 4.1 rc3 update, it appears we now also require the
cloud.openshift.com pull secret.  Validate that it is present before
attempting an install.
=> Check for cloud.openshift.com pull secret.

bootkube_log.sh
A pretty common need is to follow the bootkube log from the bootstrap
VM.  I wrote this quick and dirty script to make that a little easier
on myself, at least for the standard dev-scripts setup that's using
the libvirt baremetal network.
=> Add bootkube_log.sh.

08_deploy_bmo.sh
https://github.com/openshift-metal3/dev-scripts/issues/548
=> Add issue link tracking baremetal-operator update.

common.sh, config_example.sh, utils.sh
If one wants to test an installer they built from git, a developer can override the installer by saying:
```console
export OPENSHIFT_INSTALLER="~/go/src/github.com/openshift-metalkube/kni-installer/bin/kni-install"
make
```
This could also be a little more helpful, like actually building the installer.  This PR would require the user to have already built it.
=> Support running installer from other locations

08_deploy_bmo.sh
This was a workaround that is no longer necessary since we're now
using a new enough release of OpenShift that includes the fix.
The upstream fix was here:
https://github.com/metal3-io/cluster-api-provider-baremetal/pull/58
and it was backported here:
https://github.com/openshift/cluster-api-provider-baremetal/pull/21
The current release we're using can be checked using:
oc adm release info quay.io/openshift-release-dev/ocp-release:4.1.0-rc.3 -a ~/pull-secret.json --commits | grep baremetal
baremetal-machine-controllers https://github.com/openshift/cluster-api-provider-baremetal 8a27778353fb5f236593cdee112d4542e6f96929
This commit is past when the fix was merged into
openshift/cluster-api-provider-baremetal.
=> Remove machine-api-controllers restart.

06_create_cluster.sh, ocp_install_env.sh
This is needed for us to properly support the api-int DNS name on
baremetal. It is a prerequisite to the installer change:
https://github.com/openshift-metal3/kni-installer/pull/82
See #538 for further details.
=> Add api_vip to install-config.yaml

run_ci.sh
This fixes testing installer PR's in CI.
In #558, I added the ability to run the installer from git, assuming
that CI would check out the repo to $GOPATH, but that was an incorrect
assumption. It gets checked out to $HOME. We need it in the list of
projects that gets moved to $GOPATH, if the path exists.
This does not affect the behavior of installation from release payloads
by default.
=> Add kni-installer to projects that get moved to $GOPATH

assets/files/etc/kubernetes/manifests/coredns.yaml, assets/files/etc/kubernetes/static-pod-resources/coredns/Corefile.template
Add a static mdns record that points to the API VIP. This is to
support the new required DNS record from OpenShift.
=> Add api-int DNS record to coredns

ocp_install_env.sh
If the pull secret isn't on a single line, it messes up the formatting in install-config.yaml resulting in errors like:
```
"level=fatal msg="failed to fetch Master Machines: failed to load asset \"Install Config\": failed to unmarshal: error converting YAML to JSON: yaml: line 103: did not find expected key""
```
=> Compact pull secret onto one line

common.sh
We had been defaulting to "latest" but this isn't always
built by quay.io
=> Explicitly use the "master" for ironic images

assets/files/etc/kubernetes/static-pod-resources/coredns/Corefile.template
$CLUSTER_DOMAIN is not the correct variable to use here. It's just
named $DOMAIN.
I'm not sure how this ever worked (maybe it didn't and I messed up
testing it), but it's definitely wrong.
=> Fix Corefile domain reference

host_cleanup.sh
When cleaning up the interface, remove the interface itself from the system.
The interface becomes unconfigured, though it won't delete the interface
from the system.  Ordinarily the next step would be to reboot the system,
at which time the interface would be deleted from the system.  However, not
rebooting the system could result in errors similar to: "error creating
bridge interface baremetal: File exists"
=> Also delete the interface

01_install_requirements.sh
This version now conflicts with the one from the RDO repos, so add
it to the exclude list for epel.
Fixes: #581
=> Work around python-*zmq epel conflict

ocp_install_env.sh
I believe the OPENSHIFT_RELEASE_IMAGE should be a variable again so the pinned version can be overridden. This makes testing and CI with different openshift version easier and eliminates the need to modify the file (with essentially this change) in the ci system
=> Allow OPENSHIFT_RELEASE_IMAGE to be overridden again

run_ci.sh
Currently CI tests all PR's with a checkout of kni-installer.  That's problematic, as kni-installer repo is at 4.2, but dev-scripts doesn't have the changes needed yet.
=> Only use installer from git when testing kni-installer PR

01_install_requirements.sh
The zmq workaournd was added because of a problem
caused by the zeromq workaround. But it looks like neither
are required.
=> Remove the zmq and zeromq workarounds

utils.sh
If ironic-nodes.json doesn't specify a port for BMC, the address will be
constructed like `ipmi://192.168.1.1:` with a trailing colon.  $port
must be quoted when using -n, see the warning on -n at
http://tldp.org/LDP/abs/html/comparison-ops.html.
=> Fix bug in ipmi address when not using port

vm_setup_vars.yml
This should not be required. Once
https://github.com/openshift-metal3/kni-installer/pull/82 merges
it will no longer be.
Fixes #538
=> Remove external api-int DNS entry

10_deploy_rook.sh
After updating oc client to 4.2 the --show-all=false doesn't seem to work anymore.
Fixes #599
=> Remove --show-all=false option from oc commands in 10_deploy_rook.sh

README.md, ironic_hosts.json.example
In order to prevent issues like #593 let's add worker nodes in the ironic_hosts.json.example and add a note in the README regarding the ironic nodes names format.
Fixes #593
=> Add worker nodes to the ironic_hosts.json.example and update README

06_create_cluster.sh
It looks that running fix_certs.sh can help to avoid some issues such as #590 or #570.
=> Run fix_certs.sh every minute

get_images.sh, run_ci.sh
The latest inspector image supports finding Ironic via mDNS, but this needs new IPA images.  We don't do any checks other than see if they exist; this change ensure they match a minimum supported time stamp.
=> Ensure IPA images are up to date

11_register_hosts.sh
I saw this when searching for remaining "metalkube" references.  This
appears to be unused, so just drop it.
=> Remove unused BMOPATH variable.

run_ci.sh
This was part of the jenkins job definition, moving it
here for more visibility, the code that clones dev-scripts
has to stay where it is though.
=> Move project cloning code into run_ci.sh

ocp_cleanup.sh
Reviving the PR initially pushed via #309 because I now see that
we leak bootstrap VMs/volumes when kni-installer fails while running
terraform.
This appears to be a limitation and/or design flaw with terraform as
it's not persisting state of created resources when exiting due to errors.
This is inconvenient when developing changes to the installer and/or
terraform pieces, so lets do some automated cleanup here.
Co-Authored-By: Alexander Chuzhoy achuzhoy@redhat.com
=> cleanup leaked bootstrap VM/volume after failure

06_create_cluster.sh
This lets us remove the early exit in the installer before the
underlying issue causing this is resolved.
=> Move CSR signing to before starting cluster install

run_ci.sh
Turns out this couldn't be copy/pasted from
the jenkins job as we are in a different directory.
=> Fix project cloning

assets/files/etc/kubernetes/manifests/keepalived.yaml
In case the os has 2 interfaces, keepalived.conf would be rendered incorrectly because `INTERFACE` 
will contain 2 lines with the same name:
```
[root@dhcp-0-215 ~]# ip -o addr show to 10.35.0.0/23
2: ens3    inet 10.35.1.99/23 brd 10.35.1.255 scope global dynamic noprefixroute ens3\       valid_lft 86118sec preferred_lft 86118sec
2: ens3    inet 10.35.0.215/23 brd 10.35.1.255 scope global secondary dynamic noprefixroute ens3\       valid_lft 1700sec preferred_lft 1700sec
[root@dhcp-0-215 ~]# ip -o addr show to 10.35.0.0/23 | awk '{print $2}'
ens3
ens3
```
This fix would extract `ens3` even if we have 2 addresses on the same interface 
Review: @celebdor @yboaronn 
Related to:  https://github.com/openshift-metal3/dev-scripts/issues/512
=> keepalived - extract the interface name only once

run_ci.sh
kni-installer can't be moved to openshift-metal3, it's still using openshift-metalkube.  This fixes CI so it properly tests installer PR's.
IMHO it doesn't make sense to change kni-installer's org, as we're working on getting rid of it "really soon now" :tm:.
=> Use correct path for kni-installer

04_setup_ironic.sh
In single node virtual environments, the system can get so overloaded
during deployment of the masters that the heartbeat times out, which
causes #617. This change overrides the heartbeat timeout to change
it from the default of 60 seconds to 120 seconds. In my experience,
this is sufficient to prevent the timeouts.
Note that this is making use of the environment driver[0] in oslo.config
for setting the value. I don't think we want to change the value
in the container config since it's primarily for virtual dev
environments.
0: https://docs.openstack.org/oslo.config/latest/reference/drivers.html#environment
=> Extend Ironic conductor heartbeat timeout

common.sh
In #564 we removed the mkdir like:
$ git show cdff373 | grep mkdir
-mkdir -p "$IRONIC_DATA_DIR/html/images"
But we still need IRONIC_DATA_DIR to exist, e.g to bind into the containers
We didn't catch this in CI or local testing because the images dir is cached.
=> Reinstate mkdir for IRONIC_DATA_DIR

assets/files/etc/NetworkManager/dispatcher.d/pre-up.d/dns-vip-prepender, assets/files/etc/NetworkManager/dispatcher.d/pre-up.d/dns-vip-prepender-worker
We recently had a deployment where the DNS VIP was not properly added
to resolv.conf. There isn't enough detail in the logs from the script
to determine what went wrong, so this change adds some more logging
and a sanity check that we actually did the thing we were trying to do.
=> Add sanity check to vip-prepender

run_ci.sh
bash's pushd built-in requires an argument.
On http://10.8.144.11:8080/job/dev-tools/798/console:
```
+ pushd
./run_ci.sh: line 124: pushd: no other directory
```
=> fix bash pushd requires argument

run_ci.sh
Sorry for the churn on this, adding a checkout of kni-installer in this PR to verify CI really passes. I made an assumption that we were in $HOME when CI was running.
=> Specify full path to kni-installer checkout

01_install_requirements.sh, 02_configure_host.sh, common.sh
This PR and https://github.com/metal3-io/metal3-dev-env/pull/19 contain the changes I needed to make to get dev-scripts to run on top of RHEL8.  The types of changes include:
* A number of package names are different, mostly Python related.
* A number of packages aren't available.  There's no EPEL for RHEL8 and there's also not an OSP version we can subscribe to.  This isn't a big deal.  We install a few things from source until we can pull them from OSP, and none of these things are ones that would be needed on a production environment anyway.
* The firewall setup didn't work for me.  I found it easiest to fix it using firewalld.  I suspect this has to do with changes in behavior since RHEL8 uses nftables instead of iptables.  firewalld seems like a much nicer way to manage these rules …
=> Initial support for RHEL8 as a dev environment.

01_install_requirements.sh
Without lsb_release installed, I was getting:
error while evaluating conditional (ansible_os_family == \"RedHat\"
and ansible_lsb.major_release|int == 7): 'dict object' has no
attribute 'major_release'
Introduced by RHEL8 support in commit c416cd1d
=> Ensure redhat-lsb-core is installed

ocp_install_env.sh
This image uses the openshift-metal3 quay org for the coredns-mdns
container.
See: https://github.com/openshift-metal3/kni-installer/pull/134
=> Use 4.2.0-0.ci-2019-06-19-140700-kni.3 release image

04_setup_ironic.sh, 06_create_cluster.sh, ironic_cleanup.sh
Requires https://github.com/metal3-io/ironic-image/pull/62
=> Replace multi-service ironic container with several containers

run_ci.sh
To allow for PR's from forks with names that don't match
the main repository name we've added an additional parameter
to the CI job, BASE_REPO=ORG/REPONAME, REPO hasn't changed.
An example of the values might be
+ REPO=derekhiggins/metalkube-ironic-test
+ BASE_REPO=metal3-io/ironic-image
=> Allow for forks with alt names

11_register_hosts.sh, make-bm-worker/main.go
The consumerRef should include not only the name of the consumer, but
also it's Kind and apiVersion.
Since in practice this script is used only for referencing
machine.openshift.io/v1beta1 Machine objects, just hard-code this and
revert the change of argument names from machine to consumer.
=> make-bm-worker: Include consumer kind/version

ocp_install_env.sh
The installer is capable of looking up this info from DNS itself. I've
left the $API_VIP env variable declarations in place as they do seem
used in some of the template generation.
=> Remove apiVIP from install-config.yaml

03_ocp_repo_sync.sh
https://github.com/operator-framework/operator-sdk/commit/4d13a39a3a79af634083651b244e3efe13462504 moved away from dep.
=> Remove make dep as part of operator-sdk install

utils.sh
Hardcoding to default doesn't work in BM nodes where /dev/sda
doesn't work.
=> Allow the Hardware profile for master nodes to be configured

11_register_hosts.sh, make-bm-worker/main.go
The host object API has changed to require a flag to explicitly mark hosts
as being externally provisioned. This change updates the command line tool
we use to register masters to add the flag.
Depends on https://github.com/metal3-io/baremetal-operator/pull/255
=> add externally provisioned flag when registering masters

ocp_install_env.sh
In order to generate the configuration for keepalived and coredns
(see keepalived.sh and coredns.sh) we currently determine the
DNS VIP that has been configured by querying the
ns1.$cluster_name.$base_domain record. This implies that users
must configure this record before beginning installation. In order to
reduce the pre-installation configuration requirements, we can
instead require the cluster administrator to provide the DNS VIP
as part of the configuration supplied in install-config.
Before proposing a change to the installer to support the DNS
VIP configuration, add it here to the install-config we generate,
so that the installer change can be tested.
=> Add dnsVIP to install-config

02_configure_host.sh, 08_deploy_bmo.sh, ironic_bmo_configmap.yaml, operator_ironic.yaml, run_ci.sh
Switch to using the new ironic + baremetal operator pod.
See https://github.com/metal3-io/baremetal-operator/pull/212 for some discussion re the new yaml files added here.
=> Use the new cluster hosted ironic pod to deploy the BMO

06_create_cluster.sh
some users reported issues with step06 because of an extra slash in the OS_URL
```
curl -g -X GET http://localhost:6385//v1/nodes '-H Accept: application/json -H Content-Type: application/json -H User-Agent: wait-for-json -H X-Auth-Token: fake-token'| jq .
{
"error_message": "{\"debuginfo\": null, \"faultcode\": \"Client\", \"faultstring\": \"Invalid input for field/attribute chassis_uuid. Value: ''. unable to convert to uuid. Error: Expected a UUID but received .\"}"
}
curl -g -X GET http://localhost:6385/v1/nodes '-H Accept: application/json -H Content-Type: application/json -H User-Agent: wait-for-json -H X-Auth-Token: fake-token'| jq .
{
"nodes": [
{
"instance_uuid": null,
"uuid": "6b827bbe-4d87-4c0d-9698-019b9868d0d2",
"links": [
{
"href": …
```
=> Fix issues with additional slash in OS_URL

01_install_requirements.sh, 03_ocp_repo_sync.sh
Building master operator-sdk requires go 1.12.  It's easier to just
download a release build to avoid a go version issue on some
platforms.
Closes #674
=> Install operator-sdk from a release build.

README.md
When the BMO Ironic is up and running you need a different OS_URL to
interact with it, so add a note to the README.md
=> Add details on accessing cluster-hosted ironic

06_create_cluster.sh, README.md, docs/developing-installer.md, docs/release-payload.md, ocp_install_env.sh, release/build_installer.sh, release/release_config_example.sh, run_ci.sh, utils.sh, vm_setup_vars.yml
This moves dev-scripts to use openshift/installer instead of the kni-installer fork.  We need the remaining platform PR's to be merged, but they should be soon, just waiting on CI.
What's not clear to me is how we get the baremetal platform built for openshift-install going forward (@markmc - do you know what we need to do there?).   I'm assuming in this PR we continue for at least a little while building custom KNI release payloads with an openshift-install binary that has the baremetal platform built, but at last we can discontinue use of the fork and build our installer image out of the official repos.
=> Use openshift-install instead of kni-install

04_setup_ironic.sh, ironic_cleanup.sh, operator_ironic.yaml, run_ci.sh
This patch contains changes needed to be able to use Ironic Stein.
It has dependencies from other patches in other related repos
and they should all be merged at the same time, following the order below,
to guarantee a correct behavior.
Full patch set:
https://github.com/openshift-metal3/dev-scripts/pull/680
https://github.com/metal3-io/ironic-image/pull/79
https://github.com/metal3-io/ironic-inspector-image/pull/30
https://github.com/metal3-io/ironic-ipa-downloader/pull/3
=> Changes to use Ironic Stein

run_ci.sh
Now that we are part of openshift/installer, these are already run by
their CI system.
=> Don't run openshift hack/* CI scripts in metal3 CI

02_configure_host.sh
I've had issues running the 02 script as network service won't start:
```
Jul 23 10:11:30 kni1-bootstrap.cloud.lab.eng.bos.redhat.com network[10181]: Determining IP information for baremetal...dhclient(10102) is already running - exiting.
Jul 23 10:11:30 kni1-bootstrap.cloud.lab.eng.bos.redhat.com network[10181]: This version of ISC DHCP is based on the release available
Jul 23 10:11:30 kni1-bootstrap.cloud.lab.eng.bos.redhat.com network[10181]: on ftp.isc.org. Features have been added and other changes
Jul 23 10:11:30 kni1-bootstrap.cloud.lab.eng.bos.redhat.com network[10181]: have been made to the base software release in order to make
Jul 23 10:11:30 kni1-bootstrap.cloud.lab.eng.bos.redhat.com network[10181]: it work better with this distribution.
Jul 23 10:11:30 …
```
=> Avoid multiple BOOTPROTO=dhcp in ifcfg-baremetal

Makefile
When all goes well, "make redeploy" will result in a quicker
redeployment than "make clean all".
=> Makefile: Add "redeploy" target.

01_install_requirements.sh, 03_ocp_repo_sync.sh
The repo sync script installed dep.  Move it to the dependency
installation script instead.  Also don't bother if dep is already
installed.
=> Move dep install to install script.

02_configure_host.sh
A change was made so that the BOOTPROTO=dhcp was added to $IF_INT
instead of the baremetal bridge, but this seems to break things. The
intention of 71d221654d7 seemed to be to only add the line if it didn't
already exist, this implements that.
=> Restore BOOTPROTO=dhcp to baremetal bridge interface

common.sh
This aligns with the format expected from openshift-install, and
means we can remove some backwards compatibility from the downloader
container ref https://github.com/openshift-metal3/rhcos-downloader/pull/6
=> Switch to fully qualified RHCOS image URL

08_deploy_bmo.sh, README.md
Per my comment on #676 I think this naming is clearer, and adding
info to the README will hopefully help folks who need to override
this for baremetal testing.  Ultimately we probably need a better
and more automated way to discover this at runtime though.
=> Rename PROV_IF and add docs

08_deploy_bmo.sh
A new variable was added, CLUSTER_PRO_IF, which specifies which network
interface on the deployed hosts maps to the provisioning network.  The
script assumed that the value of PRO_IF is an appropriate default.
However, PRO_IF is the interface for the provisioning network on the
provisioning host.  We should not assume that network interfaces will
be the same between the provisioning host and the deployed hosts, so
separate these two options.
=> 08_deploy_bmo: Don't assume CLUSTER_PRO_IF == PRO_IF.

06_create_cluster.sh
Some folks have seen a confusing error like:
```
Terraform variables: Unknown BMC type 'null' for address null://null\""
```
It turns out this is because the NODES_FILE created outside
of dev-scripts contains only two nodes, so the jq slice to create
the 3 masters in the install-config returns null for the missing
node.
Adding some validation here should make it clearer, but probably we should
catch this via validation in the installer.
=> Add validation for number of nodes in NODES_FILE

02_configure_host.sh
It is disabled by default in RHEL8
Fixes #688
=> Enable network service in RHEL8

ci_logs.sh
Grab the tarball and unpack it locally to help looking
for errors in failed CI runs.
=> Add helper script to grab CI logs

01_install_requirements.sh, 02_configure_host.sh, 03_ocp_repo_sync.sh, README.md, dev-setup.md, run_ci.sh
Facet development has been dormant for quite a while.  Some of the
relevant code was commented out, but we were still installing a few
unnecessary dependencies (yarn, nodejs).
Drop the facet related references from dev-scripts for now.  It can be
re-introduced when it's being actively used and we're sure the
additions are working properly.
When development of an installer UI resumes, it may take a different
form or be in a different location, so let's revisit dev-scripts
additions when that time comes.
=> Remove facet references.

ocp_install_env.sh
This won't be the final release, I just want to see if CI is OK. Once https://github.com/openshift/installer/pull/2004 makes it into a CI build, I'll build a new release with that.  Hopefully this afternoon.
=> Bump pinned release to 4.2.0-0.ci-2019-07-31-123929-kni.0

assets/templates/98_metal3_baremetalhost_crd.yaml
Until the machine-api-operator integration is finished we need the
host CRD to be defined during the installation process so the
installer can register host objects with the new cluster. This change
adds a copy of the CRD to the manifest templates so it is uploaded to
the cluster with the other manifests managed by the installer.
=> add BareMetalHost CRD

08_deploy_bmo.sh, metal3-config.yaml, operator_ironic.yaml
metal3-config is a better name for the configmap and better
matches other configmap names.
=> Rename bmo-ironic-configmap to metal3-config.

ocp_cleanup.sh
Many times I've wasted time debugging something only to realize that a
generated asset was still present and overriding something in another
component. This removes the generated directory on ocp_cleanup.sh
=> Remove assets/generated on ocp cleanup

README.md, ocp_install_env.sh
openshift/installer#2140 adds validation that the VIPs are a) in the
MachineCIDR and b) not in ClusterNetworks or ServiceNetworks.
This patch defines the MachineCIDR to EXTERNAL_SUBNET in order to
satisfy the first requirement.
=> Add MachineCIDR definition to install-config.yaml

add-machine-ips.sh
Currently add-machine-ips.sh fails when nodes hostnames are different than master-$index. This change adjusts the script so that it matches the existing machine names.
Fixes #732
=> Match existing machines in add-machine-ips.sh

04_setup_ironic.sh, 06_create_cluster.sh, common.sh, ironic_hosts.json.example, ocp_install_env.sh, run_ci.sh
This is to test with https://github.com/openshift-metal3/kni-installer/pull/100
=> WIP run Ironic on the bootstrap VM

06_create_cluster.sh, ocp_install_env.sh
- Rename OPENSHIFT_RELEASE_IMAGE_OVERRIDE to the correct OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE
- Remove reference to RELEASE_IMAGE (removed in https://github.com/openshift/installer/pull/2217)
=> Fix and clean up release image variables

README.md
Now Ironic runs on the bootstrap VM it's no longer routable on localhost, updating
=> Ironic IP is wrong in docs

link-machine-and-node.sh
In the user-agent was the term 'linck' rather than 'link'. This is just an s/linck/link/g.
=> Minor typo in link-machine-and-node.sh

01_install_requirements.sh
We're installing virtualbmc into `/usr/loca`' and the systemd unit assumes it is in `/usr`. So the service is always in `failed` state.
virtualbmc is very cunning so when you run `vbmc add`, it goes ahead and forks the daemon:
```
DEBUG VirtualBMC [-] Server at 50891 connection error: Server response timed out
DEBUG VirtualBMC [-] Attempting to start `vbmcd` behind the scenes. Consider configuring your system to manage `vbmcd` via systemd. Automatic `vbmcd` start up will be removed in the future releases!
```
Things break badly only much later because cleanup with `systemctl stop` doesn't do what we expect.
Surely Ansible's systemd module would notice the service failing to start? Apparently not! https://github.com/ansible/ansible/issues/24450
=> Fix virtualbmc service on RHEL-8

release/build_installer.sh
The default configuration (with no timeout) means that the script
to build a custom release can exit before completion due to the
default timeout being hit. This may not be an issue on a fast
environment where the build can come up quickly, but on a slightly
slower environment a timeout is wise to have.
=> Added a timeout on the wait for build in build_installer.sh

ocp_install_env.sh
As of openshift/installer#1589 the install-config format has been
locked in as the v1 version.
=> Move to v1 install-config version

run_ci.sh
The machine-api-operator managed metal3 deployment should be coming up
now (though not fully functional yet), so we should stop ignoring a
failing MAO in CI.
=> Stop ignoring a failing machine-api-operator.

docs/release-payload.md
This updates the release payload docs to discuss how the
baremetal-installer is built and where it comes from. It also updates
the instructions for building a custom release, as we should now be
using the baremetal-installer imagestream to work out of the box with
dev-scripts.
=> Update release-payload docs now that installers are included

docs/custom-mao-and-capbm.md, stop-mao.sh
The "group" is required for the cluster-version-operator overrides list.
=> fix instructions for patching cluster-version-operator to ignore machine-api-operator

README.md
It is being removed in https://review.opendev.org/#/c/677795/.
Use 'none' auth_type instead.
=> Stop recommending deprecated OS_URL

common.sh
We'll need this when https://github.com/openshift/installer/pull/2264 lands.  
Eventually we can avoid this if and when https://github.com/openshift/installer/pull/2092 lands, otherwise there's not a convenient way to get the data out of the installer.
=> Update rhcos to 42.80.20190827.1

03_build_installer.sh, 04_setup_ironic.sh, 06_create_cluster.sh, Makefile, common.sh, ocp_install_env.sh, rhcos.sh, run_ci.sh
Instead of hardcoding the RHCOS version in dev-scripts, by re-ordering
some things like extracting/building the installer first, we can use the
rhcos.json from the installer to find out which RHCOS version we should
be using.
=> Always use RHCOS version from installer

04_setup_ironic.sh
When we have an existing cache we need to wait
for them to be updated. Without this the bootstrap VM
will most likely look at the cache before its updated
and download images over the web(only the first run after
an image version changes).
=> Wait for downloader containers to finish

11_register_hosts.sh
The journey of #260 continues.
This was previously removed because automatic CSR approval was working
for workers.  Automatic CSR approval has stopped working because a
piece of required information (the hostname) is no longer present on
Machine objects.
The hostname is copied to the Machine from the hardware introspection
data on the BareMetalHost.  Ironic was updated to support reporting
the hostname received via DHCP here: https://review.opendev.org/#/c/663991/
More history about adding this to the baremetal-operator is here:
https://github.com/metal3-io/baremetal-operator/issues/190
Ironic was downgraded in OCP 4.2, meaning we lost the change to report
the hostname.  We'll need this cron job until we're able to upgrade
Ironic again.
For more information about automated CSR approval, …
=> Restore fix_certs cron job.

common.sh
Ensure if a go program crashes we get a coredump (especially to nail
down that's causing https://github.com/openshift/oc/issues/58).
To get the dump, use coredumpctl:
coredumpctl -o oc.coredump dump /usr/local/bin/oc
=> Set GOTRACEBACK=crash by default

common.sh
This sets an environment variable that makes `oc` not use unpigz to
decompress docker image layers but instead use the slower gzip
library in golang. There is a race condition that causes `oc` to
sometimes panic.
See: https://github.com/openshift/oc/issues/58
This environment variable is read by https://github.com/openshift/oc/blob/master/vendor/github.com/docker/docker/pkg/archive/archive.go#L165.
=> Fix race condition in `oc` by disabling unpigz

utils.sh
Switching from machine type i440fx to q35 results
in the naming of network devices being changed.
See metal3-dev-env
=> Switch the default for CLUSTER_PRO_IF

README.md, clouds.yaml
It's far easier to use a clouds.yaml file, so let's add one instead of
setting the endpoint URL directly. This allows openstack commands that
talk to ironic and ironic-inspector to both work with the same
configuration.
=> add clouds.yaml and update instructions for accessing ironic

01_install_requirements.sh
I hit a problem due to having an old python-openstackclient installed.
Adding -U to the pip3 install command fixes this by ensuring
dependencies are updated if available.
=> rhel8: Add -U to pip3 install commands.

README.md
We discovered that older versions of the tool do not work properly
with clouds.yaml.
=> document that python-openstackclient 3.19.0 or higher is required

01_install_requirements.sh
Some pip installs fail if we don't have the python-devel environment
installed prior to doing the install, in particular this seems to
break with the latest versions of python-libvirt on a minimal
install which lacks the devel libraries.
=> Install python36-devel before doing pip install

11_register_hosts.sh
With https://github.com/openshift/installer/pull/2087 in place the
hosts for master nodes will be registered by the installer so we can
drop the step from dev-scripts.
=> drop master host registration

01_install_requirements.sh
Testing with https://github.com/metal3-io/metal3-dev-env/pull/54 which switches to a packaged virtualbmc for RHEL8 and attempts to help us de-duplicate installing other required packages that are common to both metal3-dev-env and dev-scripts usage.
=> Use metal3-dev-env to install packages

run_ci.sh
Otherwise, we use the wrong installer binary (openshift-baremetal-install vs openshift-install).
=> Set KNI_INSTALL_FROM_GIT before sourcing common.sh

04_setup_ironic.sh
This won't work and isn't needed in the case where
NODES_PLATFORM is set to e.g "baremetal", in which case
we don't configure the vbmc host directories and thus
the containers fail to start.
This was missed in #815 which switched over to the containerized
vbmc services.
=> Only start vbmc containers for default NODES_PLATFORM

01_install_requirements.sh, 02_configure_host.sh, 04_setup_ironic.sh, README.md, assets/files/etc/sysconfig/crio-storage, assets/templates/99_local-registry.yaml.optional, common.sh
Add the ability for the bootstrap node to pull localy
built images for development and ci jobs.
=> Pull locally built ironic images for use on bootstrap node

04_setup_ironic.sh, common.sh, config_example.sh, run_ci.sh
Use upstream container images for the containers that
make up the ironic/bmo pod.
=> Add option to use upstream images for ironic

run_ci.sh
Use BASE_BRANCH to represent the branch a PR is
opened against. We've change the scripts that
trigger run_ci.sh to pass this down the line.
Fixes: #822
=> Add support to test against alternative branches

01_install_requirements.sh, common.sh
Switch to 4.3, and chase the latest passing CI image since the
nightly builds aren't yet working
=>  Use latest 4.3 CI release

run_ci.sh
We need to clone project directories first
then set variables based on what directories exist
then import common.sh
=> run_ci.sh: move things around to happen in the correct order

common.sh
common.sh is sourced at the top of 01_install_requirements.sh, where
jq may not be installed yet.
=> Use grep instead of jq to get LATEST_CI_IMAGE

04_setup_ironic.sh, common.sh
Its does the same thing as the openshift version, so we're gonna
drop the metal3 one.
=> Switch to using the openshift downloader image

mariadb-password.yaml, utils.sh
The mariadb password will be generated and added to the openshift-machine-api namespace by the machine-api-operator and can be removed from here.
=> Remove creation of mariadb password

run_ci.sh
This directory won't exist once we stop logging
to files.
Directory wont exist after https://github.com/metal3-io/ironic-image/pull/97
=> Don't copy /../ironic/log after CI

run_ci.sh
For space reasons, We've moved WORKING_DIR onto the
BTRFS filesystem, this is chewing up diskspace so we
need to disable COW on this directory.
=> Disable copy on write on the WORKING_DIR

02_configure_host.sh
Currently this is hard-coded and will mean the ports are blocked
when testing with more than 6 nodes in total, ideally we'll move
this to the vm-setup roles in metal3-dev-env (which has the same
issue) but for now this is a quick fix to enable testing with
more than 3 workers.
=> Calculate vbmc max port based on number of nodes

01_install_requirements.sh, common.sh
This PR changed the way go gets installed so we need
to install the required ansible role and update the
PATH.
Note this installs go 1.12 to /usr/local/go but the
packages version still exists elsewhere on the
system paths.
Closes: #837
=> Updates for metal3-dev-env/pull/113

06_create_cluster.sh
It can be helpful to iterate on ocp_cleanup.sh && 06_create_cluster.sh
for installer testing but currently this fails because the ocp dir is
removed
=> Add mkdir for ocp in 06_create_cluster.sh

01_install_requirements.sh, 02_configure_host.sh, common.sh, host_cleanup.sh
For development of metal3-dev-env it's convenient to have an
override that forces use of a local checkout instead of the one
cloned under WORKING_DIR, e.g:
export METAL3_DEV_ENV="/home/shardy/metal3-dev-env"
=> Add override for metal3-dev-env testing

common.sh
If `go` command is not available in default PATH, `go env` call fails,
``` bash
+++ go env
common.sh: line 3: go: command not found
++ eval ''
```
This change adds extra check to assert `go` binary is available in
default PATH, and if not prepend it with '/usr/local/go/bin'
=> Assert 'go' command is available before calling `go env`.

vm_setup_vars.yml
In https://github.com/metal3-io/metal3-dev-env/pull/129/
and https://github.com/metal3-io/metal3-dev-env/pull/102
there are proposals to switch to a single "node" flavor
for metal3-dev-env testing.
Since we require master/worker flavors I proposed the templating
in https://github.com/metal3-io/metal3-dev-env/pull/129 such
that we can override the default flavors map and that's what
is done here - we'll need to land this when metal3-dev-env/129
lands.
=> Define flavors in vm_setup_vars.yml

ocp_install_env.sh
https://github.com/coreos/coreos-assembler/pull/924 was merged, so we shouldn't need this patch anymore.
=> Remove disk space patches

04_setup_ironic.sh, common.sh, config_example.sh
Or, in other words, let's not hardcode it anymore
=> Make local registry address configurable

common.sh, ocp_install_env.sh
RHCOS bump is passing and https://github.com/openshift/installer/pull/2666 to be merged in openshift/installer. We can drop the last workaround when it gets merged and lands in a CI build.
=> Remove last workaround

01_install_requirements.sh, common.sh
OpenShift installer `master` has moved to 4.4, we should too.
=> Update to OpenShift 4.4

01_install_requirements.sh
we will  rely on the settings in metal3-dev-env and maybe introduce some additional flag later
https://github.com/metal3-io/metal3-dev-env/blob/master/centos_install_requirements.sh#L9..L13
ref:
https://github.com/openshift-metal3/dev-scripts/issues/600
currently the function which gets disabled via this MR does not have effect
=> remove duplicate selinuxenabled logic

README.md, config_example.sh, ocp_install_env.sh
OVN network can be deployed by exporting
NETWORK_TYPE as OVNKubernetes, defaults
to OpenShiftSDN.
=> add NETWORK_TYPE in install-config.yaml

README.md, ignition/file_example.ign, utils.sh
For master/worker nodes we may need to test customizations applied
via ignition, this provides an interface to enable that in the
dev-scripts environment.
=> Add IGNITION_EXTRA for testing ignition customization

01_install_requirements.sh
Recent 4.4 CI builds are missing the buildDate and it's causing errors
in dev-scripts. We're mostly interested that the initial `oc` client
is the specified version, the buildDate check was introduced during 4.3
to ensure our build had a specific fix.
Note: the recent CI builds are *also* missing gitVersion, but at least
this doesn't cause a problem when it's blank, other than forcing a new
client download.
fixes #862
=> Don't rely on build date for `oc`

common.sh
When running on a disconnected install, the host does not
have access to curl for the image version. But we can provide
it on config file. So avoid looking for that release if
we already are providing it.
=> Do not curl for release image if we provide it

04_setup_ironic.sh, common.sh, metal3-config.yaml, ocp_install_env.sh, rhcos.sh, run_ci.sh, utils.sh
Due to the image being renamed from ironic-rhcos-downloader to
ironic-machine-os-downloader, this accounts for that change in
dev-scripts.
=> Rename RHCOS to Machine OS

ocp_install_env.sh, run_ci.sh
After the installer PR merges (https://github.com/openshift/installer/pull/2821), we must remove this patch.
=> Remove patch for ironic-machine-os-downloader rename

common.sh
This directory may be owned by root for older uses of dev-scripts, so
this changes the permissions as a one-time operation to fix existing
installs.
=> Adjust permissions on Ironic images directory

01_install_requirements.sh, 02_configure_host.sh, 04_setup_ironic.sh, common.sh, config_example.sh, ocp_install_env.sh, utils.sh
Add SSL support for local mirror.
There are issues while using local mirror that doesn't support SSL.
Current change addresses this limitation.
=> Add SSL support to local mirrored registry

02_configure_host.sh
This fails with an error like:
panic: assignment to entry in nil map
When REGISTRY_CREDS contains {} - it seems that
podman login reads this file and panics due to the empty
content, but having a non-existent file works fine.
=> Remove authfile prior to initial podman login

01_install_requirements.sh, common.sh
Otherwise we re-download oc every deploy when testing with 4.3 builds
=> Don't hardcode oc_version

common.sh
Previously [0] would set the release override to the ci image instead
of the local one that we need to use when mirroring. This change moves
the logic for setting it into a common location where the image
override will be set correctly regardless of what combination of env
vars is in use.
0: https://github.com/openshift-metal3/dev-scripts/blob/1536fdeaeac964ecc27e876ec3e509e09563b93d/common.sh#L82
=> Always use local release with MIRROR_IMAGES

04_setup_ironic.sh, common.sh
This is undefined as exposed by setting
set -euxo pipefail in the 04 script.
Setting that is also desirable because
currently we ignore any failure in the
oc adm release mirror because the results
are piped to tee.
=> Define default for KNI_INSTALL_FROM_GIT

04_setup_ironic.sh
We don't need to extract the installer if we know we'll build it from source.
=> Only extract installer when not building from source

common.sh
Move the initialization of WORKING_DIR earlier in common.sh so it
comes before the first use to avoid errors due to the variable not
being defined.
=> handle unset variables

02_configure_host.sh
On RHEL 8, when ifdown is run on a bridge's only (or last up) interface,
then the bridge is deleted. However, when ifup is run on the bridge's
interface, it is not correspondingly run on the bridge itself.
See:
https://github.com/fedora-sysv/initscripts/blob/rhel8-branch/network-scripts/ifdown-eth#L144
Since the provisioning interface is bounced with ifup/ifdown after
bringing the bridge up, then the bridge itself ends up not existing.
This patch adds an additional call to ifup the provisioning bridge after
bouncing the interface.
Signed-off-by: James Slagle <james.slagle@gmail.com>
=> Run ifup on provisioning bridge after bouncing interface

ocp_cleanup.sh
These can get left as the --remove-all-storage doesn't remove them
(they're passed via -fw-cfg not strictly owned by the domain).
=> ocp_cleanup: Remove any stale .ign volumes

01_install_requirements.sh, common.sh
Modify the way we calculate the actual OC version - the previous string manipulation doesn't work so we ended up downloading the client every time.  Also make a similar change to improve the regex used to extract OPENSHIFT_VERSION from the release pullspec.
=> Fix some issues calculated the openshift version

common.sh
On EL8 and podman, you get an error like this when running as a non-root-user:
```
sudo -E podman pull --authfile combined-pullsecret--l08EkMYeFz registry.svc.ci.openshift.org/ocp/release:4.4.0-0.ci-2020-01-23-160905
Error: could not get runtime: error creating runtime static files directory /var/lib/containers/storage/libpod: mkdir /var/lib/containers/storage: permission denied
```
This is due to XDG_RUNTIME_DIR variable being set, and us copying the
user's environment with sudo -E. This is fixed in podman 1.4.4 or later,
however RHEL8 is only at 1.4.2 and it doesn't look like the fix has
been backported, at least as of 1.4.2-6.
=> Workaround error with podman when XDG_RUNTIME_DIR is set

06_create_cluster.sh
The default configuration listens on IPv4 only.  With this
configuration, it seems to be listening on both IPv4 and IPv6
(localhost), so this should be a safe default in all cases for
dev-scripts.
=> Make dnsmasq listed on IPv6

06_create_cluster.sh
The default configuration listens on IPv4 only.  With this
configuration, it seems to be listening on both IPv4 and IPv6
(localhost), so this should be a safe default in all cases for
dev-scripts.
=> [release-4.3] Make dnsmasq listed on IPv6

01_install_requirements.sh, common.sh
The openshift CI jobs will extract `oc` from one of the containers,
and the version isn't determinable from images built in CI. This also
lets a user override the OPENSHIFT_VERSION in case they want to
install some specific version for some reason.
=> Change handling of client utility installs to allow CI installations of dev-scripts

04_setup_ironic.sh, utils.sh
In openshift CI the URL takes the form
registry.svc.ci.openshift.org/ci-op-45stc91l/release:latest
we need to allow for the "-"'s in ci-op-45stc91l
=> Allow for RELEASE_IMAGE URL with a "-"

utils.sh
In dev-scripts we copy install-config.yaml to a temp file, as the
installer deletes it after it's consumed. We do not need to do this;
the installer keeps a copy of the install-config in it's generated
assets. It can be recovered with `create install-config` command, if
needed.
Between `create manifests` and `create cluster`, we restore our original
file. The installer reads it twice. However, if there's *any*
discrepancy at all, then the installer thinks things are dirty and
regenerates all of the assets (see error below). And the two versions
can differ, as the installer modifies it!! For example, due to the
presence of deprecated parameters that need converting.
```
level=warning msg="Discarding the Openshift Manifests that was provided in the target directory because its dependencies …
```
=> Stop using install-config.yaml.tmp

host_cleanup.sh
These are added as part of the dev-scripts run, but they aren't
removed by make clean. This is currently causing failures due to a
dependency issue between epel and tripleo.[0] Removing them when
cleaning should fix the problem.
0: #922
=> Remove tripleo repos when cleaning

common.sh, utils.sh
We only want to generate these cert files when necessary, either on
a new deployment of the registry or when the cert files change.
The previous check for existence meant the latter case wasn't handled
correctly. Even if we fixed that somehow, the md5 check later wasn't
effective either because the directory is bind mounted into the
container so we're essentially checking that the md5 of the file
matches itself.
To address these issues, I've added a version number to the cert and
key files for the registry. If/when we make further changes to the
cert configuration for the registry we just need to bump that version
to force an update of the registry. The registry restart is also
explicitly requested any time the certs are re-generated so we don't
have to try to figure out which cert is in …
=> Version local registry cert files

01_install_requirements.sh, common.sh, metal3-config.yaml.template, metal3-templater.go, ocp_install_env.sh, run_ci.sh, utils.sh
In 4.4, we will no longer require any configmap at all. In 4.3 however,
we still need to provide the full configmap, as well as exclude the
install-config parameters that haven't been backported yet
=> Restore 4.3 compatability, remove configmap in 4.4

01_install_requirements.sh, README.md, common.sh, sanitychecks.sh
This PR addresses issue #895.
A couple of sanity checks have been added to verify that:
1) The WORKING_DIR is world readable
2) Enough free space is available to successfully setup dev-scripts. Since this value can be difficult to estimate precisely, it can be configured via the MIN_SPACE_REQUIRED setting, by default set to 80Gb
To minimize the impact on the existing code, these checks have been placed in a separate script invoked just after commons.sh
=> Add sanity checks to verify the working dir

01_install_requirements.sh, config_example.sh, metal3-dev/run.sh
This is only required when running the BMO locally so
lets only install it when needed - this saves us several
minutes in every CI run :)
=> Don't always install operator-sdk

common.sh, sanitychecks.sh
This issue was mentioned in #900 but I missed it when
merging - we need to ensure world-readable access to
the entire path, not only the $WORKING_DIR which may
be a subdirectory.
Also made the script executable and moved a variable to
enable easier local testing, and reversed the order of
the size and access test (the size test will always fail
if the directory is not readable, so we should check for
access first).
=> Fix world-readable check in sanitychecks.sh

README.md
The 03_build_installer.sh script is run when "make" is executed, however
it was not mentioned in README.md. Manually running the scripts as shown
in README.md prior to this patch would result in an error as the ocp
installer was never extracted.
=> Add 03_build_installer.sh to README.md

common.sh
The RHEL8 var comparison is used later to check
for the right OS, but the var is just defined if
we are on the RHEL8 case. Be sure to always export
this var as false before, so we have it correctly
defined and do not fail the comparison later.
=> Always export RHEL8 var

ironic_hosts.json.example, utils.sh
This new flag was added to skip certificate checking
in the case of non-trusted certificate. This is useful
for development environment. So adding the option in
dev-scripts to be able to use the flag in the nodes.
=> Add new setting to disable certificate verification

docs/custom-mao-and-capbm.md
The referenced one does not exist, it needs to be
machine-api-controllers instead
=> Update documentation to reflect the deployment to delete

02_configure_host.sh
In https://github.com/metal3-io/metal3-dev-env/pull/215
I'm trying to remove the dependency on RDO repos, where
crudini is installed from - instead we can use an ansible
ad-hoc command to do the same thing.
=> Replace crudini usage with ansible

common.sh
Sets a value for $PS4 which will log the script name and line number,
and function name (if applicable).
As most of the scripts already run -x, this doesn't really add any extra
verbosity and is very helpful when reviewing logs and failures.
=> Use a better value for $PS4

01_install_requirements.sh
This changes go version to 1.13 so we can build installer from source.
https://github.com/openshift/installer/pull/2745 has landed requiring us to use 1.13.
=> Handle installer move to go 1.13

02_configure_host.sh, config_example.sh, ocp_install_env.sh, utils.sh
Sticking to the same defaults as the metal3-dev-env support
for consistency.
=> Add support for provisioning over IPv6

02_configure_host.sh
This is needed since https://github.com/metal3-io/metal3-dev-env/pull/231
otherwise the ansible playbook fails due to the undefined variable.
=> Add nodes_file when running metal3-dev-env setup

04_setup_ironic.sh, run_ci.sh
coredns-mdns is somewhat unique in that it doesn't become its own
image, it gets included in the coredns image as a vendored plugin.
Because of this, we need a bit more logic around building proposed
changes than just exporting the appropriate local image env var.
This change adds the ability to override the Dockerfile name for the
image build in dev-scripts (because coredns is also unusual in that
way) and adds the necessary steps to clone and update the coredns
code so it can be built with the proposed change.
=> Add support for coredns-mdns to run_ci.sh

run_ci.sh
This was missed in the original commit of coredns-mdns ci. Without
it the go mod commands fail because there is no project for them to
work on.
=> cd into coredns directory before updating module

02_configure_host.sh, 03_build_installer.sh, 04_setup_ironic.sh, 06_create_cluster.sh, README.md, common.sh, host_cleanup.sh, ironic_cleanup.sh, ocp_cleanup.sh, ocp_install_env.sh, run_ci.sh, show_bootstrap_log.sh, utils.sh, vm_setup_vars.yml
This set of changes is the first in a series to support running
dev-scripts multiple times on the same host to create multiple
clusters. With these changes in place, the files created end up either
in cluster-specific locations or with the cluster name in the file
name. It is also possible to control the names of the provisioning and
baremetal networks using variables in the config file and control the
starting value for the VMBC ports used by the emulator.
=> support better per-cluster naming

01_install_requirements.sh
Fixes an undefined variable, and adds --client so we don't block waiting to report API versions, only the client
=> Some fixes to the oc client install

README.md, ocp_cleanup.sh, run_ci.sh
These will break when we move the baremetal network to ipv6 ref #951 and also we missed a couple of references to the "baremetal" network in #948
=> Fix some hardcoded network references

common.sh
Otherwise this is undefined on other platforms which can
lead to an error.
=> Default CENTOS8 variable

02_configure_host.sh, common.sh, config_example.sh
Support was added in metal3-dev-env[0] for using custom hostname
formats for the Ironic nodes. This adds the necessary configuration
variables to dev-scripts to override the master and worker hostnames.
Real deployments frequently won't use master-X hostnames so it is
important that we can test those formats in a virtual environment.
0: https://github.com/metal3-io/metal3-dev-env/commit/3cf4203ffeb66a30bf5bf71efc462e7b8adbeb9f
=> Wire in hostname format parameters

host_cleanup.sh
This accidentally got dropped in [0]. It's still needed to prevent
dependency issues on re-deploy.
0: https://github.com/openshift-metal3/dev-scripts/commit/f64ebda3671a6d6e7620898181e0648b40b5a9f3
=> Re-add tripleo repo cleanup

01_install_requirements.sh
This currently doesn't work as we compare e.g
4.5.0-202002280431-79259a8 '!=' 4.5 and thus the
tarball gets downloaded every time (which can take
up to a minute in my environment).
=> Rework caching of oc tarball

02_configure_host.sh
Allow connections from the baremetal network to the sushy-tools
service providing the redfish emulator.
=> add iptables rule for redfish service

vm_setup_vars.yml
I'm seeing k8s-prometheus pods fail because of lack of CPU resources.
Give masters 8 vCPUs instead of 4.
=> Give masters 8 vCPUs

02_configure_host.sh
At least on CentOS 8 as deployed by packet.net, firewalld is installed
but not running by default.  This should be safe, even if it's already
enabled and running.
=> Ensure firewalld is running

02_configure_host.sh, common.sh
This moves us to using firewalld with ansible, and changes the VBMC
rules to calculate the max port based on the number of hosts.
=> Use firewalld with ansible

vm_setup_vars.yml
If we choose not to manage our bridges, we assume that those
are already created on the host. In that case we cannot use nat,
because it will conflict with the existing bridge. We need to
use bridge mode (shared physical device).
=> Forward mode of baremetal bridge needs to be flexible

.gitignore, utils.sh
Since https://github.com/metal3-io/metal3-dev-env/pull/215
openstackclient isn't installed natively by default, instead
it's run via a wrapper script which binds a directory into
the a container running the metal3-io/ironic-client image
When https://github.com/metal3-io/metal3-dev-env/pull/256
lands the wrapper script will look for a _clouds_yaml dir
in $PWD, so creating this dir will enable the containerized
client to work with dev-scripts.
We leave the existing clouds.yaml for compatibility with any
existing environments which may already have a locally installed
client.
Fixes: #971
=> Create _clouds_yaml dir for ironic-client container

04_setup_ironic.sh, common.sh, utils.sh
A CI release image pullspec looks like this:
registry.svc.ci.openshift.org/ci-op-cl986sps/release@sha256:a680697fcb21ae298d2ee4d25ca16f641c674bf3d5db6d670fe8a8bd03db5b89
Any raw pullspec that has a hash in it does not work with image
mirroring. This fixes it by properly handling this case.
=> Fix mirroring openshift CI images

04_setup_ironic.sh
Without this, attempts to curl from ipv6 fail with:
curl: (3) [globbing] error: bad range specification after pos 9
-g tells curl to disable globbing so it will just use the url as
provided.
Closes #976
=> Add -g to curl commands that might get ipv6 addresses

ocp_install_env.sh
When the installer runs, it removes the install config file, which
makes debugging a failed deployment more challenging. Make a backup
copy when we produce the real output file.
=> save a copy of the install config

ocp_cleanup.sh
The volume list output starts with a blank space so the grep pattern
looking for the cluster name at the start of the line was not
matching. Fix this by switching the awk to extract the volume name to
the before the grep to filter the volumes.
=> fix bootstrap vm volume cleanup

Makefile, cache_cleanup.sh, podman_cleanup.sh, registry_cleanup.sh, workingdir_cleanup.sh
Use `make realclean` to run all of the new cleaning steps, in addition
to the old ones.
cache_cleanup.sh removes user cache files related to the installer.
registry_cleanup.sh removes the local registry service and its files.
workingdir_cleanup.sh removes the entire working directory.
=> add more cleanup scripts and Makefile target

demo/launch_demo_bmo.sh, docs/custom-mao-and-capbm.md
Fix couple of places still referring to `ocp/auth` instead of
`ocp/$CLUSTER_NAME/auth` after commit f64ebda3
=> Update some docs for new cluster dir location

03_build_installer.sh, ocp_install_env.sh, rhcos.sh
If we're in OpenShift CI in an installer PR, then the installer is
built by rebasing on the target branch (i.e. master). The SHA that
`openshift-install version` reports doesn't exist on GitHub. It's only
in the environment that CI used to build the installer.
This gets the rhcos.json that's now in the baremetal-installer container. This avoids the CI problem, and avoids making any GitHub URL calls in 4.5 or later.
=> Retrieve installer sha from installer container if present

ironic_hosts.json.example, utils.sh
Create a new property boot_mode in the properties
dictionary. It can accept two values (UEFI, legacy) and
will default to UEFI. This will be passed to install-config
and will be picked by the installer.
=> Add possibility to pass boot_mode

host_cleanup.sh
So that it can be cleaned up.
Fixes: https://github.com/openshift-metal3/dev-scripts/issues/932
=> Pass NODES_FILE into teardown

README.md, common.sh
Most people have already moved to CentOS 8 or RHEL 8 at this point.
Let's give one last very clear warning that CentOS 7 is going away,
and then a bit later we can drop all related code for CentOS 7.
Closes #888
=> Deprecate CentOS 7

common.sh, utils.sh
The latest image has a bug that prevents mirroring some images, so
make it possible to specify an older version.
=> multi-cluster: make it possible to change the docker registry image

02_configure_host.sh, host_cleanup.sh, vm_setup_vars.yml
Use the cluster name as the prefix for VMs so they all have unique
names and we can tell which go with which cluster.
=> multi-cluster: pass cluster name as VM prefix

common.sh, ocp_install_env.sh
We only want to use the remote libvirt feature when configuring a
cluster for hive, so use a flag to toggle that behavior.
=> add variable to control use of remote libvirturi in install-config

common.sh
Instead of using a static default, compute a default for DNS_VIP based
on the EXTERNAL_SUBNET. This means one less value someone needs to
override in order to build secondary clusters.
=> multi-cluster: compute the DNS_VIP based on the network

04_setup_ironic.sh, utils.sh
If a new release image is published between when the local mirror is
created and when the install-config file is created, it is possible
that the releases used may not match. This causes the local mirror
to not be used, which results in either unnecessary external traffic
or complete failure, depending on the situation.
This change writes the mirrored release image to a temp file so it
can be retrieved later when install-config is generated. This way
we know the same release image is used for both.
Closes #1001
=> Ensure same release image is used for mirror and install

README.md, common.sh, config_example.sh, hive_install.sh
Include a variable for managing which hive image to use.  This makes it
easier to deploy a private build consistently.
=> multi-cluster: add script to install hive with required configuration

vm_setup_vars.yml
Update dev-scripts to specify the baremetal network subnets for IPv4
and IPv6 separate to be compatible with metal3-dev-env PR
https://github.com/metal3-io/metal3-dev-env/pull/280.
This should be harmless if it merges before the metal3-dev-env PR.
=> Specify v4 and v6 subnets to m3-dev-env

vm_setup_vars.yml
This change was missed when I updated dev-scripts to be compatible
with https://github.com/metal3-io/metal3-dev-env/pull/280
=> Fix libvirt network spec for latest metal3-dev-env

01_install_requirements.sh, vm_setup_vars.yml
Unfortunately it looks like this still isn't working, so going to revert and pin to an older metal3-dev-env commit.
When it's working we can get a dev-scripts PR open to restore this and then confirm with CI things pass.
=> Revert dual stack changes and pin metal3-dev-env

common.sh
Redfish represents what we'll want in production. Openshift
4.3 doesn't have the backports.
=> Switch over to redfish is not running 4.3

images/Dockerfile.ci
Refactor Dockerfile.ci to be used with OpenShift CI pipeline:src, required for OpenShift CI integration (see https://github.com/openshift/release/pull/8420)
=> New OpenShift CI Docker image

01_install_requirements.sh, 02_configure_host.sh, 06_create_cluster.sh, README.md, common.sh, config_example.sh, ocp_cleanup.sh, ocp_install_env.sh, run_ci.sh, vm_setup_vars.yml
This commit allows configuring a dual-stack IPv4+IPv6 environment.  It
changes a bunch of configuration to reflect that IPv4 and IPv6
settings are required at the same time, creates a dual-stack
"baremetal" network environment, and configures the OpenShift cluster
with both IPv4 and IPv6 subnets.
This isn't actually expected to result in a working OpenShift cluster
yet, but this provides a development and test environment for
dual-stack OpenShift clusters.
=> Add dual stack IPv4+IPv6 support
